operator:
  image:
    repository: registry.gitlab.com/gitlab-org/cloud-native/gitlab-operator
    tag: "3.2.1"
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
