image:
  repository: clickhouse/clickhouse-server
  tag: "26.6"
  pullPolicy: IfNotPresent

password: "e2e-clickhouse-password"

users:
  siphon:
    password: "e2e-siphon-ch-password"
  gitlab:
    password: "e2e-gitlab-ch-password"

initdbScripts: {}

persistence:
  enabled: true
  size: 20Gi

resources:
  requests:
    cpu: 1
    memory: 4Gi
  limits:
    cpu: 4
    memory: 8Gi
