// This file is @generated by prost-build.
/// Envelope for the execute_query stream. Each message carries exactly one of:
/// request (client initial), redaction exchange (server/client), result, or error.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteQueryMessage {
    #[prost(oneof = "execute_query_message::Content", tags = "1, 2, 3, 4")]
    pub content: ::core::option::Option<execute_query_message::Content>,
}
/// Nested message and enum types in `ExecuteQueryMessage`.
pub mod execute_query_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Content {
        #[prost(message, tag = "1")]
        Request(super::ExecuteQueryRequest),
        #[prost(message, tag = "2")]
        Redaction(super::RedactionExchange),
        #[prost(message, tag = "3")]
        Result(super::ExecuteQueryResult),
        #[prost(message, tag = "4")]
        Error(super::ExecuteQueryError),
    }
}
/// Client-sent initial message to start a query.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteQueryRequest {
    /// JSON DSL query string
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    /// RAW: tabular JSON rows; LLM: GOON text
    #[prost(enumeration = "ResponseFormat", tag = "2")]
    pub format: i32,
    /// defaults to JSON DSL
    #[prost(enumeration = "QueryType", tag = "3")]
    pub query_type: i32,
}
/// Server-sent final message with query results.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteQueryResult {
    #[prost(message, optional, tag = "3")]
    pub metadata: ::core::option::Option<QueryMetadata>,
    #[prost(oneof = "execute_query_result::Content", tags = "1, 2")]
    pub content: ::core::option::Option<execute_query_result::Content>,
}
/// Nested message and enum types in `ExecuteQueryResult`.
pub mod execute_query_result {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Content {
        /// format = RAW: structured JSON
        #[prost(string, tag = "1")]
        ResultJson(::prost::alloc::string::String),
        /// format = LLM: compact text
        #[prost(string, tag = "2")]
        FormattedText(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryMetadata {
    /// e.g. "traversal", "aggregation", "search"
    #[prost(string, tag = "1")]
    pub query_type: ::prost::alloc::string::String,
    /// compiled ClickHouse SQL(s) for debugging
    #[prost(string, repeated, tag = "2")]
    pub raw_query_strings: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// rows returned after redaction (and cursor slicing if applicable)
    #[prost(int32, tag = "3")]
    pub row_count: i32,
    /// semver string, e.g. "1.0.0"; empty for stub formatters
    #[prost(string, tag = "4")]
    pub format_version: ::prost::alloc::string::String,
    #[prost(enumeration = "FormatName", tag = "5")]
    pub format_name: i32,
}
/// Server-sent error when query compilation or execution fails.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteQueryError {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
    /// e.g. "compile_error", "execution_error"
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
}
/// Request to retrieve the graph schema with optional node expansion.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetGraphSchemaRequest {
    /// node names to include full properties/relationships; pass "\*" to expand all
    #[prost(string, repeated, tag = "1")]
    pub expand_nodes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// RAW: StructuredSchema; LLM: TOON text
    #[prost(enumeration = "ResponseFormat", tag = "2")]
    pub format: i32,
}
/// Schema response — exactly one of structured or text depending on format.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGraphSchemaResponse {
    #[prost(oneof = "get_graph_schema_response::Content", tags = "1, 2")]
    pub content: ::core::option::Option<get_graph_schema_response::Content>,
}
/// Nested message and enum types in `GetGraphSchemaResponse`.
pub mod get_graph_schema_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Content {
        /// format = RAW
        #[prost(message, tag = "1")]
        Structured(super::StructuredSchema),
        /// format = LLM (TOON notation)
        #[prost(string, tag = "2")]
        FormattedText(::prost::alloc::string::String),
    }
}
/// Full structured schema with domains, nodes, and edges.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StructuredSchema {
    #[prost(string, tag = "1")]
    pub schema_version: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub domains: ::prost::alloc::vec::Vec<SchemaDomain>,
    #[prost(message, repeated, tag = "3")]
    pub nodes: ::prost::alloc::vec::Vec<SchemaNode>,
    #[prost(message, repeated, tag = "4")]
    pub edges: ::prost::alloc::vec::Vec<SchemaEdge>,
}
/// Logical grouping of related node types (e.g. "ci", "core", "plan").
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SchemaDomain {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub node_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// A node type in the ontology. Properties, style, and edges are only
/// populated when the node name appears in expand_nodes.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SchemaNode {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub domain: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub primary_key: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub label_field: ::prost::alloc::string::String,
    /// populated when expanded
    #[prost(message, repeated, tag = "6")]
    pub properties: ::prost::alloc::vec::Vec<SchemaProperty>,
    /// populated when expanded
    #[prost(message, optional, tag = "7")]
    pub style: ::core::option::Option<SchemaNodeStyle>,
    /// populated when expanded
    #[prost(string, repeated, tag = "8")]
    pub outgoing_edges: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// populated when expanded
    #[prost(string, repeated, tag = "9")]
    pub incoming_edges: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// A single property on a node type.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SchemaProperty {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// e.g. "int64", "string", "datetime"
    #[prost(string, tag = "2")]
    pub data_type: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub nullable: bool,
    /// allowed values for enum-typed properties
    #[prost(string, repeated, tag = "4")]
    pub enum_values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// A named relationship type with its valid source/target combinations.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SchemaEdge {
    /// e.g. "AUTHORED", "CONTAINS", "MEMBER_OF"
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub variants: ::prost::alloc::vec::Vec<SchemaEdgeVariant>,
}
/// One valid source->target pair for an edge type.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SchemaEdgeVariant {
    #[prost(string, tag = "1")]
    pub source_type: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub target_type: ::prost::alloc::string::String,
}
/// Visual styling hints for graph rendering (Three.js dashboard).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SchemaNodeStyle {
    /// relative node size in the graph visualization
    #[prost(int32, tag = "1")]
    pub size: i32,
    /// hex color, e.g. "#6366f1"
    #[prost(string, tag = "2")]
    pub color: ::prost::alloc::string::String,
}
/// Wrapper for the redaction handshake within a streaming query.
/// Server sends `required` with resources to check, client responds with decisions.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RedactionExchange {
    #[prost(oneof = "redaction_exchange::Content", tags = "1, 2")]
    pub content: ::core::option::Option<redaction_exchange::Content>,
}
/// Nested message and enum types in `RedactionExchange`.
pub mod redaction_exchange {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Content {
        /// server -> client
        #[prost(message, tag = "1")]
        Required(super::RedactionRequired),
        /// client -> server
        #[prost(message, tag = "2")]
        Response(super::RedactionResponse),
    }
}
/// Server asks Rails to authorize a set of resources before returning results.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RedactionRequired {
    /// correlates request with response
    #[prost(string, tag = "1")]
    pub result_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub resources: ::prost::alloc::vec::Vec<ResourceToAuthorize>,
}
/// A batch of resource IDs that need authorization checks.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResourceToAuthorize {
    /// e.g. "project", "merge_request"
    #[prost(string, tag = "1")]
    pub resource_type: ::prost::alloc::string::String,
    #[prost(int64, repeated, tag = "2")]
    pub resource_ids: ::prost::alloc::vec::Vec<i64>,
    /// e.g. \["read_project"\]
    #[prost(string, repeated, tag = "3")]
    pub abilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Rails responds with per-resource authorization decisions.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RedactionResponse {
    #[prost(string, tag = "1")]
    pub result_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub authorizations: ::prost::alloc::vec::Vec<ResourceAuthorization>,
}
/// Authorization decisions for one resource type. Keys are resource IDs,
/// values are true (authorized) or false (redact).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResourceAuthorization {
    #[prost(string, tag = "1")]
    pub resource_type: ::prost::alloc::string::String,
    #[prost(map = "int64, bool", tag = "2")]
    pub authorized: ::std::collections::HashMap<i64, bool>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListToolsRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListToolsResponse {
    #[prost(message, repeated, tag = "1")]
    pub tools: ::prost::alloc::vec::Vec<ToolDefinition>,
}
/// An MCP-compatible tool definition. The Rust service is the single source of
/// truth for tool metadata — Rails passes these through to MCP and REST consumers.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToolDefinition {
    /// e.g. "query_graph", "get_graph_schema"
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// includes TOON schema context for query_graph
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    /// JSON Schema for the tool's input parameters
    #[prost(string, tag = "3")]
    pub parameters_json_schema: ::prost::alloc::string::String,
}
/// Request for cluster health, with optional LLM formatting.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetClusterHealthRequest {
    /// RAW: structured JSON; LLM: TOON text
    #[prost(enumeration = "ResponseFormat", tag = "1")]
    pub format: i32,
}
/// Health response — structured or TOON text depending on format.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetClusterHealthResponse {
    #[prost(oneof = "get_cluster_health_response::Content", tags = "1, 2")]
    pub content: ::core::option::Option<get_cluster_health_response::Content>,
}
/// Nested message and enum types in `GetClusterHealthResponse`.
pub mod get_cluster_health_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Content {
        /// format = RAW
        #[prost(message, tag = "1")]
        Structured(super::StructuredClusterHealth),
        /// format = LLM
        #[prost(string, tag = "2")]
        FormattedText(::prost::alloc::string::String),
    }
}
/// Structured cluster health with per-component breakdown.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StructuredClusterHealth {
    #[prost(enumeration = "ClusterStatus", tag = "1")]
    pub status: i32,
    #[prost(string, tag = "2")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub components: ::prost::alloc::vec::Vec<ComponentHealth>,
}
/// Health of a single service component (clickhouse, indexer, webserver).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ComponentHealth {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "ClusterStatus", tag = "2")]
    pub status: i32,
    #[prost(message, optional, tag = "3")]
    pub replicas: ::core::option::Option<ReplicaStatus>,
    /// component-specific metrics (e.g. query_latency_p99_ms)
    #[prost(map = "string, string", tag = "4")]
    pub metrics: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplicaStatus {
    #[prost(int32, tag = "1")]
    pub ready: i32,
    #[prost(int32, tag = "2")]
    pub desired: i32,
}
/// Request for graph entity counts scoped by traversal_path prefix.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetGraphStatusRequest {
    /// traversal_path prefix to scope counts (e.g. "1/2/")
    #[prost(string, tag = "1")]
    pub traversal_path: ::prost::alloc::string::String,
    #[prost(enumeration = "SourceType", tag = "2")]
    pub source_type: i32,
    /// RAW: structured JSON; LLM: TOON text
    #[prost(enumeration = "ResponseFormat", tag = "3")]
    pub format: i32,
}
/// Indexing progress metadata from the most recent indexing run.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IndexingStatus {
    #[prost(enumeration = "IndexingState", tag = "1")]
    pub state: i32,
    #[prost(string, optional, tag = "2")]
    pub last_started_at: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub last_completed_at: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "4")]
    pub last_duration_ms: ::core::option::Option<u64>,
    #[prost(string, optional, tag = "5")]
    pub last_error: ::core::option::Option<::prost::alloc::string::String>,
}
/// Response containing project coverage and entity counts grouped by domain.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGraphStatusResponse {
    #[prost(oneof = "get_graph_status_response::Content", tags = "1, 2")]
    pub content: ::core::option::Option<get_graph_status_response::Content>,
}
/// Nested message and enum types in `GetGraphStatusResponse`.
pub mod get_graph_status_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Content {
        /// format = RAW
        #[prost(message, tag = "1")]
        Structured(super::StructuredGraphStatus),
        /// format = LLM (TOON notation)
        #[prost(string, tag = "2")]
        FormattedText(::prost::alloc::string::String),
    }
}
/// Structured graph status with project coverage, entity counts, and indexing state.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StructuredGraphStatus {
    #[prost(message, optional, tag = "1")]
    pub projects: ::core::option::Option<ProjectsStatus>,
    #[prost(message, repeated, tag = "2")]
    pub domains: ::prost::alloc::vec::Vec<GraphStatusDomain>,
    #[prost(message, optional, tag = "3")]
    pub indexing: ::core::option::Option<IndexingStatus>,
}
/// How many projects under this scope have been code-indexed.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectsStatus {
    #[prost(int64, tag = "1")]
    pub indexed: i64,
    #[prost(int64, tag = "2")]
    pub total_known: i64,
}
/// Entity counts for a single domain (e.g. "ci", "core", "plan").
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GraphStatusDomain {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<GraphStatusItem>,
}
/// Count for a single entity type (e.g. "Project": 42).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GraphStatusItem {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub count: i64,
}
/// Controls output serialization across all data RPCs.
/// RAW returns structured JSON for programmatic consumers (dashboard, CLI).
/// LLM returns compact text (GOON for queries, TOON for schema/health) optimized for token budgets.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ResponseFormat {
    Raw = 0,
    Llm = 1,
}
impl ResponseFormat {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Raw => "RESPONSE_FORMAT_RAW",
            Self::Llm => "RESPONSE_FORMAT_LLM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RESPONSE_FORMAT_RAW" => Some(Self::Raw),
            "RESPONSE_FORMAT_LLM" => Some(Self::Llm),
            _ => None,
        }
    }
}
/// Concrete encoding produced by the server. QueryMetadata carries this
/// alongside format_version so consumers can route/parse without inspecting
/// the payload body. Mirrors ResponseFormat but in response context.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FormatName {
    Raw = 0,
    Goon = 1,
}
impl FormatName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Raw => "FORMAT_NAME_RAW",
            Self::Goon => "FORMAT_NAME_GOON",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FORMAT_NAME_RAW" => Some(Self::Raw),
            "FORMAT_NAME_GOON" => Some(Self::Goon),
            _ => None,
        }
    }
}
/// Query language selector. Only JSON DSL is supported today.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum QueryType {
    Json = 0,
}
impl QueryType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Json => "QUERY_TYPE_JSON",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "QUERY_TYPE_JSON" => Some(Self::Json),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ClusterStatus {
    Unspecified = 0,
    Healthy = 1,
    Degraded = 2,
    Unhealthy = 3,
}
impl ClusterStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CLUSTER_STATUS_UNSPECIFIED",
            Self::Healthy => "CLUSTER_STATUS_HEALTHY",
            Self::Degraded => "CLUSTER_STATUS_DEGRADED",
            Self::Unhealthy => "CLUSTER_STATUS_UNHEALTHY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CLUSTER_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "CLUSTER_STATUS_HEALTHY" => Some(Self::Healthy),
            "CLUSTER_STATUS_DEGRADED" => Some(Self::Degraded),
            "CLUSTER_STATUS_UNHEALTHY" => Some(Self::Unhealthy),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SourceType {
    Group = 0,
    Project = 1,
}
impl SourceType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Group => "SOURCE_TYPE_GROUP",
            Self::Project => "SOURCE_TYPE_PROJECT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SOURCE_TYPE_GROUP" => Some(Self::Group),
            "SOURCE_TYPE_PROJECT" => Some(Self::Project),
            _ => None,
        }
    }
}
/// Derived indexing lifecycle state.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum IndexingState {
    NotIndexed = 0,
    Backfilling = 1,
    Indexed = 2,
    Error = 3,
    Unknown = 4,
    Indexing = 5,
}
impl IndexingState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NotIndexed => "INDEXING_STATE_NOT_INDEXED",
            Self::Backfilling => "INDEXING_STATE_BACKFILLING",
            Self::Indexed => "INDEXING_STATE_INDEXED",
            Self::Error => "INDEXING_STATE_ERROR",
            Self::Unknown => "INDEXING_STATE_UNKNOWN",
            Self::Indexing => "INDEXING_STATE_INDEXING",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INDEXING_STATE_NOT_INDEXED" => Some(Self::NotIndexed),
            "INDEXING_STATE_BACKFILLING" => Some(Self::Backfilling),
            "INDEXING_STATE_INDEXED" => Some(Self::Indexed),
            "INDEXING_STATE_ERROR" => Some(Self::Error),
            "INDEXING_STATE_UNKNOWN" => Some(Self::Unknown),
            "INDEXING_STATE_INDEXING" => Some(Self::Indexing),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod knowledge_graph_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Core service exposing 4 RPCs. Gated behind the :knowledge_graph feature flag
    /// in Rails. JWT auth carries user identity and traversal IDs for authorization.
    #[derive(Debug, Clone)]
    pub struct KnowledgeGraphServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl KnowledgeGraphServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> KnowledgeGraphServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> KnowledgeGraphServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            KnowledgeGraphServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Returns available tool definitions with parameter schemas.
        /// Used by MCP tools/list and GET /api/v4/orbit/tools.
        pub async fn list_tools(
            &mut self,
            request: impl tonic::IntoRequest<super::ListToolsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListToolsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/gkg.v1.KnowledgeGraphService/ListTools",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("gkg.v1.KnowledgeGraphService", "ListTools"));
            self.inner.unary(req, path, codec).await
        }
        /// Executes a graph query against ClickHouse with bidirectional streaming
        /// for the redaction exchange (server requests authorization checks from Rails,
        /// Rails responds with per-resource decisions).
        /// Used by MCP tools/call("query_graph") and POST /api/v4/orbit/query.
        pub async fn execute_query(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::ExecuteQueryMessage,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ExecuteQueryMessage>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/gkg.v1.KnowledgeGraphService/ExecuteQuery",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("gkg.v1.KnowledgeGraphService", "ExecuteQuery"));
            self.inner.streaming(req, path, codec).await
        }
        /// Returns the graph ontology (nodes, edges, domains) from in-memory cache.
        /// No ClickHouse, no redaction. Supports selective node expansion.
        /// Used by MCP tools/call("get_graph_schema") and GET /api/v4/orbit/schema.
        pub async fn get_graph_schema(
            &mut self,
            request: impl tonic::IntoRequest<super::GetGraphSchemaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetGraphSchemaResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/gkg.v1.KnowledgeGraphService/GetGraphSchema",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("gkg.v1.KnowledgeGraphService", "GetGraphSchema"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Returns cluster health and component status.
        /// Used by GET /api/v4/orbit/status.
        pub async fn get_cluster_health(
            &mut self,
            request: impl tonic::IntoRequest<super::GetClusterHealthRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetClusterHealthResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/gkg.v1.KnowledgeGraphService/GetClusterHealth",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("gkg.v1.KnowledgeGraphService", "GetClusterHealth"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Returns entity counts per domain, scoped by traversal_path prefix.
        /// Used by admin dashboards to inspect graph coverage.
        pub async fn get_graph_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetGraphStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetGraphStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/gkg.v1.KnowledgeGraphService/GetGraphStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("gkg.v1.KnowledgeGraphService", "GetGraphStatus"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod knowledge_graph_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with KnowledgeGraphServiceServer.
    #[async_trait]
    pub trait KnowledgeGraphService: std::marker::Send + std::marker::Sync + 'static {
        /// Returns available tool definitions with parameter schemas.
        /// Used by MCP tools/list and GET /api/v4/orbit/tools.
        async fn list_tools(
            &self,
            request: tonic::Request<super::ListToolsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListToolsResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the ExecuteQuery method.
        type ExecuteQueryStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ExecuteQueryMessage, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Executes a graph query against ClickHouse with bidirectional streaming
        /// for the redaction exchange (server requests authorization checks from Rails,
        /// Rails responds with per-resource decisions).
        /// Used by MCP tools/call("query_graph") and POST /api/v4/orbit/query.
        async fn execute_query(
            &self,
            request: tonic::Request<tonic::Streaming<super::ExecuteQueryMessage>>,
        ) -> std::result::Result<
            tonic::Response<Self::ExecuteQueryStream>,
            tonic::Status,
        >;
        /// Returns the graph ontology (nodes, edges, domains) from in-memory cache.
        /// No ClickHouse, no redaction. Supports selective node expansion.
        /// Used by MCP tools/call("get_graph_schema") and GET /api/v4/orbit/schema.
        async fn get_graph_schema(
            &self,
            request: tonic::Request<super::GetGraphSchemaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetGraphSchemaResponse>,
            tonic::Status,
        >;
        /// Returns cluster health and component status.
        /// Used by GET /api/v4/orbit/status.
        async fn get_cluster_health(
            &self,
            request: tonic::Request<super::GetClusterHealthRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetClusterHealthResponse>,
            tonic::Status,
        >;
        /// Returns entity counts per domain, scoped by traversal_path prefix.
        /// Used by admin dashboards to inspect graph coverage.
        async fn get_graph_status(
            &self,
            request: tonic::Request<super::GetGraphStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetGraphStatusResponse>,
            tonic::Status,
        >;
    }
    /// Core service exposing 4 RPCs. Gated behind the :knowledge_graph feature flag
    /// in Rails. JWT auth carries user identity and traversal IDs for authorization.
    #[derive(Debug)]
    pub struct KnowledgeGraphServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> KnowledgeGraphServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for KnowledgeGraphServiceServer<T>
    where
        T: KnowledgeGraphService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/gkg.v1.KnowledgeGraphService/ListTools" => {
                    #[allow(non_camel_case_types)]
                    struct ListToolsSvc<T: KnowledgeGraphService>(pub Arc<T>);
                    impl<
                        T: KnowledgeGraphService,
                    > tonic::server::UnaryService<super::ListToolsRequest>
                    for ListToolsSvc<T> {
                        type Response = super::ListToolsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListToolsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as KnowledgeGraphService>::list_tools(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListToolsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/gkg.v1.KnowledgeGraphService/ExecuteQuery" => {
                    #[allow(non_camel_case_types)]
                    struct ExecuteQuerySvc<T: KnowledgeGraphService>(pub Arc<T>);
                    impl<
                        T: KnowledgeGraphService,
                    > tonic::server::StreamingService<super::ExecuteQueryMessage>
                    for ExecuteQuerySvc<T> {
                        type Response = super::ExecuteQueryMessage;
                        type ResponseStream = T::ExecuteQueryStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::ExecuteQueryMessage>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as KnowledgeGraphService>::execute_query(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ExecuteQuerySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/gkg.v1.KnowledgeGraphService/GetGraphSchema" => {
                    #[allow(non_camel_case_types)]
                    struct GetGraphSchemaSvc<T: KnowledgeGraphService>(pub Arc<T>);
                    impl<
                        T: KnowledgeGraphService,
                    > tonic::server::UnaryService<super::GetGraphSchemaRequest>
                    for GetGraphSchemaSvc<T> {
                        type Response = super::GetGraphSchemaResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetGraphSchemaRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as KnowledgeGraphService>::get_graph_schema(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetGraphSchemaSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/gkg.v1.KnowledgeGraphService/GetClusterHealth" => {
                    #[allow(non_camel_case_types)]
                    struct GetClusterHealthSvc<T: KnowledgeGraphService>(pub Arc<T>);
                    impl<
                        T: KnowledgeGraphService,
                    > tonic::server::UnaryService<super::GetClusterHealthRequest>
                    for GetClusterHealthSvc<T> {
                        type Response = super::GetClusterHealthResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetClusterHealthRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as KnowledgeGraphService>::get_cluster_health(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetClusterHealthSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/gkg.v1.KnowledgeGraphService/GetGraphStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetGraphStatusSvc<T: KnowledgeGraphService>(pub Arc<T>);
                    impl<
                        T: KnowledgeGraphService,
                    > tonic::server::UnaryService<super::GetGraphStatusRequest>
                    for GetGraphStatusSvc<T> {
                        type Response = super::GetGraphStatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetGraphStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as KnowledgeGraphService>::get_graph_status(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetGraphStatusSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for KnowledgeGraphServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "gkg.v1.KnowledgeGraphService";
    impl<T> tonic::server::NamedService for KnowledgeGraphServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
