// This file is @generated by prost-build.
/// --- ExecuteQuery ---
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteQueryMessage {
    #[prost(oneof = "execute_query_message::Content", tags = "1, 2, 3, 4")]
    pub content: ::core::option::Option<execute_query_message::Content>,
}
/// Nested message and enum types in `ExecuteQueryMessage`.
pub mod execute_query_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Content {
        #[prost(message, tag = "1")]
        Request(super::ExecuteQueryRequest),
        #[prost(message, tag = "2")]
        Redaction(super::RedactionExchange),
        #[prost(message, tag = "3")]
        Result(super::ExecuteQueryResult),
        #[prost(message, tag = "4")]
        Error(super::ExecuteQueryError),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteQueryRequest {
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    #[prost(enumeration = "ResponseFormat", tag = "2")]
    pub format: i32,
    #[prost(enumeration = "QueryType", tag = "3")]
    pub query_type: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteQueryResult {
    #[prost(string, tag = "1")]
    pub result_json: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub generated_sql: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub row_count: i32,
    #[prost(int32, tag = "4")]
    pub redacted_count: i32,
    #[prost(double, tag = "5")]
    pub execution_time_ms: f64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteQueryError {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
}
/// --- GetGraphSchema ---
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetGraphSchemaRequest {
    #[prost(string, repeated, tag = "1")]
    pub expand_nodes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(enumeration = "ResponseFormat", tag = "2")]
    pub format: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGraphSchemaResponse {
    #[prost(oneof = "get_graph_schema_response::Content", tags = "1, 2")]
    pub content: ::core::option::Option<get_graph_schema_response::Content>,
}
/// Nested message and enum types in `GetGraphSchemaResponse`.
pub mod get_graph_schema_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Content {
        #[prost(message, tag = "1")]
        Structured(super::StructuredSchema),
        #[prost(string, tag = "2")]
        FormattedText(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StructuredSchema {
    #[prost(string, tag = "1")]
    pub schema_version: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub domains: ::prost::alloc::vec::Vec<SchemaDomain>,
    #[prost(message, repeated, tag = "3")]
    pub nodes: ::prost::alloc::vec::Vec<SchemaNode>,
    #[prost(message, repeated, tag = "4")]
    pub edges: ::prost::alloc::vec::Vec<SchemaEdge>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SchemaDomain {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub node_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SchemaNode {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub domain: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub primary_key: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub label_field: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "6")]
    pub properties: ::prost::alloc::vec::Vec<SchemaProperty>,
    #[prost(message, optional, tag = "7")]
    pub style: ::core::option::Option<SchemaNodeStyle>,
    #[prost(string, repeated, tag = "8")]
    pub outgoing_edges: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "9")]
    pub incoming_edges: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SchemaProperty {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub data_type: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub nullable: bool,
    #[prost(string, repeated, tag = "4")]
    pub enum_values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SchemaEdge {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub variants: ::prost::alloc::vec::Vec<SchemaEdgeVariant>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SchemaEdgeVariant {
    #[prost(string, tag = "1")]
    pub source_type: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub target_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SchemaNodeStyle {
    #[prost(int32, tag = "1")]
    pub size: i32,
    #[prost(string, tag = "2")]
    pub color: ::prost::alloc::string::String,
}
/// --- Redaction (shared) ---
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RedactionExchange {
    #[prost(oneof = "redaction_exchange::Content", tags = "1, 2")]
    pub content: ::core::option::Option<redaction_exchange::Content>,
}
/// Nested message and enum types in `RedactionExchange`.
pub mod redaction_exchange {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Content {
        #[prost(message, tag = "1")]
        Required(super::RedactionRequired),
        #[prost(message, tag = "2")]
        Response(super::RedactionResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RedactionRequired {
    #[prost(string, tag = "1")]
    pub result_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub resources: ::prost::alloc::vec::Vec<ResourceToAuthorize>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResourceToAuthorize {
    #[prost(string, tag = "1")]
    pub resource_type: ::prost::alloc::string::String,
    #[prost(int64, repeated, tag = "2")]
    pub resource_ids: ::prost::alloc::vec::Vec<i64>,
    #[prost(string, repeated, tag = "3")]
    pub abilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RedactionResponse {
    #[prost(string, tag = "1")]
    pub result_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub authorizations: ::prost::alloc::vec::Vec<ResourceAuthorization>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResourceAuthorization {
    #[prost(string, tag = "1")]
    pub resource_type: ::prost::alloc::string::String,
    #[prost(map = "int64, bool", tag = "2")]
    pub authorized: ::std::collections::HashMap<i64, bool>,
}
/// --- ListTools ---
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListToolsRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListToolsResponse {
    #[prost(message, repeated, tag = "1")]
    pub tools: ::prost::alloc::vec::Vec<ToolDefinition>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToolDefinition {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub parameters_json_schema: ::prost::alloc::string::String,
}
/// --- ClusterHealth ---
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetClusterHealthRequest {
    #[prost(enumeration = "ResponseFormat", tag = "1")]
    pub format: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetClusterHealthResponse {
    #[prost(oneof = "get_cluster_health_response::Content", tags = "1, 2")]
    pub content: ::core::option::Option<get_cluster_health_response::Content>,
}
/// Nested message and enum types in `GetClusterHealthResponse`.
pub mod get_cluster_health_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Content {
        #[prost(message, tag = "1")]
        Structured(super::StructuredClusterHealth),
        #[prost(string, tag = "2")]
        FormattedText(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StructuredClusterHealth {
    #[prost(enumeration = "ClusterStatus", tag = "1")]
    pub status: i32,
    #[prost(string, tag = "2")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub components: ::prost::alloc::vec::Vec<ComponentHealth>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ComponentHealth {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "ClusterStatus", tag = "2")]
    pub status: i32,
    #[prost(message, optional, tag = "3")]
    pub replicas: ::core::option::Option<ReplicaStatus>,
    #[prost(map = "string, string", tag = "4")]
    pub metrics: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplicaStatus {
    #[prost(int32, tag = "1")]
    pub ready: i32,
    #[prost(int32, tag = "2")]
    pub desired: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ResponseFormat {
    Raw = 0,
    Llm = 1,
}
impl ResponseFormat {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Raw => "RESPONSE_FORMAT_RAW",
            Self::Llm => "RESPONSE_FORMAT_LLM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RESPONSE_FORMAT_RAW" => Some(Self::Raw),
            "RESPONSE_FORMAT_LLM" => Some(Self::Llm),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum QueryType {
    Json = 0,
}
impl QueryType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Json => "QUERY_TYPE_JSON",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "QUERY_TYPE_JSON" => Some(Self::Json),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ClusterStatus {
    Unspecified = 0,
    Healthy = 1,
    Degraded = 2,
    Unhealthy = 3,
}
impl ClusterStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CLUSTER_STATUS_UNSPECIFIED",
            Self::Healthy => "CLUSTER_STATUS_HEALTHY",
            Self::Degraded => "CLUSTER_STATUS_DEGRADED",
            Self::Unhealthy => "CLUSTER_STATUS_UNHEALTHY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CLUSTER_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "CLUSTER_STATUS_HEALTHY" => Some(Self::Healthy),
            "CLUSTER_STATUS_DEGRADED" => Some(Self::Degraded),
            "CLUSTER_STATUS_UNHEALTHY" => Some(Self::Unhealthy),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod knowledge_graph_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct KnowledgeGraphServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl KnowledgeGraphServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> KnowledgeGraphServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> KnowledgeGraphServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            KnowledgeGraphServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn list_tools(
            &mut self,
            request: impl tonic::IntoRequest<super::ListToolsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListToolsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/gkg.v1.KnowledgeGraphService/ListTools",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("gkg.v1.KnowledgeGraphService", "ListTools"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn execute_query(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::ExecuteQueryMessage,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ExecuteQueryMessage>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/gkg.v1.KnowledgeGraphService/ExecuteQuery",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("gkg.v1.KnowledgeGraphService", "ExecuteQuery"));
            self.inner.streaming(req, path, codec).await
        }
        pub async fn get_graph_schema(
            &mut self,
            request: impl tonic::IntoRequest<super::GetGraphSchemaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetGraphSchemaResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/gkg.v1.KnowledgeGraphService/GetGraphSchema",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("gkg.v1.KnowledgeGraphService", "GetGraphSchema"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_cluster_health(
            &mut self,
            request: impl tonic::IntoRequest<super::GetClusterHealthRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetClusterHealthResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/gkg.v1.KnowledgeGraphService/GetClusterHealth",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("gkg.v1.KnowledgeGraphService", "GetClusterHealth"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod knowledge_graph_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with KnowledgeGraphServiceServer.
    #[async_trait]
    pub trait KnowledgeGraphService: std::marker::Send + std::marker::Sync + 'static {
        async fn list_tools(
            &self,
            request: tonic::Request<super::ListToolsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListToolsResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the ExecuteQuery method.
        type ExecuteQueryStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ExecuteQueryMessage, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn execute_query(
            &self,
            request: tonic::Request<tonic::Streaming<super::ExecuteQueryMessage>>,
        ) -> std::result::Result<
            tonic::Response<Self::ExecuteQueryStream>,
            tonic::Status,
        >;
        async fn get_graph_schema(
            &self,
            request: tonic::Request<super::GetGraphSchemaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetGraphSchemaResponse>,
            tonic::Status,
        >;
        async fn get_cluster_health(
            &self,
            request: tonic::Request<super::GetClusterHealthRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetClusterHealthResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct KnowledgeGraphServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> KnowledgeGraphServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for KnowledgeGraphServiceServer<T>
    where
        T: KnowledgeGraphService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/gkg.v1.KnowledgeGraphService/ListTools" => {
                    #[allow(non_camel_case_types)]
                    struct ListToolsSvc<T: KnowledgeGraphService>(pub Arc<T>);
                    impl<
                        T: KnowledgeGraphService,
                    > tonic::server::UnaryService<super::ListToolsRequest>
                    for ListToolsSvc<T> {
                        type Response = super::ListToolsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListToolsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as KnowledgeGraphService>::list_tools(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListToolsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/gkg.v1.KnowledgeGraphService/ExecuteQuery" => {
                    #[allow(non_camel_case_types)]
                    struct ExecuteQuerySvc<T: KnowledgeGraphService>(pub Arc<T>);
                    impl<
                        T: KnowledgeGraphService,
                    > tonic::server::StreamingService<super::ExecuteQueryMessage>
                    for ExecuteQuerySvc<T> {
                        type Response = super::ExecuteQueryMessage;
                        type ResponseStream = T::ExecuteQueryStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::ExecuteQueryMessage>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as KnowledgeGraphService>::execute_query(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ExecuteQuerySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/gkg.v1.KnowledgeGraphService/GetGraphSchema" => {
                    #[allow(non_camel_case_types)]
                    struct GetGraphSchemaSvc<T: KnowledgeGraphService>(pub Arc<T>);
                    impl<
                        T: KnowledgeGraphService,
                    > tonic::server::UnaryService<super::GetGraphSchemaRequest>
                    for GetGraphSchemaSvc<T> {
                        type Response = super::GetGraphSchemaResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetGraphSchemaRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as KnowledgeGraphService>::get_graph_schema(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetGraphSchemaSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/gkg.v1.KnowledgeGraphService/GetClusterHealth" => {
                    #[allow(non_camel_case_types)]
                    struct GetClusterHealthSvc<T: KnowledgeGraphService>(pub Arc<T>);
                    impl<
                        T: KnowledgeGraphService,
                    > tonic::server::UnaryService<super::GetClusterHealthRequest>
                    for GetClusterHealthSvc<T> {
                        type Response = super::GetClusterHealthResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetClusterHealthRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as KnowledgeGraphService>::get_cluster_health(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetClusterHealthSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for KnowledgeGraphServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "gkg.v1.KnowledgeGraphService";
    impl<T> tonic::server::NamedService for KnowledgeGraphServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
