#!/usr/bin/env bash
# Regenerate siphon CDC config from the GitLab SSOT table definitions.
#
# Pulls `db/siphon/tables/*.yml` from `gitlab-org/gitlab` at the ref pinned in
# `config/versions.yaml` (gitlab.ref), filters to `database: main` (e2e PG has
# no ci/sec shards), and runs the siphon `schema generate-values` binary inside
# its docker image to emit two helm value fragments:
#
#   config/cdc-producer.yaml — `table_mapping:` for the producer deployment
#   config/cdc-consumer.yaml — `streams:` + `clickhouse.dedup_config:` for the consumer
#
# `values/siphon.yaml.gotmpl` reads both files at render time. Re-run this
# script whenever you bump `gitlab.ref` or `siphon.image.tag` in versions.yaml.
#
# Requirements: docker (or compatible runtime), yq (mikefarah, v4+).

set -euo pipefail

# shellcheck source=lib.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

VERSIONS="$E2E_DIR/config/versions.yaml"
LAYOUT="$E2E_DIR/config/siphon-layout.yaml"
OUT_PRODUCER="$E2E_DIR/config/cdc-producer.yaml"
OUT_CONSUMER="$E2E_DIR/config/cdc-consumer.yaml"

command -v docker >/dev/null || { echo "docker required"; exit 1; }
command -v yq >/dev/null || { echo "yq (mikefarah v4+) required"; exit 1; }

SIPHON_IMAGE="$(yq -r '.siphon.image.repository + ":" + .siphon.image.tag' "$VERSIONS")"
GITLAB_REF="$(yq -r '.gitlab.ref' "$VERSIONS")"

[[ "$SIPHON_IMAGE" == *":null"* || "$SIPHON_IMAGE" == "null:null" ]] \
  && { echo "siphon.image.{repository,tag} missing in $VERSIONS"; exit 1; }
[[ -z "$GITLAB_REF" || "$GITLAB_REF" == "null" ]] \
  && { echo "gitlab.ref missing in $VERSIONS"; exit 1; }

log "siphon image: $SIPHON_IMAGE"
log "gitlab ref:   $GITLAB_REF"

# Under GitLab CI with docker-in-docker the dind daemon only sees paths under
# $CI_PROJECT_DIR — /tmp lives on the runner, not the dind container, so volume
# mounts from /tmp would be empty inside the siphon container.
TMP="$(mktemp -d -p "${CI_PROJECT_DIR:-/tmp}")"
trap 'rm -rf "$TMP"' EXIT
TABLES_RAW="$TMP/tables-raw"
TABLES="$TMP/tables"
mkdir -p "$TABLES_RAW" "$TABLES"

# --- 1. Fetch SSOT tables ----------------------------------------------------
# 278964 = gitlab-org/gitlab. The repository archive API streams just the path
# we ask for, so we don't clone the whole monorepo.
ARCHIVE="$TMP/tables.tar.gz"
URL="https://gitlab.com/api/v4/projects/278964/repository/archive.tar.gz?sha=${GITLAB_REF}&path=db/siphon/tables"
log "fetching $URL"
curl -sfL --retry 3 --retry-delay 2 -o "$ARCHIVE" "$URL"
gzip -t "$ARCHIVE" 2>/dev/null || { echo "downloaded archive is not gzip (bad ref?)"; exit 1; }
tar -xzf "$ARCHIVE" --strip-components=4 -C "$TABLES_RAW"

# --- 2. Filter to database: main --------------------------------------------
# Layout below only declares a `main` producer; siphon's helm generator hard-fails
# on any SSOT table whose `database:` is not in the layout.
SKIPPED=0
KEPT=0
for f in "$TABLES_RAW"/*.yml "$TABLES_RAW"/*.yaml; do
  [[ -f "$f" ]] || continue
  db="$(yq -r '.database // "main"' "$f")"
  if [[ "$db" == "main" ]]; then
    cp "$f" "$TABLES/"
    KEPT=$((KEPT+1))
  else
    SKIPPED=$((SKIPPED+1))
  fi
done
log "tables kept (main): $KEPT, skipped (other dbs): $SKIPPED"
[[ "$KEPT" -gt 0 ]] || { echo "no main-database tables found in SSOT"; exit 1; }

# --- 3. Generate fragments via siphon schema binary --------------------------
RAW="$TMP/raw.yaml"
docker run --rm \
  -v "$TABLES:/tables:ro" \
  -v "$LAYOUT:/layout.yaml:ro" \
  "$SIPHON_IMAGE" \
  /app/schema generate-values --tables-dir /tables --layout /layout.yaml \
  > "$RAW"

# --- 4. Split per-section into addressable YAML files ------------------------
# Generator output is a single stream with `# Producer: <id>` and `# Consumer: <id>`
# headers separating sections. With one producer + one consumer in our layout
# the split is trivial; reconciler section (if any) is dropped (no reconciler
# deployment in e2e).
awk -v prod="$OUT_PRODUCER.tmp" -v cons="$OUT_CONSUMER.tmp" '
  /^# Producer:/   { section="producer"; next }
  /^# Consumer:/   { section="consumer"; next }
  /^# Reconciler/  { section="skip"; next }
  section=="producer" { print > prod }
  section=="consumer" { print > cons }
' "$RAW"

[[ -s "$OUT_PRODUCER.tmp" ]] || { echo "producer fragment empty"; exit 1; }
[[ -s "$OUT_CONSUMER.tmp" ]] || { echo "consumer fragment empty"; exit 1; }

# Header for human readers; not consumed by helmfile.
HEADER="# GENERATED by scripts/sync-cdc-tables.sh — do not edit by hand.
# Source: gitlab-org/gitlab @ ${GITLAB_REF} (db/siphon/tables/), filtered to database: main.
# Regenerate after bumping gitlab.ref or siphon.image.tag in versions.yaml.
"
{ echo "$HEADER"; cat "$OUT_PRODUCER.tmp"; } > "$OUT_PRODUCER"
{ echo "$HEADER"; cat "$OUT_CONSUMER.tmp"; } > "$OUT_CONSUMER"
rm -f "$OUT_PRODUCER.tmp" "$OUT_CONSUMER.tmp"

log "wrote $OUT_PRODUCER"
log "wrote $OUT_CONSUMER"
