use std::time::Duration;

use tonic::{Code, Status};

/// Status-message prefix Workhorse puts on every status it generates itself.
/// A status without it is Gitaly's own answer or a transport failure.
pub const PROXY_STATUS_PREFIX: &str = "proxy: ";

pub const REASON_SESSION_EXPIRED: &str = "session_expired";
pub const REASON_SHUTTING_DOWN: &str = "shutting_down";
pub const REASON_STREAM_DEADLINE: &str = "stream_deadline";

#[derive(Debug, thiserror::Error)]
pub enum GitalyProxyError {
    #[error("gitaly proxy: unauthorized (401) — check JWT secret")]
    Unauthorized,

    #[error("gitaly proxy: forbidden (403) for project {project_id}")]
    Forbidden { project_id: i64 },

    /// 404: project unknown, proxy disabled, or the consumer policy does not
    /// cover this project. The server collapses all three so the client
    /// cannot tell them apart; callers with a non-proxy path fall back.
    #[error("gitaly proxy: not available for project {project_id} (404)")]
    NotAvailable { project_id: i64 },

    /// 429 (Rails preauth rate limit) or 503 (Workhorse at capacity or
    /// shutting down). Back off per `retry_after` before dialing again.
    #[error("gitaly proxy: busy (status {status}), retry after {retry_after:?}")]
    Busy {
        status: u16,
        retry_after: Option<Duration>,
    },

    /// 502: Rails answered but Workhorse could not use the preauth payload
    /// (version skew). Not a client problem; do not retry in a tight loop.
    #[error("gitaly proxy: bad gateway (502) — Rails/Workhorse version skew")]
    BadGateway,

    #[error("gitaly proxy: unexpected handshake status {status}")]
    UnexpectedStatus { status: u16 },

    #[error("gitaly proxy: unsupported session profile {profile:?}")]
    UnsupportedProfile { profile: String },

    #[error("gitaly proxy: malformed 101 header {header}: {reason}")]
    MalformedSessionHeader {
        header: &'static str,
        reason: String,
    },

    #[error("gitaly proxy: handshake failed: {0}")]
    Handshake(String),

    #[error("gitaly proxy: invalid base_url: {0}")]
    InvalidBaseUrl(String),

    #[error("gitaly proxy: JWT signing failed: {0}")]
    JwtSigning(String),

    #[error("gitaly proxy: transport: {0}")]
    Transport(#[from] tonic::transport::Error),

    /// `PERMISSION_DENIED proxy: *` — the RPC violated the session policy or
    /// profile. A configuration drift, never transient.
    #[error("gitaly proxy: policy denied the RPC: proxy: {reason}")]
    PolicyDenied { reason: String },

    /// `DEADLINE_EXCEEDED proxy: stream_deadline` — the RPC hit the server's
    /// hard per-stream cap. Retrying would burn the same Gitaly time again.
    #[error("gitaly proxy: RPC exceeded the server's per-stream deadline")]
    StreamDeadline,

    /// The RPC was rejected as stale (`session_expired` / `shutting_down`)
    /// on a fresh channel too, so the one permitted retry has been spent.
    #[error("gitaly proxy: session stale after one retry: {0}")]
    StaleAfterRetry(Status),

    /// Every other gRPC status, including Gitaly's own.
    #[error("gitaly proxy: RPC failed: {0}")]
    Rpc(Status),
}

/// How a client must react to a gRPC status coming back through the tunnel.
///
/// Classification is on the `proxy:` prefix first and the code second, so an
/// unknown `proxy:` reason falls into the class its code implies.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StatusClass {
    /// The session is draining; nothing reached Gitaly. Rotate and retry once.
    StaleSession,
    /// `PERMISSION_DENIED proxy: *`. Not transient.
    PolicyDenied,
    /// `DEADLINE_EXCEEDED proxy: stream_deadline`. Never retry.
    StreamDeadline,
    /// Any other `proxy:` status (e.g. `proxy: peek first frame`).
    OtherProxy,
    /// No `proxy:` prefix: Gitaly's own status or a transport failure.
    Passthrough,
}

/// Returns the reason code when `status` was generated by the proxy itself.
pub fn proxy_reason(status: &Status) -> Option<&str> {
    status.message().strip_prefix(PROXY_STATUS_PREFIX)
}

pub fn classify_status(status: &Status) -> StatusClass {
    let Some(reason) = proxy_reason(status) else {
        return StatusClass::Passthrough;
    };
    match status.code() {
        Code::Unauthenticated | Code::Unavailable => StatusClass::StaleSession,
        Code::PermissionDenied => StatusClass::PolicyDenied,
        Code::DeadlineExceeded if reason == REASON_STREAM_DEADLINE => StatusClass::StreamDeadline,
        _ => StatusClass::OtherProxy,
    }
}

impl From<Status> for GitalyProxyError {
    fn from(status: Status) -> Self {
        match classify_status(&status) {
            StatusClass::PolicyDenied => Self::PolicyDenied {
                reason: proxy_reason(&status).unwrap_or_default().to_owned(),
            },
            StatusClass::StreamDeadline => Self::StreamDeadline,
            StatusClass::StaleSession | StatusClass::OtherProxy | StatusClass::Passthrough => {
                Self::Rpc(status)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn classifies_on_prefix_first_then_code() {
        let cases = [
            (
                Status::unauthenticated("proxy: session_expired"),
                StatusClass::StaleSession,
            ),
            (
                Status::unavailable("proxy: shutting_down"),
                StatusClass::StaleSession,
            ),
            (
                Status::unauthenticated("proxy: some_future_reason"),
                StatusClass::StaleSession,
            ),
            (
                Status::permission_denied("proxy: method_not_allowed"),
                StatusClass::PolicyDenied,
            ),
            (
                Status::deadline_exceeded("proxy: stream_deadline"),
                StatusClass::StreamDeadline,
            ),
            (
                Status::internal("proxy: peek first frame: boom"),
                StatusClass::OtherProxy,
            ),
            (
                Status::unavailable("connection reset"),
                StatusClass::Passthrough,
            ),
            (
                Status::deadline_exceeded("Deadline expired"),
                StatusClass::Passthrough,
            ),
            (
                Status::not_found("proxy:no space"),
                StatusClass::Passthrough,
            ),
        ];
        for (status, expected) in cases {
            assert_eq!(classify_status(&status), expected, "{status:?}");
        }
    }

    #[test]
    fn converts_policy_and_deadline_statuses_to_typed_errors() {
        let denied = GitalyProxyError::from(Status::permission_denied("proxy: repo_scope"));
        assert!(
            matches!(denied, GitalyProxyError::PolicyDenied { reason } if reason == "repo_scope")
        );

        let deadline = GitalyProxyError::from(Status::deadline_exceeded("proxy: stream_deadline"));
        assert!(matches!(deadline, GitalyProxyError::StreamDeadline));

        let gitaly = GitalyProxyError::from(Status::not_found("repository not found"));
        assert!(matches!(gitaly, GitalyProxyError::Rpc(s) if s.code() == Code::NotFound));
    }
}
