image: registry.gitlab.com/gitlab-org/orbit/build-images/rust-builder:latest

setup_script:
  - apt-get update && apt-get install -y --no-install-recommends npm
  - mise trust
  - mise install

cache:
  key:
    files:
      - Cargo.lock
    prefix: duo-agent
  paths:
    - target/

network_policy:
  include_recommended_allowed: true
  allow_all_unix_sockets: true
