include:
  - component: ${CI_SERVER_FQDN}/gitlab-org/components/danger-review/danger-review@1.2.0
    rules:
      - if: $CI_SERVER_HOST == "gitlab.com"
    inputs:
      job_image: "ruby:3.2.5"

rspec:
  stage: test
  image: ruby:3.2.5
  script:
  - bundle config set path vendor/bundle
  - bundle install
  - bundle exec rspec -fd
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"'


qa-igluctl-lint:
  image: openjdk:26-ea-slim
  stage: test
  cache:
    key: igluctl-0.7.2
    paths:
      - igluctl
  script:
  - echo 'Linting schemas'
  - apt-get update && apt-get install -y curl
  - |
    if [ ! -f igluctl ]; then
      echo 'Downloading igluctl...'
      curl -fSL -o igluctl https://github.com/snowplow/igluctl/releases/download/0.7.2/igluctl
      chmod +x igluctl
    else
      echo 'Using cached igluctl'
    fi
  # exclude invalid gitlab_experiment schemas
  - rm public/schemas/com.gitlab/gitlab_experiment/jsonschema/0-2-0
  - rm public/schemas/com.gitlab/gitlab_experiment/jsonschema/0-3-0
  - ./igluctl lint public/schemas
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"'

pages:
  stage: deploy
  script:
  - echo 'Deploying the Iglu Registry using Gitlab Pages'
  artifacts:
    paths:
    - public
  only:
  - master
