FROM --platform=linux/amd64 debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*

COPY gkg-server /usr/local/bin/gkg-server

ENTRYPOINT ["gkg-server"]
