apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor/iglu
    contents:
      - path: .
        git:
          url: https://gitlab.com/gitlab-org/iglu.git
          ref: master
        includePaths:
          - public/schemas/com.gitlab/orbit_*/**
