use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use ontology::Ontology;

fn load_ontology(path: Option<&PathBuf>) -> Result<Ontology> {
    match path {
        Some(p) => Ontology::load_from_dir(p).context("failed to load ontology"),
        None => Ontology::load_embedded().context("failed to load embedded ontology"),
    }
}

/// Reference DDL emitted to `config/graph.sql` always assumes a local `default`
/// ClickHouse user; the indexer substitutes the deployment's configured
/// credentials at migration time.
fn local_dictionary_source() -> query_engine::compiler::DictionarySource<'static> {
    query_engine::compiler::DictionarySource {
        database: "default",
        user: "default",
        password: None,
    }
}

pub fn run_remote(
    ontology_path: Option<PathBuf>,
    prefix: String,
    diff: Option<PathBuf>,
) -> Result<()> {
    let ont = load_ontology(ontology_path.as_ref())?;

    let tables = query_engine::compiler::generate_graph_tables(&ont);
    let mut generated: Vec<String> = tables
        .iter()
        .map(|t| {
            let t = if prefix.is_empty() {
                t.clone()
            } else {
                t.clone().with_prefix(&prefix)
            };
            format!("{};\n", query_engine::compiler::emit_create_table(&t))
        })
        .collect();

    let dicts = query_engine::compiler::generate_graph_dictionaries(&ont);
    generated.extend(dicts.iter().map(|d| {
        let d = if prefix.is_empty() {
            d.clone()
        } else {
            d.clone().with_prefix(&prefix)
        };
        format!(
            "{};\n",
            query_engine::compiler::emit_create_dictionary(&d, &local_dictionary_source())
        )
    }));

    let views = if prefix.is_empty() {
        query_engine::compiler::generate_graph_materialized_views(&ont)
    } else {
        query_engine::compiler::generate_graph_materialized_views_with_prefix(&ont, &prefix)
    };
    for mv in &views {
        generated.push(format!(
            "{};\n",
            query_engine::compiler::emit_create_materialized_view(mv)
        ));
    }

    let schema_version = include_str!(concat!(env!("CONFIG_DIR"), "/SCHEMA_VERSION")).trim();

    match diff {
        Some(path) => run_schema_diff(&generated, &path),
        None => {
            println!("-- SCHEMA_VERSION={schema_version} [AUTOGENERATED — DO NOT EDIT MANUALLY]");
            println!("-- Regenerate with: mise schema:generate:ddl");
            println!();
            for stmt in &generated {
                println!("{stmt}");
            }
            Ok(())
        }
    }
}

/// Manifest table DDL for DuckDB. Passed through to the compiler as
/// external DDL so the codegen crate stays schema-agnostic.
const MANIFEST_DDL: &str = "\
CREATE TYPE IF NOT EXISTS repo_status AS ENUM ('pending', 'indexing', 'indexed', 'error');

CREATE TABLE IF NOT EXISTS _orbit_manifest (
    repo_path VARCHAR PRIMARY KEY,
    project_id BIGINT NOT NULL,
    parent_repo_path VARCHAR,
    branch VARCHAR,
    commit_sha VARCHAR,
    status repo_status NOT NULL DEFAULT 'pending',
    last_indexed_at TIMESTAMP,
    error_message VARCHAR
);";

pub fn run_local(ontology_path: Option<PathBuf>) -> Result<()> {
    let ont = load_ontology(ontology_path.as_ref())?;
    print!(
        "{}",
        query_engine::compiler::generate_local_ddl(&ont, MANIFEST_DDL)
    );
    Ok(())
}

/// Full `config/graph_unversioned.sql` skeleton with one hole filled at
/// generation time: `__ATTRIBUTION_SELECT__` (the refreshable MV body). The
/// `__ACTIVE_PREFIX__`/`__ACTIVE_VERSION__` placeholders are left in the output
/// and resolved by the indexer at apply time.
const UNVERSIONED_FILE_TEMPLATE: &str = include_str!("graph_unversioned.sql.tpl");

/// Per-table attribution branch. `__LOGICAL__` is replaced with the unprefixed
/// logical table name; physical table references carry the `__ACTIVE_PREFIX__`
/// placeholder the applier resolves to the active version's prefix.
const ATTRIBUTION_BRANCH_TEMPLATE: &str =
    include_str!("namespace_storage_attribution_branch.sql.tpl");

/// The `__global` branch up to the per-table predicate; the global table names
/// are appended as an `IN` list, then closed with `GROUP BY table`. Global
/// tables carry no `traversal_path`, so they are booked whole under `__global`
/// rather than attributed per namespace.
const GLOBAL_BRANCH_HEADER: &str = r"SELECT
    today() AS snapshot_date,
    __ACTIVE_VERSION__ AS schema_version,
    replaceRegexpOne(table, '^v\d+_', '') AS logical_table,
    '__global' AS top_level_namespace,
    sum(data_compressed_bytes) AS compressed_bytes
FROM system.parts
WHERE database = currentDatabase() AND active
  AND table IN (";

/// Generates `config/graph_unversioned.sql`: the idempotent DDL for the
/// namespace-storage snapshot table and its refreshable MV. Physical table
/// references in the MV carry `__ACTIVE_PREFIX__`/`__ACTIVE_VERSION__`
/// placeholders that the indexer resolves to the active schema version at apply
/// time.
pub fn run_unversioned(ontology_path: Option<PathBuf>) -> Result<()> {
    let ont = load_ontology(ontology_path.as_ref())?;
    print!("{}", render_unversioned_file(&ont));
    Ok(())
}

fn render_unversioned_file(ontology: &Ontology) -> String {
    UNVERSIONED_FILE_TEMPLATE.replace(
        "__ATTRIBUTION_SELECT__",
        &render_attribution_select(ontology),
    )
}

/// Attribution branches (one per namespace-attributable table) plus the
/// `__global` branch, joined by `UNION ALL`.
fn render_attribution_select(ontology: &Ontology) -> String {
    let mut branches: Vec<String> = list_namespace_attributable_tables(ontology)
        .iter()
        .map(|table| ATTRIBUTION_BRANCH_TEMPLATE.replace("__LOGICAL__", table))
        .collect();
    branches.push(render_global_tables_branch(&list_global_tables(ontology)));
    branches.join("\nUNION ALL\n")
}

fn render_global_tables_branch(global_tables: &[String]) -> String {
    let table_list = global_tables
        .iter()
        .map(|table| format!("'__ACTIVE_PREFIX__{table}'"))
        .collect::<Vec<_>>()
        .join(", ");
    format!("{GLOBAL_BRANCH_HEADER}{table_list})\nGROUP BY table")
}

/// Non-global node tables plus the physical edge tables — every table carrying
/// a `traversal_path` that can be attributed to a top-level namespace.
fn list_namespace_attributable_tables(ontology: &Ontology) -> Vec<String> {
    let mut tables: BTreeSet<String> = ontology
        .nodes()
        .filter(|node| !node.global)
        .map(|node| node.destination_table.clone())
        .collect();
    tables.extend(ontology.edge_tables().iter().map(|table| table.to_string()));
    tables.into_iter().collect()
}

fn list_global_tables(ontology: &Ontology) -> Vec<String> {
    let mut tables: Vec<String> = ontology
        .global_tables()
        .iter()
        .map(|table| table.to_string())
        .collect();
    tables.sort();
    tables
}

fn run_schema_diff(generated_stmts: &[String], sql_path: &Path) -> Result<()> {
    let existing_sql = std::fs::read_to_string(sql_path)
        .with_context(|| format!("failed to read {}", sql_path.display()))?;

    let existing = extract_tables_from_sql(&existing_sql);
    let generated_sql = generated_stmts.join("\n");
    let generated = extract_tables_from_sql(&generated_sql);

    let all_names: BTreeSet<&str> = existing
        .keys()
        .chain(generated.keys())
        .map(|s| s.as_str())
        .collect();

    let mut ok = 0u32;
    let mut diffs = 0u32;
    let mut missing = 0u32;
    let mut extra = 0u32;

    for name in &all_names {
        if *name == "gkg_schema_version" {
            continue;
        }

        match (existing.get(*name), generated.get(*name)) {
            (Some(_), None) => {
                eprintln!("MISSING from generated: {name}");
                missing += 1;
            }
            (None, Some(_)) => {
                eprintln!("EXTRA in generated: {name}");
                extra += 1;
            }
            (Some(exp), Some(got)) => {
                if exp.trim() == got.trim() {
                    ok += 1;
                } else {
                    diffs += 1;
                    eprintln!("DIFF: {name}");
                    let exp_lines: Vec<&str> = exp.lines().collect();
                    let got_lines: Vec<&str> = got.lines().collect();
                    let max = exp_lines.len().max(got_lines.len());
                    for i in 0..max {
                        let e = exp_lines.get(i).map(|s| s.trim()).unwrap_or("<missing>");
                        let g = got_lines.get(i).map(|s| s.trim()).unwrap_or("<missing>");
                        if e != g {
                            eprintln!("  L{i}: exp: {e}");
                            eprintln!("  L{i}: got: {g}");
                        }
                    }
                }
            }
            (None, None) => unreachable!(),
        }
    }

    eprintln!();
    eprintln!("{ok} OK, {diffs} DIFF, {missing} MISSING, {extra} EXTRA");

    if diffs > 0 || missing > 0 || extra > 0 {
        anyhow::bail!("DDL mismatch: {diffs} tables differ, {missing} missing, {extra} extra");
    }

    eprintln!("All tables match.");
    Ok(())
}

fn extract_tables_from_sql(sql: &str) -> BTreeMap<String, String> {
    let mut tables = BTreeMap::new();
    let mut depth = 0i32;
    let mut in_string = false;
    let mut start = 0;

    for (i, c) in sql.char_indices() {
        match c {
            '\'' if !in_string || (i > 0 && sql.as_bytes()[i - 1] != b'\\') => {
                in_string = !in_string;
            }
            '(' if !in_string => depth += 1,
            ')' if !in_string => depth -= 1,
            ';' if !in_string && depth == 0 => {
                let stmt = sql[start..=i].trim();
                if let Some(name) =
                    extract_ddl_object_name(stmt).or_else(|| extract_create_dictionary_name(stmt))
                {
                    tables.insert(name, strip_leading_comments(stmt).to_string());
                }
                start = i + 1;
            }
            _ => {}
        }
    }

    tables
}

fn strip_leading_comments(stmt: &str) -> &str {
    let mut start = 0;
    for line in stmt.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with("--") {
            start += line.len() + 1;
        } else {
            break;
        }
    }
    if start >= stmt.len() {
        stmt
    } else {
        &stmt[start..]
    }
}

fn extract_ddl_object_name(stmt: &str) -> Option<String> {
    let upper = stmt.to_uppercase();
    let markers = [
        "CREATE MATERIALIZED VIEW IF NOT EXISTS ",
        "CREATE TABLE IF NOT EXISTS ",
    ];
    for marker in markers {
        if let Some(pos) = upper.find(marker) {
            let after = &stmt[pos + marker.len()..];
            let name = after
                .split(|c: char| c.is_whitespace() || c == '(')
                .next()?;
            if !name.is_empty() {
                return Some(name.to_string());
            }
        }
    }
    None
}

fn extract_create_dictionary_name(stmt: &str) -> Option<String> {
    let upper = stmt.to_uppercase();
    let marker = "CREATE DICTIONARY IF NOT EXISTS ";
    let pos = upper.find(marker)?;
    let after = &stmt[pos + marker.len()..];
    let name = after
        .split(|c: char| c.is_whitespace() || c == '(')
        .next()?;
    if name.is_empty() {
        None
    } else {
        Some(name.to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn remote_ddl_contains_create_table() {
        let ont = ontology::Ontology::load_embedded().unwrap();
        let tables = query_engine::compiler::generate_graph_tables(&ont);
        assert!(!tables.is_empty());
        let sql = query_engine::compiler::emit_create_table(&tables[0]);
        assert!(sql.contains("CREATE TABLE"));
    }

    #[test]
    fn local_ddl_contains_create_table_and_manifest() {
        let ont = ontology::Ontology::load_embedded().unwrap();
        let ddl = query_engine::compiler::generate_local_ddl(&ont, MANIFEST_DDL);
        assert!(ddl.contains("CREATE TABLE"));
        assert!(ddl.contains("_orbit_manifest"));
        assert!(ddl.contains("SCHEMA_VERSION="));
    }

    #[test]
    fn extract_tables_from_sql_parses_create_table() {
        let sql = "CREATE TABLE IF NOT EXISTS foo (id BIGINT);\n\
                   CREATE TABLE IF NOT EXISTS bar (name VARCHAR);";
        let tables = extract_tables_from_sql(sql);
        assert_eq!(tables.len(), 2);
        assert!(tables.contains_key("foo"));
        assert!(tables.contains_key("bar"));
    }

    #[test]
    fn extract_tables_from_sql_parses_dictionary() {
        let sql = "CREATE DICTIONARY IF NOT EXISTS my_dict (id UInt64) PRIMARY KEY id;";
        let tables = extract_tables_from_sql(sql);
        assert!(tables.contains_key("my_dict"));
    }

    #[test]
    fn strip_leading_comments_removes_header() {
        let stmt = "-- comment\n-- another\nCREATE TABLE foo;";
        assert_eq!(strip_leading_comments(stmt), "CREATE TABLE foo;");
    }

    fn unversioned_ontology() -> Ontology {
        Ontology::load_embedded().unwrap()
    }

    #[test]
    fn attribution_select_has_one_branch_per_attributable_table() {
        let ont = unversioned_ontology();
        let select = render_attribution_select(&ont);
        for table in list_namespace_attributable_tables(&ont) {
            assert!(
                select.contains(&format!("'{table}' AS logical_table")),
                "missing attribution branch for {table}"
            );
        }
    }

    #[test]
    fn global_branch_covers_every_global_table() {
        let ont = unversioned_ontology();
        let select = render_attribution_select(&ont);
        let global_branch_at = select
            .find("'__global' AS top_level_namespace")
            .expect("global branch");
        for table in list_global_tables(&ont) {
            assert!(
                select[global_branch_at..].contains(&format!("'__ACTIVE_PREFIX__{table}'")),
                "global table {table} missing from __global branch"
            );
        }
    }

    #[test]
    fn generated_file_resolves_generation_time_placeholders() {
        let file = render_unversioned_file(&unversioned_ontology());
        for placeholder in ["__LOGICAL__", "__ATTRIBUTION_SELECT__"] {
            assert!(
                !file.contains(placeholder),
                "unresolved generation-time placeholder {placeholder} in generated file"
            );
        }
    }

    #[test]
    fn generated_file_keeps_apply_time_placeholders_for_the_mv() {
        let file = render_unversioned_file(&unversioned_ontology());
        assert!(
            file.contains(
                "CREATE MATERIALIZED VIEW __ACTIVE_PREFIX__namespace_storage_snapshot_refresh"
            ),
            "MV name must carry the __ACTIVE_PREFIX__ placeholder"
        );
        assert!(
            file.contains(
                "DROP VIEW IF EXISTS __ACTIVE_PREFIX__namespace_storage_snapshot_refresh"
            ),
            "MV drop must carry the __ACTIVE_PREFIX__ placeholder"
        );
        assert!(
            file.contains("__ACTIVE_VERSION__ AS schema_version"),
            "schema_version column must use the __ACTIVE_VERSION__ placeholder"
        );
    }

    #[test]
    fn generated_mv_body_has_no_analyzer_workaround_or_version_subquery() {
        let file = render_unversioned_file(&unversioned_ontology());
        assert!(
            !file.contains("enable_analyzer"),
            "enable_analyzer setting must be gone once names are prefixed literally"
        );
        assert!(
            !file.contains("gkg_schema_version"),
            "no scalar subquery on gkg_schema_version should remain"
        );
    }

    #[test]
    fn generated_file_has_no_hardcoded_gkg_database() {
        let file = render_unversioned_file(&unversioned_ontology());
        assert!(!file.contains("'gkg'"), "quoted 'gkg' database in file");
        assert!(!file.contains("gkg."), "qualified gkg. database in file");
    }

    #[test]
    fn generated_file_orders_the_two_objects() {
        let file = render_unversioned_file(&unversioned_ontology());
        let markers = [
            "CREATE TABLE IF NOT EXISTS namespace_storage_snapshot",
            "DROP VIEW IF EXISTS __ACTIVE_PREFIX__namespace_storage_snapshot_refresh",
            "CREATE MATERIALIZED VIEW __ACTIVE_PREFIX__namespace_storage_snapshot_refresh",
        ];
        let mut previous = 0;
        for marker in markers {
            let at = file
                .find(marker)
                .unwrap_or_else(|| panic!("missing statement: {marker}"));
            assert!(at >= previous, "statement out of order: {marker}");
            previous = at;
        }
    }
}
