use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use ontology::Ontology;
use orbit_migrations::schema::{DictionaryCredentials, GraphSchema};

fn load_ontology(path: Option<&PathBuf>) -> Result<Ontology> {
    match path {
        Some(path) => Ontology::load_from_dir(path).context("failed to load ontology"),
        None => Ontology::load_embedded().context("failed to load embedded ontology"),
    }
}

fn local_dictionary_credentials() -> DictionaryCredentials {
    DictionaryCredentials {
        database: "default".into(),
        user: "default".into(),
        password: None,
    }
}

pub fn run_remote(
    ontology_path: Option<PathBuf>,
    prefix: String,
    diff: Option<PathBuf>,
) -> Result<()> {
    let ontology = load_ontology(ontology_path.as_ref())?;
    let schema = GraphSchema::from_ontology(&ontology);
    let credentials = local_dictionary_credentials();

    let mut generated: Vec<String> = schema
        .tables
        .iter()
        .map(|table| format!("{};\n", table.to_create_sql(&prefix)))
        .collect();

    for dictionary in &schema.dictionaries {
        let prefixed = dictionary.clone().with_schema_version_prefix(&prefix);
        generated.push(format!("{};\n", prefixed.to_create_sql(&credentials)));
    }

    let all_table_names: Vec<String> = schema
        .tables
        .iter()
        .map(|table| table.name.clone())
        .collect();
    for view in schema.views.iter().filter(|view| view.versioned) {
        let prefixed = view
            .clone()
            .with_schema_version_prefix(&prefix, &all_table_names);
        generated.push(format!("{};\n", prefixed.to_create_sql()));
    }

    let schema_version = orbit_versions::VERSIONS.schema;

    match diff {
        Some(path) => run_schema_diff(&generated, &path),
        None => {
            println!("-- SCHEMA_VERSION={schema_version} [AUTOGENERATED — DO NOT EDIT MANUALLY]");
            println!("-- Regenerate with: mise schema:generate:ddl");
            println!();
            for stmt in &generated {
                println!("{stmt}");
            }
            Ok(())
        }
    }
}

/// Manifest and search-index DDL for DuckDB. Passed through to the compiler
/// as external DDL so the codegen crate stays schema-agnostic. The doc
/// macros are the single definition of search-document text: the indexer
/// derives a per-project gl_def_doc_<pid> table from gl_definition with them
/// and builds the FTS index over it, so write and read sides cannot drift and
/// BM25 statistics stay scoped to one project.
const MANIFEST_DDL: &str = "\
CREATE TYPE IF NOT EXISTS repo_status AS ENUM ('pending', 'indexing', 'indexed', 'error');

CREATE TABLE IF NOT EXISTS _orbit_manifest (
    repo_path VARCHAR PRIMARY KEY,
    project_id BIGINT NOT NULL,
    parent_repo_path VARCHAR,
    branch VARCHAR,
    commit_sha VARCHAR,
    status repo_status NOT NULL DEFAULT 'pending',
    last_indexed_at TIMESTAMP,
    error_message VARCHAR
);

CREATE TABLE IF NOT EXISTS _orbit_meta (
    key VARCHAR PRIMARY KEY,
    value VARCHAR NOT NULL
);

CREATE OR REPLACE MACRO def_name(fqn) AS
    regexp_replace(fqn, '^.*[:.#/]', '');

CREATE OR REPLACE MACRO camel_split(txt) AS
    regexp_replace(regexp_replace(txt, '([A-Z]+)([A-Z][a-z])', '\\1 \\2', 'g'),
                   '([a-z0-9])([A-Z])', '\\1 \\2', 'g');

CREATE OR REPLACE MACRO fts_doc(txt) AS
    CASE WHEN camel_split(txt) = txt THEN txt
         ELSE txt || ' ' || camel_split(txt) END;";

pub fn run_local(ontology_path: Option<PathBuf>) -> Result<()> {
    let ontology = load_ontology(ontology_path.as_ref())?;
    print!(
        "{}",
        query_engine::compiler::generate_local_ddl(&ontology, MANIFEST_DDL)
    );
    Ok(())
}

pub fn run_persistent(ontology_path: Option<PathBuf>, diff: Option<PathBuf>) -> Result<()> {
    let ontology = load_ontology(ontology_path.as_ref())?;
    let schema = GraphSchema::from_ontology(&ontology);

    let generated: Vec<String> = schema
        .unversioned_definitions
        .iter()
        .map(|definition| format!("{};\n", definition.create_statement))
        .collect();

    let schema_version = orbit_versions::VERSIONS.schema;

    match diff {
        Some(path) => run_schema_diff(&generated, &path),
        None => {
            println!("-- SCHEMA_VERSION={schema_version} [AUTOGENERATED — DO NOT EDIT MANUALLY]");
            println!("-- Regenerate with: mise schema:generate:ddl");
            println!(
                "-- Persistent objects: created once at boot, never version-prefixed or GCed."
            );
            println!();
            for stmt in &generated {
                println!("{stmt}");
            }
            Ok(())
        }
    }
}

fn run_schema_diff(generated_stmts: &[String], sql_path: &Path) -> Result<()> {
    let existing_sql = std::fs::read_to_string(sql_path)
        .with_context(|| format!("failed to read {}", sql_path.display()))?;

    let existing = extract_tables_from_sql(&existing_sql);
    let generated_sql = generated_stmts.join("\n");
    let generated = extract_tables_from_sql(&generated_sql);

    let all_names: BTreeSet<&str> = existing
        .keys()
        .chain(generated.keys())
        .map(|s| s.as_str())
        .collect();

    let mut ok = 0u32;
    let mut diffs = 0u32;
    let mut missing = 0u32;
    let mut extra = 0u32;

    for name in &all_names {
        if *name == "gkg_schema_version" {
            continue;
        }

        match (existing.get(*name), generated.get(*name)) {
            (Some(_), None) => {
                eprintln!("MISSING from generated: {name}");
                missing += 1;
            }
            (None, Some(_)) => {
                eprintln!("EXTRA in generated: {name}");
                extra += 1;
            }
            (Some(exp), Some(got)) => {
                if exp.trim() == got.trim() {
                    ok += 1;
                } else {
                    diffs += 1;
                    eprintln!("DIFF: {name}");
                    let exp_lines: Vec<&str> = exp.lines().collect();
                    let got_lines: Vec<&str> = got.lines().collect();
                    let max = exp_lines.len().max(got_lines.len());
                    for i in 0..max {
                        let e = exp_lines.get(i).map(|s| s.trim()).unwrap_or("<missing>");
                        let g = got_lines.get(i).map(|s| s.trim()).unwrap_or("<missing>");
                        if e != g {
                            eprintln!("  L{i}: exp: {e}");
                            eprintln!("  L{i}: got: {g}");
                        }
                    }
                }
            }
            (None, None) => unreachable!(),
        }
    }

    eprintln!();
    eprintln!("{ok} OK, {diffs} DIFF, {missing} MISSING, {extra} EXTRA");

    if diffs > 0 || missing > 0 || extra > 0 {
        anyhow::bail!("DDL mismatch: {diffs} tables differ, {missing} missing, {extra} extra");
    }

    eprintln!("All tables match.");
    Ok(())
}

fn extract_tables_from_sql(sql: &str) -> BTreeMap<String, String> {
    let mut tables = BTreeMap::new();
    let mut depth = 0i32;
    let mut in_string = false;
    let mut start = 0;

    for (i, c) in sql.char_indices() {
        match c {
            '\'' if !in_string || (i > 0 && sql.as_bytes()[i - 1] != b'\\') => {
                in_string = !in_string;
            }
            '(' if !in_string => depth += 1,
            ')' if !in_string => depth -= 1,
            ';' if !in_string && depth == 0 => {
                let stmt = sql[start..=i].trim();
                if let Some(name) =
                    extract_ddl_object_name(stmt).or_else(|| extract_create_dictionary_name(stmt))
                {
                    tables.insert(name, strip_leading_comments(stmt).to_string());
                }
                start = i + 1;
            }
            _ => {}
        }
    }

    tables
}

fn strip_leading_comments(stmt: &str) -> &str {
    let mut start = 0;
    for line in stmt.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with("--") {
            start += line.len() + 1;
        } else {
            break;
        }
    }
    if start >= stmt.len() {
        stmt
    } else {
        &stmt[start..]
    }
}

fn extract_ddl_object_name(stmt: &str) -> Option<String> {
    let upper = stmt.to_uppercase();
    let markers = [
        "CREATE MATERIALIZED VIEW IF NOT EXISTS ",
        "CREATE TABLE IF NOT EXISTS ",
    ];
    for marker in markers {
        if let Some(pos) = upper.find(marker) {
            let after = &stmt[pos + marker.len()..];
            let name = after
                .split(|c: char| c.is_whitespace() || c == '(')
                .next()?;
            if !name.is_empty() {
                return Some(name.to_string());
            }
        }
    }
    None
}

fn extract_create_dictionary_name(stmt: &str) -> Option<String> {
    let upper = stmt.to_uppercase();
    let marker = "CREATE DICTIONARY IF NOT EXISTS ";
    let pos = upper.find(marker)?;
    let after = &stmt[pos + marker.len()..];
    let name = after
        .split(|c: char| c.is_whitespace() || c == '(')
        .next()?;
    if name.is_empty() {
        None
    } else {
        Some(name.to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn remote_ddl_contains_create_table() {
        let ontology = ontology::Ontology::load_embedded().unwrap();
        let schema = GraphSchema::from_ontology(&ontology);
        assert!(!schema.tables.is_empty());
        assert!(schema.tables[0].to_create_sql("").contains("CREATE TABLE"));
    }

    #[test]
    fn persistent_ddl_contains_unversioned_table_without_prefix() {
        let ontology = ontology::Ontology::load_embedded().unwrap();
        let schema = GraphSchema::from_ontology(&ontology);
        let table = schema
            .unversioned_definitions
            .iter()
            .find(|definition| definition.entity_type == "TABLE")
            .expect("an unversioned table should be generated");
        assert!(table.create_statement.contains("CREATE TABLE"));
        let schema_version = orbit_versions::VERSIONS.schema;
        assert!(
            !table
                .create_statement
                .contains(&format!(" v{schema_version}_"))
        );
    }

    #[test]
    fn local_ddl_contains_create_table_and_manifest() {
        let ontology = ontology::Ontology::load_embedded().unwrap();
        let ddl = query_engine::compiler::generate_local_ddl(&ontology, MANIFEST_DDL);
        assert!(ddl.contains("CREATE TABLE"));
        assert!(ddl.contains("_orbit_manifest"));
        assert!(ddl.contains("_orbit_meta"));
        assert!(ddl.contains("MACRO fts_doc"));
        assert!(ddl.contains("SCHEMA_VERSION="));
    }

    #[test]
    fn extract_tables_from_sql_parses_create_table() {
        let sql = "CREATE TABLE IF NOT EXISTS foo (id BIGINT);\n\
                   CREATE TABLE IF NOT EXISTS bar (name VARCHAR);";
        let tables = extract_tables_from_sql(sql);
        assert_eq!(tables.len(), 2);
        assert!(tables.contains_key("foo"));
        assert!(tables.contains_key("bar"));
    }

    #[test]
    fn extract_tables_from_sql_parses_dictionary() {
        let sql = "CREATE DICTIONARY IF NOT EXISTS my_dict (id UInt64) PRIMARY KEY id;";
        let tables = extract_tables_from_sql(sql);
        assert!(tables.contains_key("my_dict"));
    }

    #[test]
    fn strip_leading_comments_removes_header() {
        let stmt = "-- comment\n-- another\nCREATE TABLE foo;";
        assert_eq!(strip_leading_comments(stmt), "CREATE TABLE foo;");
    }
}
