-- [AUTOGENERATED — DO NOT EDIT MANUALLY] Regenerate with: mise schema:generate:ddl
-- Idempotent DDL for the namespace-storage objects.
--
-- The snapshot table is version-agnostic and survives schema migrations. The
-- refreshable MV is bound to one schema version's physical tables, so the
-- applier substitutes two placeholders at apply time:
--   __ACTIVE_PREFIX__   the active version's table prefix (empty at version 0,
--                       else v<N>_)
--   __ACTIVE_VERSION__  the active version number
--
-- Applied by the dispatcher at startup (only when the active schema version
-- equals the binary's embedded SCHEMA_VERSION) and again after a migration
-- promotes.

CREATE TABLE IF NOT EXISTS namespace_storage_snapshot (
    snapshot_date Date,
    schema_version Int64,
    logical_table String,
    top_level_namespace String,
    compressed_bytes Int64
)
ENGINE = ReplacingMergeTree
ORDER BY (logical_table, top_level_namespace, snapshot_date)
TTL snapshot_date + INTERVAL 400 DAY;

-- Refreshable materialized views are not CREATE-OR-REPLACE-able in ClickHouse,
-- so the previous definition is dropped before the new one is created.
DROP VIEW IF EXISTS __ACTIVE_PREFIX__namespace_storage_snapshot_refresh;

CREATE MATERIALIZED VIEW __ACTIVE_PREFIX__namespace_storage_snapshot_refresh
REFRESH EVERY 1 DAY OFFSET 2 HOUR
APPEND TO namespace_storage_snapshot
AS
__ATTRIBUTION_SELECT__;
