[package]
name = "orbit-migrations"
version.workspace = true
edition = "2024"
license = "LicenseRef-EE"

[dependencies]
arrow = { workspace = true }
async-nats = { workspace = true }
clickhouse-client = { workspace = true }
ontology = { path = "../ontology" }
orbit-versions = { path = "../orbit-versions" }
orbit-utils = { path = "../utils" }
regex = { workspace = true }
serde = { workspace = true }
serde-saphyr = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
