use std::path::{Path, PathBuf};

fn main() {
    #[cfg(target_os = "macos")]
    {
        println!("cargo:rustc-link-arg-bin=orbit=-Wl,-rpath,@loader_path/deps");
    }

    generate_skill_files();

    // Release jobs run on `vX.Y.Z` tags (.gitlab/ci/release-local.yml), so
    // CI_COMMIT_TAG is the authoritative release version. `git describe` is a
    // best-effort convenience for local/dev builds; the static Cargo.toml
    // version is the last-resort fallback (source-tarball builds with no git).
    let version = std::env::var("CI_COMMIT_TAG")
        .ok()
        .filter(|tag| !tag.is_empty())
        .or_else(|| {
            std::process::Command::new("git")
                // --match pins us to release tags: this repo also has
                // `clients/gkgpb/vX.Y.Z` tags, and a bare --tags would pick the
                // nearest of either namespace.
                .args([
                    "describe", "--tags", "--always", "--dirty", "--match", "v[0-9]*",
                ])
                .output()
                .ok()
                .filter(|out| out.status.success())
                .map(|out| String::from_utf8_lossy(&out.stdout).trim().to_string())
                .filter(|described| !described.is_empty())
        })
        .unwrap_or_else(|| env!("CARGO_PKG_VERSION").to_string());

    // Publish strips the leading `v` (scripts/upload-local-cli-release.sh uses
    // `${CI_COMMIT_TAG#v}`), so the package-registry version glab downloads and
    // compares against in `--update` is a bare semver. Match that here.
    let version = version.strip_prefix('v').unwrap_or(&version);

    println!("cargo:rustc-env=ORBIT_VERSION={version}");
    println!("cargo:rerun-if-env-changed=CI_COMMIT_TAG");
    // Rebuild when HEAD or refs move so dev builds don't report a stale tag.
    println!("cargo:rerun-if-changed=../../.git/HEAD");
    println!("cargo:rerun-if-changed=../../.git/refs");
}

/// Embeds `skills/orbit-local/` into the binary so `orbit skill [path]` serves a
/// version-matched copy regardless of install method. Deriving the file table
/// from the on-disk tree (rather than a hand-maintained list) means the manifest
/// `orbit skill` reports can never drift from what is actually embedded.
fn generate_skill_files() {
    let skills_dir =
        PathBuf::from(std::env::var("SKILLS_DIR").expect(
            "SKILLS_DIR must be set via .cargo/config.toml [env] when building orbit-local",
        ));
    let skill_root = skills_dir.join("orbit-local");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));

    let mut files = Vec::new();
    collect_files(&skill_root, &skill_root, &mut files);
    files.sort();
    assert!(
        files.iter().any(|(rel, _)| rel == "SKILL.md"),
        "skills/orbit-local must contain a SKILL.md manifest"
    );

    let mut emitted = String::from("// @generated by build.rs - do not edit\n\n");
    emitted.push_str("pub(crate) static SKILL_FILES: &[(&str, &str)] = &[\n");
    for (rel, abs) in &files {
        emitted.push_str(&format!(
            "    ({rel:?}, include_str!({abs:?})),\n",
            abs = abs.to_str().expect("skill path is valid UTF-8")
        ));
    }
    emitted.push_str("];\n");

    std::fs::write(out_dir.join("skill_files.rs"), emitted).expect("write skill_files.rs");
    println!("cargo:rerun-if-changed={}", skill_root.display());
}

fn collect_files(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let mut entries: Vec<_> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", dir.display()))
        .map(|e| e.expect("dir entry").path())
        .collect();
    entries.sort();
    for path in entries {
        if path.is_dir() {
            collect_files(root, &path, out);
        } else {
            let rel = path
                .strip_prefix(root)
                .expect("path under skill root")
                .to_str()
                .expect("skill relative path is valid UTF-8")
                .replace('\\', "/");
            let abs = std::fs::canonicalize(&path).unwrap_or(path);
            out.push((rel, abs));
            println!("cargo:rerun-if-changed={}", out.last().unwrap().1.display());
        }
    }
}
