[package]
name = "orbit-cli"
version.workspace = true
edition = "2024"
build = "build.rs"

[[bin]]
name = "orbit"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
mimalloc = { workspace = true }
arrow = { workspace = true, features = ["prettyprint"] }
code-graph = { path = "../code-graph" }
duckdb-client = { path = "../duckdb-client" }
labkit-events = { workspace = true }
orbit-analytics = { path = "../orbit-analytics" }
orbit-prompts = { path = "../orbit-prompts" }
orbit-utils = { path = "../utils" }
ontology = { path = "../ontology" }
gitalisk-core = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
dirs = { workspace = true }
dunce = { workspace = true }
reqwest = { workspace = true }
rmcp = { workspace = true }
rust-embed = { workspace = true }
rustls = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
rust-stemmers = { workspace = true }
serde_json = { workspace = true, features = ["raw_value"] }
strum = { workspace = true }

[build-dependencies]
orbit-prompts = { path = "../orbit-prompts" }

[dev-dependencies]
orbit-analytics = { path = "../orbit-analytics", features = ["testkit"] }
tempfile = { workspace = true }
