use std::collections::{BTreeMap, BTreeSet};

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// Fingerprint-snapshot path relative to `CONFIG_DIR`.
pub const FINGERPRINT_FILE: &str = "schema-migrations.fingerprint.yaml";

const FINGERPRINT_HEADER: &str = "\
# GENERATED by `mise schema:bump` or `mise schema:snapshot` — do not edit.
#
# Versioned source or DDL drift requires a SCHEMA_VERSION bump and migration
# ledger entry. Auxiliary-schema drift requires `mise schema:snapshot` and does
# not invalidate indexed graph data. Describes current state only; history
# lives in git.
";

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Fingerprints {
    pub sources: BTreeMap<String, String>,
    pub ddl: BTreeMap<String, String>,
    #[serde(default)]
    pub auxiliary_schema: BTreeMap<String, String>,
}

impl Fingerprints {
    pub fn parse(content: &str) -> Result<Self, String> {
        serde_yaml::from_str(content).map_err(|e| format!("parsing fingerprint snapshot: {e}"))
    }

    #[must_use]
    pub fn render(&self) -> String {
        let body = serde_yaml::to_string(self).expect("fingerprints serialize");
        format!("{FINGERPRINT_HEADER}{body}")
    }

    #[must_use]
    pub fn get_versioned_diff_keys_between(
        &self,
        base: &Fingerprints,
    ) -> (BTreeSet<String>, BTreeSet<String>) {
        (
            get_diff_keys_between(&self.sources, &base.sources),
            get_diff_keys_between(&self.ddl, &base.ddl),
        )
    }

    #[must_use]
    pub fn get_auxiliary_schema_diff_keys_between(&self, base: &Fingerprints) -> BTreeSet<String> {
        get_diff_keys_between(&self.auxiliary_schema, &base.auxiliary_schema)
    }

    #[must_use]
    pub fn has_same_versioned_fingerprints_as(&self, base: &Fingerprints) -> bool {
        self.sources == base.sources && self.ddl == base.ddl
    }
}

#[must_use]
pub fn source_fingerprints() -> BTreeMap<String, String> {
    crate::loading::embedded_files()
        .into_iter()
        .filter(|(path, _)| !path.starts_with("sql/"))
        .map(|(path, content)| {
            let hash = if path == "schema.yaml" {
                stable_versioned_schema_hash(&content)
            } else if path.ends_with(".yaml") || path.ends_with(".yml") {
                stable_yaml_hash(&content)
            } else {
                sha256_hex(&content)
            };
            (path, hash)
        })
        .collect()
}

#[must_use]
pub fn embedded_sources() -> BTreeMap<String, String> {
    crate::loading::embedded_files().into_iter().collect()
}

#[must_use]
fn stable_yaml_hash(content: &str) -> String {
    match serde_yaml::from_str::<serde_yaml::Value>(content) {
        Ok(mut value) => {
            sort_yaml_keys(&mut value);
            match serde_yaml::to_string(&value) {
                Ok(rendered) => sha256_hex(&rendered),
                Err(_) => sha256_hex(content),
            }
        }
        Err(_) => sha256_hex(content),
    }
}

fn stable_versioned_schema_hash(content: &str) -> String {
    let Ok(mut value) = serde_yaml::from_str::<serde_yaml::Value>(content) else {
        return sha256_hex(content);
    };
    remove_auxiliary_schema_settings(&mut value);
    sort_yaml_keys(&mut value);
    serde_yaml::to_string(&value)
        .map(|rendered| sha256_hex(&rendered))
        .unwrap_or_else(|_| sha256_hex(content))
}

#[must_use]
pub fn sha256_hex(input: &str) -> String {
    use std::fmt::Write as _;

    let mut hasher = Sha256::new();
    hasher.update(input.as_bytes());
    let digest = hasher.finalize();
    let mut out = String::with_capacity(digest.len() * 2);
    for byte in digest {
        let _ = write!(out, "{byte:02x}");
    }
    out
}

fn sort_yaml_keys(value: &mut serde_yaml::Value) {
    match value {
        serde_yaml::Value::Mapping(map) => {
            let mut entries: Vec<(serde_yaml::Value, serde_yaml::Value)> =
                std::mem::take(map).into_iter().collect();
            for (_, v) in &mut entries {
                sort_yaml_keys(v);
            }
            entries.sort_by_key(|(key, _)| serialized_key(key));
            for (k, v) in entries {
                map.insert(k, v);
            }
        }
        serde_yaml::Value::Sequence(seq) => {
            for v in seq {
                sort_yaml_keys(v);
            }
        }
        _ => {}
    }
}

fn serialized_key(key: &serde_yaml::Value) -> String {
    serde_yaml::to_string(key).unwrap_or_default()
}

fn get_diff_keys_between(
    current: &BTreeMap<String, String>,
    base: &BTreeMap<String, String>,
) -> BTreeSet<String> {
    let mut changed = BTreeSet::new();
    for (key, hash) in current {
        if base.get(key) != Some(hash) {
            changed.insert(key.clone());
        }
    }
    for key in base.keys() {
        if !current.contains_key(key) {
            changed.insert(key.clone());
        }
    }
    changed
}

fn remove_auxiliary_schema_settings(value: &mut serde_yaml::Value) {
    let serde_yaml::Value::Mapping(schema) = value else {
        return;
    };
    let Some(serde_yaml::Value::Mapping(settings)) =
        schema.get_mut(serde_yaml::Value::String("settings".to_string()))
    else {
        return;
    };
    retain_versioned_auxiliary_tables(settings);
    settings.remove(serde_yaml::Value::String(
        "refreshable_materialized_views".to_string(),
    ));
}

fn retain_versioned_auxiliary_tables(settings: &mut serde_yaml::Mapping) {
    let key = serde_yaml::Value::String("auxiliary_tables".to_string());
    let Some(serde_yaml::Value::Sequence(tables)) = settings.get_mut(&key) else {
        return;
    };
    tables.retain(|table| {
        table
            .as_mapping()
            .and_then(|mapping| mapping.get(serde_yaml::Value::String("versioned".to_string())))
            .and_then(serde_yaml::Value::as_bool)
            .unwrap_or(true)
    });
    if tables.is_empty() {
        settings.remove(&key);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn set(names: &[&str]) -> BTreeSet<String> {
        names.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn stable_hash_ignores_comments_and_key_order() {
        let a = "b: 2\na: 1\n";
        let b = "# a leading comment\na: 1\nb: 2 # trailing\n";
        assert_eq!(stable_yaml_hash(a), stable_yaml_hash(b));
    }

    #[test]
    fn stable_hash_differs_on_value_change() {
        assert_ne!(stable_yaml_hash("a: 1\n"), stable_yaml_hash("a: 2\n"));
    }

    #[test]
    fn stable_hash_recurses_into_nested_maps() {
        let a = "outer:\n  y: 2\n  x: 1\n";
        let b = "outer:\n  x: 1\n  y: 2\n";
        assert_eq!(stable_yaml_hash(a), stable_yaml_hash(b));
    }

    #[test]
    fn versioned_schema_hash_ignores_ddl_owned_settings() {
        let first = "settings:\n  table_prefix: gl_\n";
        let second = "settings:\n  table_prefix: gl_\n  auxiliary_tables:\n    - name: first\n      versioned: false\n  refreshable_materialized_views:\n    - name: second\n      versioned: true\n      append_to: first\n      refresh: EVERY 1 DAY\n      select_file: sql/second.sql\n";
        assert_eq!(
            stable_versioned_schema_hash(first),
            stable_versioned_schema_hash(second)
        );
    }

    #[test]
    fn versioned_schema_hash_keeps_versioned_ddl_declarations() {
        let first = "settings:\n  auxiliary_tables:\n    - name: first\n";
        let second = "settings:\n  auxiliary_tables:\n    - name: second\n";
        assert_ne!(
            stable_versioned_schema_hash(first),
            stable_versioned_schema_hash(second)
        );
    }

    #[test]
    fn versioned_schema_hash_keeps_insert_trigger_views() {
        let first = "settings:\n  materialized_views:\n    - name: first\n      select_query: SELECT 1\n      engine: MergeTree\n";
        let second = "settings:\n  materialized_views:\n    - name: second\n      select_query: SELECT 1\n      engine: MergeTree\n";

        assert_ne!(
            stable_versioned_schema_hash(first),
            stable_versioned_schema_hash(second)
        );
    }

    #[test]
    fn versioned_schema_hash_keeps_other_settings() {
        let first = "settings:\n  table_prefix: gl_\n";
        let second = "settings:\n  table_prefix: graph_\n";
        assert_ne!(
            stable_versioned_schema_hash(first),
            stable_versioned_schema_hash(second)
        );
    }

    #[test]
    fn diff_reports_changed_added_and_removed() {
        let base = Fingerprints {
            sources: BTreeMap::from([("a".into(), "1".into()), ("b".into(), "2".into())]),
            ddl: BTreeMap::from([("t".into(), "9".into())]),
            auxiliary_schema: BTreeMap::new(),
        };
        let current = Fingerprints {
            sources: BTreeMap::from([
                ("a".into(), "1".into()),
                ("b".into(), "changed".into()),
                ("c".into(), "3".into()),
            ]),
            ddl: BTreeMap::new(),
            auxiliary_schema: BTreeMap::new(),
        };
        let (sources, ddl) = current.get_versioned_diff_keys_between(&base);
        assert_eq!(sources, set(&["b", "c"]));
        assert_eq!(ddl, set(&["t"]));
    }
}
