CREATE TABLE IF NOT EXISTS gl_job (
    id Int64 CODEC(Delta(8), LZ4),
    name String DEFAULT '' CODEC(ZSTD(1)),
    status LowCardinality(String) DEFAULT '' CODEC(LZ4),
    ref String DEFAULT '' CODEC(ZSTD(1)),
    tag Nullable(Bool),
    allow_failure Bool DEFAULT false,
    coverage String DEFAULT '' CODEC(ZSTD(1)),
    environment String DEFAULT '' CODEC(ZSTD(1)),
    `when` String DEFAULT '' CODEC(ZSTD(1)),
    retried Nullable(Bool),
    failure_reason Nullable(String) CODEC(ZSTD(1)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    started_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    finished_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    queued_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    runner_id Nullable(Int64) CODEC(Delta(8), LZ4),
    timeout Nullable(Int64) CODEC(Delta(8), LZ4),
    timeout_source LowCardinality(String) DEFAULT '' CODEC(LZ4),
    exit_code Nullable(Int64) CODEC(Delta(8), LZ4),
    scheduling_type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    project_id Int64 CODEC(Delta(8), LZ4),
    user_id Nullable(Int64) CODEC(Delta(8), LZ4),
    upstream_pipeline_id Nullable(Int64) CODEC(Delta(8), LZ4),
    stage_id Nullable(Int64) CODEC(Delta(8), LZ4),
    pipeline_id Nullable(Int64) CODEC(Delta(8), LZ4),
    auto_canceled_by_id Nullable(Int64) CODEC(Delta(8), LZ4),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;
