CREATE TABLE IF NOT EXISTS siphon_p_ci_builds
(
    `status` LowCardinality(String) DEFAULT '',
    `finished_at` Nullable(DateTime64(6, 'UTC')),
    `created_at` DateTime64(6, 'UTC') DEFAULT now(),
    `updated_at` DateTime64(6, 'UTC') DEFAULT now(),
    `started_at` Nullable(DateTime64(6, 'UTC')),
    `coverage` Nullable(Float64),
    `name` Nullable(String),
    `options` Nullable(String),
    `allow_failure` Bool DEFAULT false,
    `stage_idx` Nullable(Int64),
    `tag` Nullable(Bool),
    `ref` Nullable(String),
    `type` LowCardinality(String) DEFAULT '',
    `target_url` Nullable(String),
    `description` Nullable(String),
    `erased_at` Nullable(DateTime64(6, 'UTC')),
    `artifacts_expire_at` Nullable(DateTime64(6, 'UTC')),
    `environment` LowCardinality(String) DEFAULT '',
    `when` LowCardinality(String) DEFAULT '',
    `yaml_variables` Nullable(String),
    `queued_at` Nullable(DateTime64(6, 'UTC')),
    `lock_version` Int64 DEFAULT 0,
    `coverage_regex` Nullable(String),
    `retried` Nullable(Bool),
    `protected` Nullable(Bool),
    `failure_reason` Nullable(Int64),
    `scheduled_at` Nullable(DateTime64(6, 'UTC')),
    `token_encrypted` Nullable(String),
    `resource_group_id` Nullable(Int64),
    `waiting_for_resource_at` Nullable(DateTime64(6, 'UTC')),
    `processed` Nullable(Bool),
    `scheduling_type` Nullable(Int16),
    `id` Int64,
    `stage_id` Nullable(Int64),
    `partition_id` Int64,
    `auto_canceled_by_partition_id` Nullable(Int64),
    `auto_canceled_by_id` Nullable(Int64),
    `commit_id` Nullable(Int64),
    `erased_by_id` Nullable(Int64),
    `project_id` Int64,
    `runner_id` Nullable(Int64),
    `upstream_pipeline_id` Nullable(Int64),
    `user_id` Nullable(Int64),
    `execution_config_id` Nullable(Int64),
    `upstream_pipeline_partition_id` Nullable(Int64),
    `scoped_user_id` Nullable(Int64),
    `timeout` Nullable(Int64),
    `timeout_source` Nullable(Int16),
    `exit_code` Nullable(Int16),
    `debug_trace_enabled` Nullable(Bool),
    `traversal_path` String DEFAULT '0/',
    `_siphon_replicated_at` DateTime64(6, 'UTC') DEFAULT now(),
    `_siphon_deleted` Bool DEFAULT FALSE
)
ENGINE = ReplacingMergeTree(_siphon_replicated_at, _siphon_deleted)
PRIMARY KEY (traversal_path, id, partition_id)
ORDER BY (traversal_path, id, partition_id);
