//! CNG setup: post-deploy configuration.
//!
//! Runs after CNG deploy has stood up GitLab. Configures the cluster
//! for the GKG stack:
//!
//!   8.  Bridge PG credentials to default namespace (for Siphon)
//!   9.  Grant REPLICATION privilege to gitlab PG user (for Siphon WAL sender)
//!  10.  Extract JWT secret from toolbox pod -> e2e/tilt/.secrets
//!  11.  Run Rails db:migrate
//!  12.  Enable :knowledge_graph feature flag
//!  13.  Copy test scripts into toolbox pod
//!  14.  Create test data (users, groups, projects, MRs)

use std::fs;

use anyhow::{Context, Result};
use xshell::{Shell, cmd};

use super::super::config::Config;
use super::super::constants as c;
use super::super::kubectl;
use super::super::ui;

/// Run all CNG setup steps.
pub fn run(sh: &Shell, cfg: &Config) -> Result<()> {
    ui::banner("CNG Setup: Post-deploy Configuration")?;

    fs::create_dir_all(&cfg.log_dir)?;

    let toolbox_pod = kubectl::get_toolbox_pod(sh, cfg)?;
    ui::detail("Toolbox pod", &toolbox_pod)?;

    bridge_pg_credentials(sh, cfg)?;
    grant_replication(sh, cfg)?;
    extract_jwt_secret(sh, cfg, &toolbox_pod)?;
    run_db_migrate(sh, cfg, &toolbox_pod)?;
    enable_feature_flag(sh, cfg, &toolbox_pod)?;
    copy_test_scripts(sh, cfg, &toolbox_pod)?;
    create_test_data(sh, cfg, &toolbox_pod)?;

    ui::outro("CNG setup complete")?;
    Ok(())
}

// -- Step 8: Bridge PG credentials --------------------------------------------

fn bridge_pg_credentials(sh: &Shell, cfg: &Config) -> Result<()> {
    ui::step(8, "Bridging PostgreSQL credentials")?;

    let pg_pass = kubectl::read_secret(
        sh,
        &cfg.gitlab_ns,
        &cfg.pg_secret_name,
        &cfg.pg_password_key,
    )?;
    let default_ns = &cfg.default_ns;
    let bridge_secret = c::PG_BRIDGE_SECRET_NAME;

    // kubectl create --dry-run=client -o yaml | kubectl apply -f - is idempotent.
    let yaml = cmd!(
        sh,
        "kubectl create secret generic {bridge_secret}
            -n {default_ns}
            --from-literal=password={pg_pass}
            --dry-run=client -o yaml"
    )
    .quiet()
    .read()?;

    cmd!(sh, "kubectl apply -f -").stdin(&yaml).quiet().run()?;

    ui::done(&format!("{bridge_secret} secret created in {default_ns}"))?;
    Ok(())
}

// -- Step 9: Grant REPLICATION privilege ---------------------------------------

fn grant_replication(sh: &Shell, cfg: &Config) -> Result<()> {
    ui::step(
        9,
        &format!("Granting REPLICATION privilege to {} PG user", cfg.pg_user),
    )?;

    let pg_superpass = kubectl::read_secret(
        sh,
        &cfg.gitlab_ns,
        &cfg.pg_secret_name,
        &cfg.pg_superpass_key,
    )?;
    let sql = format!("ALTER USER {} REPLICATION;", cfg.pg_user);

    kubectl::pg_superuser_exec(sh, cfg, &pg_superpass, &sql)?;

    ui::done("REPLICATION privilege granted")?;
    Ok(())
}

// -- Step 10: Extract JWT secret ----------------------------------------------

fn extract_jwt_secret(sh: &Shell, cfg: &Config, toolbox_pod: &str) -> Result<()> {
    ui::step(10, "Extracting JWT secret")?;

    let jwt_path = &cfg.jwt_secret_path;
    let jwt_secret = kubectl::toolbox_exec(sh, cfg, toolbox_pod, &["cat", jwt_path]);

    match jwt_secret {
        Ok(secret) if !secret.is_empty() => {
            let pg_pass = kubectl::read_secret(
                sh,
                &cfg.gitlab_ns,
                &cfg.pg_secret_name,
                &cfg.pg_password_key,
            )?;

            let secrets_file = cfg.tilt_dir.join(c::SECRETS_FILE);
            fs::create_dir_all(&cfg.tilt_dir)?;

            let contents = format!(
                "# Auto-generated by cargo xtask e2e setup\n\
                 POSTGRES_PASSWORD={pg_pass}\n\
                 CLICKHOUSE_PASSWORD=\n\
                 GKG_JWT_SECRET={secret}\n"
            );
            fs::write(&secrets_file, contents)?;

            ui::done(&format!("Written to {}", secrets_file.display()))?;
        }
        _ => {
            ui::warn("Could not extract JWT secret. You'll need to set it manually.")?;
        }
    }

    Ok(())
}

// -- Step 11: Run Rails db:migrate --------------------------------------------

fn run_db_migrate(sh: &Shell, cfg: &Config, toolbox_pod: &str) -> Result<()> {
    ui::step(11, "Running Rails db:migrate")?;

    let ns = &cfg.gitlab_ns;
    let rails_root = &cfg.rails_root;
    let script = r#"cd "$0" && bundle exec rails db:migrate RAILS_ENV=production"#.to_string();

    cmd!(
        sh,
        "kubectl exec -n {ns} {toolbox_pod} -- bash -c {script} {rails_root}"
    )
    .run()
    .context("rails db:migrate failed")?;

    ui::done("Migrations complete")?;
    Ok(())
}

// -- Step 12: Enable feature flag ---------------------------------------------

fn enable_feature_flag(sh: &Shell, cfg: &Config, toolbox_pod: &str) -> Result<()> {
    ui::step(12, "Enabling :knowledge_graph feature flag")?;

    kubectl::toolbox_rails_eval(sh, cfg, toolbox_pod, "Feature.enable(:knowledge_graph)")?;

    ui::done("Feature flag enabled")?;
    Ok(())
}

// -- Step 13: Copy test scripts -----------------------------------------------

fn copy_test_scripts(sh: &Shell, cfg: &Config, toolbox_pod: &str) -> Result<()> {
    ui::step(13, "Copying test scripts to toolbox pod")?;

    let ns = &cfg.gitlab_ns;
    let e2e_pod_dir = &cfg.e2e_pod_dir;

    kubectl::toolbox_exec(sh, cfg, toolbox_pod, &["mkdir", "-p", e2e_pod_dir])?;

    let tests_dir = cfg.gkg_root.join(c::E2E_TESTS_DIR);
    if !tests_dir.exists() {
        ui::warn(&format!("No test scripts found at {}", tests_dir.display()))?;
        return Ok(());
    }

    for entry in fs::read_dir(&tests_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().is_some_and(|ext| ext == "rb") {
            let filename = path.file_name().unwrap().to_string_lossy();
            let src = path.to_string_lossy().to_string();
            let dest = format!("{ns}/{toolbox_pod}:{e2e_pod_dir}/{filename}");

            cmd!(sh, "kubectl cp {src} {dest}").quiet().run()?;
            ui::detail_item(&format!("Copied {filename}"))?;
        }
    }

    ui::done(&format!("Test scripts at {e2e_pod_dir}/ in toolbox pod"))?;
    Ok(())
}

// -- Step 14: Create test data ------------------------------------------------

fn create_test_data(sh: &Shell, cfg: &Config, toolbox_pod: &str) -> Result<()> {
    ui::step(14, "Creating test data")?;

    let ns = &cfg.gitlab_ns;
    let rails_root = &cfg.rails_root;
    let e2e_pod_dir = &cfg.e2e_pod_dir;
    let script =
        r#"cd "$0" && bundle exec rails runner "$1"/create_test_data.rb RAILS_ENV=production"#
            .to_string();

    let output = cmd!(
        sh,
        "kubectl exec -n {ns} {toolbox_pod} -- bash -c {script} {rails_root} {e2e_pod_dir}"
    )
    .ignore_status()
    .output()?;

    let stdout = String::from_utf8_lossy(&output.stdout);

    // Write log
    let log_path = cfg.log_dir.join(c::CREATE_TEST_DATA_LOG);
    fs::write(&log_path, stdout.as_ref())?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        ui::warn(&format!("create_test_data.rb exited with error: {stderr}"))?;
        ui::warn(&format!("Check {}", log_path.display()))?;
    }

    ui::done("Test data creation complete")?;

    // Check if manifest was written
    let manifest_check = kubectl::toolbox_exec(
        sh,
        cfg,
        toolbox_pod,
        &["test", "-f", &cfg.manifest_pod_path],
    );

    if manifest_check.is_ok() {
        ui::info("Manifest verified in toolbox pod")?;

        let pod_path = format!("{ns}/{toolbox_pod}:{}", cfg.manifest_pod_path);
        let local_path = cfg.log_dir.join(c::MANIFEST_JSON);
        let local_str = local_path.to_string_lossy().to_string();
        let _ = cmd!(sh, "kubectl cp {pod_path} {local_str}")
            .quiet()
            .ignore_status()
            .run();
        ui::info(&format!("Manifest copied to {}", local_path.display()))?;
    } else {
        ui::warn(&format!(
            "Manifest not found at {} -- create_test_data.rb may have failed",
            cfg.manifest_pod_path
        ))?;
        ui::warn(&format!("Check {}", log_path.display()))?;
    }

    Ok(())
}
