{{- include "siphon.prepareDeployments" $ -}}
{{- range $name, $deployment := .Values.deployments }}
{{- if $deployment.enabled }}
{{- $globalLabels := $.Values.labels | default dict }}
{{- $deployLabels := $deployment.labels | default dict }}
{{- $mergedLabels := mergeOverwrite (deepCopy $globalLabels) $deployLabels }}
{{- $globalPodSpec := $.Values.podSpec | default dict }}
{{- $deployPodSpec := $deployment.podSpec | default dict }}
{{- $mergedPodSpec := mergeOverwrite (deepCopy $globalPodSpec) $deployPodSpec }}
{{- $reloader := $deployment.reloader | default $.Values.reloader }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "siphon.labels" (dict "name" $name "context" $) | nindent 4 }}
    {{- with $mergedLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if or $reloader $deployment.annotations }}
  annotations:
    {{- if $reloader }}
    configmap.reloader.stakater.com/reload: {{ $name }}-config
    {{- if $deployment.envFromSecrets }}
    {{- $secretNames := list }}
    {{- range $deployment.envFromSecrets }}
    {{- $secretNames = append $secretNames .secretName }}
    {{- end }}
    secret.reloader.stakater.com/reload: {{ $secretNames | uniq | join "," | quote }}
    {{- end }}
    {{- end }}
    {{- with $deployment.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
spec:
  replicas: {{ $deployment.replicas | default $.Values.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "siphon.selectorLabels" (dict "name" $name) | nindent 6 }}
  template:
{{ include "siphon.pod" (dict
  "deployment" $deployment
  "name" $name
  "context" $
  "command" $deployment.command
  "args" $deployment.args
  "metricsPort" ((($deployment.metrics).port) | default $.Values.metrics.port)
  "resources" ($deployment.resources | default $.Values.resources)
  "podSpec" $mergedPodSpec
  "labels" $mergedLabels
  "env" $deployment.env
  "envFromSecrets" $deployment.envFromSecrets
  "volumes" $deployment.volumes
  "volumeMounts" $deployment.volumeMounts
) | indent 4 }}
{{- end }}
{{- end }}
