[package]
name = "orbit-devtools"
version.workspace = true
edition = "2024"
license = "MIT"

[[bin]]
name = "orbit-devtools"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
compiler = { path = "../query-engine/compiler" }
ontology = { path = "../ontology" }
orbit-utils = { path = "../utils" }

[lints]
workspace = true
