{{- if .Values.webserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gkg.fullname" . }}-webserver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gkg.componentLabels" (dict "root" . "component" "webserver") | nindent 4 }}
  {{- with .Values.webserver.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webserver.service.type }}
  ports:
    - port: {{ .Values.webserver.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.webserver.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "gkg.componentSelectorLabels" (dict "root" . "component" "webserver") | nindent 4 }}
{{- end }}
