image: python:3.12-slim

robotframework:
  version: "7.4.2"
  requestsVersion: "0.9.7"
  pabotVersion: "5.2.2"
  processes: 12

resources:
  requests:
    cpu: "1"
    memory: 1Gi
  limits:
    cpu: "4"
    memory: 2Gi

namespaces:
  gitlab: ""
  gkg: ""

configMap: e2e-robot-tests
fixturesConfigMap: e2e-robot-fixtures
rootPatSecret: gitlab-root-pat
rootPatSecretNamespace: ""
rootPatSecretKey: pat
ttlSecondsAfterFinished: 600
