#!/usr/bin/env bash
# =============================================================================
# post-deploy.sh -- Post-deploy setup for GKG E2E with caproni
#
# Runs after `caproni up` and before `tilt up`. Sets up:
#   1. Wait for GitLab pods to be ready
#   2. Bridge secrets from gitlab namespace to default namespace (for Siphon)
#   3. Extract JWT secret for GKG server
#   4. Run Rails db:migrate (creates knowledge_graph tables)
#   5. Enable :knowledge_graph feature flag
#   6. Create test data (group 99, project 19, users, memberships)
#   7. Copy test scripts into the toolbox pod
#
# Usage:
#   cd ~/Desktop/Code/gkg/e2e/caproni
#   ./post-deploy.sh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
GKG_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
TILT_DIR="${GKG_ROOT}/e2e/tilt"
GITLAB_NS="gitlab"
DEFAULT_NS="default"

echo "=== GKG E2E: Post-deploy setup ==="

# ---- 1. Wait for GitLab pods to be ready ------------------------------------

echo ""
echo "--- Waiting for GitLab webservice to be ready (timeout 10m) ---"
kubectl wait --for=condition=ready pod \
  -l app=webservice \
  -n "${GITLAB_NS}" \
  --timeout=600s 2>/dev/null || {
    echo "WARNING: webservice not ready after 10m. Continuing anyway..."
  }

echo "--- Waiting for GitLab toolbox to be ready ---"
kubectl wait --for=condition=ready pod \
  -l app=toolbox \
  -n "${GITLAB_NS}" \
  --timeout=300s 2>/dev/null || {
    echo "WARNING: toolbox not ready after 5m. Continuing anyway..."
  }

echo "--- Waiting for PostgreSQL to be ready ---"
kubectl wait --for=condition=ready pod \
  -l app.kubernetes.io/name=postgresql \
  -n "${GITLAB_NS}" \
  --timeout=300s 2>/dev/null || {
    echo "WARNING: postgresql not ready after 5m. Continuing anyway..."
  }

# ---- 2. Bridge PG credentials to default namespace --------------------------
# Siphon (in default ns) needs the postgres password to connect to the
# GitLab PG (in gitlab ns).

echo ""
echo "--- Bridging PostgreSQL credentials to default namespace ---"

PG_PASS=$(kubectl get secret -n "${GITLAB_NS}" gitlab-postgresql-password \
  -o jsonpath='{.data.postgresql-password}' | base64 -d)

kubectl create secret generic postgres-credentials \
  -n "${DEFAULT_NS}" \
  --from-literal=password="${PG_PASS}" \
  --dry-run=client -o yaml | kubectl apply -f -

echo "    Created postgres-credentials secret in ${DEFAULT_NS} namespace"

# ---- 3. Extract JWT secret for GKG server -----------------------------------
# The GKG server validates JWTs signed with .gitlab_shell_secret.
# Extract it from the webservice pod and write to e2e/tilt/.secrets.

echo ""
echo "--- Extracting JWT secret ---"

TOOLBOX_POD=$(kubectl get pod -n "${GITLAB_NS}" -l app=toolbox \
  -o jsonpath='{.items[0].metadata.name}')

JWT_SECRET=$(kubectl exec -n "${GITLAB_NS}" "${TOOLBOX_POD}" -- \
  cat /srv/gitlab/.gitlab_shell_secret 2>/dev/null || echo "")

if [ -z "${JWT_SECRET}" ]; then
  echo "WARNING: Could not extract .gitlab_shell_secret from toolbox pod."
  echo "         You may need to manually set GKG_JWT_SECRET in ${TILT_DIR}/.secrets"
else
  # Write .secrets file for Tilt
  cat > "${TILT_DIR}/.secrets" <<EOF
# Auto-generated by post-deploy.sh
POSTGRES_PASSWORD=${PG_PASS}
CLICKHOUSE_PASSWORD=
GKG_JWT_SECRET=${JWT_SECRET}
EOF
  echo "    Written to ${TILT_DIR}/.secrets"
fi

# ---- 4. Run Rails db:migrate ------------------------------------------------
# The feature branch has migrations that create knowledge_graph tables
# (knowledge_graph_enabled_namespaces, etc.)

echo ""
echo "--- Running Rails db:migrate ---"

kubectl exec -n "${GITLAB_NS}" "${TOOLBOX_POD}" -- \
  bash -c 'cd /srv/gitlab && bundle exec rails db:migrate RAILS_ENV=production' \
  2>&1 | tail -5

echo "    Migrations complete"

# ---- 5. Enable feature flag -------------------------------------------------

echo ""
echo "--- Enabling :knowledge_graph feature flag ---"

kubectl exec -n "${GITLAB_NS}" "${TOOLBOX_POD}" -- \
  bash -c 'cd /srv/gitlab && echo "Feature.enable(:knowledge_graph)" | bundle exec rails console -e production' \
  2>&1 | tail -3

echo "    Feature flag enabled"

# ---- 6. Copy test scripts into toolbox pod -----------------------------------

echo ""
echo "--- Copying test scripts to toolbox pod ---"

kubectl exec -n "${GITLAB_NS}" "${TOOLBOX_POD}" -- mkdir -p /tmp/e2e
kubectl cp "${GKG_ROOT}/tests/e2e/" "${GITLAB_NS}/${TOOLBOX_POD}:/tmp/e2e/"

echo "    Test scripts copied to /tmp/e2e/ in toolbox pod"

# ---- 7. Create test data ----------------------------------------------------
# Group 99 (kg-redaction-test-group), project 19, users, memberships.

echo ""
echo "--- Creating test data ---"

kubectl exec -n "${GITLAB_NS}" "${TOOLBOX_POD}" -- \
  bash -c 'cd /srv/gitlab && bundle exec rails runner /tmp/e2e/create_test_data.rb RAILS_ENV=production' \
  2>&1 | tail -5

echo "    Test data created"

# ---- Done --------------------------------------------------------------------

echo ""
echo "=== Post-deploy setup complete ==="
echo ""
echo "Next steps:"
echo "  1. Deploy GKG infrastructure:"
echo "     cd ${GKG_ROOT}"
echo "     GKG_E2E_CAPRONI=1 mise exec -- tilt up --file e2e/tilt/Tiltfile"
echo ""
echo "  2. Wait for all pods to be ready, then run tests:"
echo "     kubectl exec -n ${GITLAB_NS} ${TOOLBOX_POD} -- \\"
echo "       bash -c 'cd /srv/gitlab && bundle exec rails runner /tmp/e2e/redaction_test.rb RAILS_ENV=production'"
echo ""
echo "  PostgreSQL is available at:"
echo "    gitlab-postgresql.${GITLAB_NS}.svc.cluster.local:5432"
echo "    Database: gitlabhq_production"
echo "    User: gitlab"
echo "    Password: (in postgres-credentials secret)"
