#!/usr/bin/env bash
# =============================================================================
# teardown.sh -- Remove the entire E2E environment
#
# Levels of teardown:
#
#   ./teardown.sh              Full teardown: Tilt + GitLab + Colima
#   ./teardown.sh --keep-colima  Remove Tilt + GitLab but keep the Colima VM
#   ./teardown.sh --tilt-only    Only tear down Tilt resources (keep GitLab + Colima)
#
# This is the inverse of setup.sh. After a full teardown, you can re-run
# setup.sh for a cleanroom install.
#
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
GKG_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
TILT_DIR="${GKG_ROOT}/e2e/tilt"
LOG_DIR="${GKG_ROOT}/.dev"

COLIMA_PROFILE="${COLIMA_PROFILE:-caproni}"
GITLAB_NS="gitlab"

# Parse flags
KEEP_COLIMA=false
TILT_ONLY=false
for arg in "$@"; do
  case "$arg" in
    --keep-colima) KEEP_COLIMA=true ;;
    --tilt-only)   TILT_ONLY=true; KEEP_COLIMA=true ;;
    --help|-h)
      head -20 "$0" | grep '^#' | sed 's/^# *//'
      exit 0
      ;;
  esac
done

log()  { echo ""; echo "=== $1 ==="; }
step() { echo "--- $1 ---"; }

ensure_docker_host() {
  export DOCKER_HOST="unix://${HOME}/.colima/${COLIMA_PROFILE}/docker.sock"
}

echo ""
echo "================================================================"
echo "  GKG E2E Teardown"
echo "================================================================"
echo "  Keep Colima: ${KEEP_COLIMA}"
echo "  Tilt only:   ${TILT_ONLY}"
echo "================================================================"

# ── 1. Tear down Tilt (GKG stack) ────────────────────────────────────────────

log "1. Tearing down Tilt resources (GKG stack)"

ensure_docker_host 2>/dev/null || true

# Stop Tilt if running (sends SIGTERM to tilt process)
if pgrep -f "tilt up.*Tiltfile" >/dev/null 2>&1; then
  step "Stopping Tilt process..."
  pkill -f "tilt up.*Tiltfile" 2>/dev/null || true
  sleep 2
fi

# Remove Tilt-managed resources via tilt down
if command -v tilt &>/dev/null; then
  step "Running tilt down..."
  (cd "${GKG_ROOT}" && tilt down --file e2e/tilt/Tiltfile 2>/dev/null) || true
fi

# Clean up any remaining resources in default namespace
# ClickHouse is deployed standalone (not via Tilt) since setup.sh Phase 3
step "Cleaning up default namespace resources..."
kubectl delete deployment -n default -l 'app.kubernetes.io/managed-by=tilt' --ignore-not-found 2>/dev/null || true
kubectl delete statefulset -n default gkg-e2e-clickhouse --ignore-not-found 2>/dev/null || true
kubectl delete job -n default gkg-e2e-migrate gkg-dispatch-indexing --ignore-not-found 2>/dev/null || true
kubectl delete service -n default gkg-e2e-clickhouse --ignore-not-found 2>/dev/null || true
kubectl delete configmap -n default gkg-e2e-clickhouse-init --ignore-not-found 2>/dev/null || true
kubectl delete secret -n default postgres-credentials clickhouse-credentials gkg-server-credentials --ignore-not-found 2>/dev/null || true
kubectl delete pvc -n default -l app=gkg-e2e-clickhouse --ignore-not-found 2>/dev/null || true

# Remove Helm release for GKG if it exists
helm uninstall gkg-e2e -n default 2>/dev/null || true

step "Tilt resources removed"

if [ "${TILT_ONLY}" = true ]; then
  echo ""
  echo "Tilt-only teardown complete. GitLab and Colima still running."
  echo "Re-run Tilt: cd ${GKG_ROOT} && GKG_E2E_CAPRONI=1 mise exec -- tilt up --file e2e/tilt/Tiltfile"
  exit 0
fi

# ── 2. Tear down GitLab (Helm release) ───────────────────────────────────────

log "2. Tearing down GitLab"

ensure_docker_host 2>/dev/null || true

if helm status gitlab -n "${GITLAB_NS}" &>/dev/null; then
  step "Uninstalling GitLab Helm release..."
  helm uninstall gitlab -n "${GITLAB_NS}" --timeout 5m 2>&1 | tail -3 || true
  step "GitLab Helm release removed"
else
  step "No GitLab Helm release found"
fi

# Clean up PVCs (persistent data)
step "Removing GitLab PVCs..."
kubectl delete pvc -n "${GITLAB_NS}" --all --ignore-not-found 2>/dev/null || true

# Remove namespace
step "Removing ${GITLAB_NS} namespace..."
kubectl delete namespace "${GITLAB_NS}" --ignore-not-found --timeout=120s 2>/dev/null || true

# ── 3. Tear down Traefik ─────────────────────────────────────────────────────

log "3. Tearing down Traefik"

if helm status traefik -n kube-system &>/dev/null; then
  step "Uninstalling Traefik..."
  helm uninstall traefik -n kube-system 2>&1 | tail -3 || true
  step "Traefik removed"
else
  step "No Traefik release found"
fi

# ── 4. Clean up local artifacts ──────────────────────────────────────────────

log "4. Cleaning up local artifacts"

# Remove .secrets (will be regenerated by setup.sh)
if [ -f "${TILT_DIR}/.secrets" ]; then
  rm -f "${TILT_DIR}/.secrets"
  step "Removed ${TILT_DIR}/.secrets"
fi

# Remove logs and manifest
if [ -d "${LOG_DIR}" ]; then
  rm -f "${LOG_DIR}/create-test-data.log" "${LOG_DIR}/manifest.json" \
        "${LOG_DIR}/colima-start.log" "${LOG_DIR}/tilt-ci.log" \
        "${LOG_DIR}/tilt-ci.pid" "${LOG_DIR}/clickhouse-migrate.log"
  step "Cleaned ${LOG_DIR}/"
fi

# ── 5. Stop Colima ───────────────────────────────────────────────────────────

if [ "${KEEP_COLIMA}" = false ]; then
  log "5. Stopping Colima (profile: ${COLIMA_PROFILE})"

  if colima status --profile "${COLIMA_PROFILE}" &>/dev/null; then
    step "Stopping Colima VM..."
    colima stop --profile "${COLIMA_PROFILE}" 2>&1 || true

    step "Deleting Colima VM..."
    colima delete --profile "${COLIMA_PROFILE}" --force 2>&1 || true

    step "Colima VM deleted"
  else
    step "Colima (${COLIMA_PROFILE}) not running"
  fi

  # Remove docker images from colima's daemon (they're gone with the VM anyway)
  step "Note: CNG images are gone with the Colima VM."
  step "They will be rebuilt on next setup.sh run."
else
  log "5. Keeping Colima VM (--keep-colima)"
  step "Colima profile '${COLIMA_PROFILE}' still running"

  # Optionally remove docker images to free space
  ensure_docker_host 2>/dev/null || true
  step "Docker images still present:"
  docker images "gkg-e2e/*" --format "  {{.Repository}}:{{.Tag}}  ({{.Size}})" 2>/dev/null || true
fi

# ── Done ─────────────────────────────────────────────────────────────────────

echo ""
echo "================================================================"
echo "  Teardown complete!"
echo "================================================================"
if [ "${KEEP_COLIMA}" = true ]; then
  echo ""
  echo "  Colima VM is still running. To fully remove:"
  echo "    colima stop --profile ${COLIMA_PROFILE}"
  echo "    colima delete --profile ${COLIMA_PROFILE} --force"
fi
echo ""
echo "  To start fresh:"
echo "    cd ${SCRIPT_DIR}"
echo "    ./setup.sh"
echo ""
