description: User who approved a merge request

variants:
  - from_node: { type: User, id: id }
    to_node: { type: MergeRequest, id: id }
    scope: prune_to_target
    description: "User approved a merge request."

sources:
  - table: siphon_approvals
    scope: namespaced
    order_by: [traversal_path, merge_request_id, id]
    from:
      id: user_id
      type: User
      enrich: [state, private_profile, admin, auditor, external, user_type]
    to:
      id: merge_request_id
      type: MergeRequest
      enrich: [state_id, merge_status, draft, squash, discussion_locked]
  - node: MergeRequest
    from: {type: User, id: user_id}
    to: {type: MergeRequest, id: id}
    unnest: approvals
