# config/ontology/edges/authored.yaml

description: Authorship relationship between users and entities

variants:
  - from_node: { type: User, id: id }
    to_node: { type: Note, id: id }
    description: "User authored note."

  - from_node: { type: User, id: id }
    to_node: { type: MergeRequest, id: id }
    description: "User authored merge request."

  - from_node: { type: User, id: id }
    to_node: { type: Vulnerability, id: id }
    description: "User reported vulnerability."

  - from_node: { type: User, id: id }
    to_node: { type: WorkItem, id: id }
    description: "User authored work item."

denormalized_properties:
  - node: MergeRequest
    property: state
    direction: target
  - node: WorkItem
    property: state
    direction: target
  - node: WorkItem
    property: work_item_type
    direction: target
  - node: Vulnerability
    property: state
    direction: target
  - node: Vulnerability
    property: severity
    direction: target

