# config/ontology/edges/creator.yaml

description: User created project

variants:
  - from_node: { type: User, id: id }
    to_node: { type: Project, id: id }
    scope: prune_to_target
    description: "User created project."

sources:
  - node: Project
    from: {type: User, id: creator_id}
    to: {type: Project, id: id}
