# config/ontology/edges/deployed_to.yaml

description: Merge request was deployed as part of a deployment

variants:
  - from_node: { type: MergeRequest, id: id }
    to_node: { type: Deployment, id: id }
    description: "Merge request was included in deployment."

etl:
  - scope: namespaced
    source: siphon_deployment_merge_requests
    order_by: [traversal_path, deployment_id, merge_request_id]
    from:
      id: merge_request_id
      type: MergeRequest
    to:
      id: deployment_id
      type: Deployment
