description: Finding was detected by a vulnerability scanner

edges:
  - from: {node: Finding, key: scanner_id}
    to:   {node: VulnerabilityScanner, key: id}
  - from: {node: VulnerabilityOccurrence, key: scanner_id}
    to:   {node: VulnerabilityScanner, key: id}
