# config/ontology/edges/detected_in.yaml

description: Pipeline where finding was detected

properties:
  detection_type:
    type: enum
    source: detection_type
    nullable: false
    description: "Whether this is the first or most recent detection."
    values:
      0: initial
      1: latest

variants:
  - from_node: { type: Finding, id: id }
    to_node: { type: Pipeline, id: id }
    description: "Finding was first detected in pipeline."

  - from_node: { type: Finding, id: id }
    to_node: { type: Pipeline, id: id }
    description: "Finding was last detected in pipeline."
