# config/ontology/edges/dismissed_by.yaml

description: User who dismissed a vulnerability

variants:
  - from_node: { type: User, id: id }
    to_node: { type: Vulnerability, id: id }
    fk_column: dismissed_by_id
    scope: prune_to_target
    description: "User dismissed vulnerability."
