# config/ontology/edges/fixes.yaml

description: Merge request fixes a vulnerability

variants:
  - from_node: { type: MergeRequest, id: id }
    to_node: { type: Vulnerability, id: id }
    description: "Merge request fixes vulnerability."

etl:
  - scope: namespaced
    source: siphon_vulnerability_merge_request_links
    order_by: [traversal_path, id]
    from:
      id: merge_request_id
      type: MergeRequest
      # enrich: [state_id]  # denorm: MR state
    to:
      id: vulnerability_id
      type: Vulnerability
      # enrich: [state, severity]  # denorm: vulnerability state + severity
