# config/ontology/edges/has_head_pipeline.yaml

description: Merge request's head pipeline (pipeline running against the tip of the source branch)

variants:
  - from_node: { type: MergeRequest, id: id }
    to_node: { type: Pipeline, id: id }
    description: "Merge request has head pipeline."

denormalized_properties:
  - node: MergeRequest
    property: state
    direction: source
  - node: Pipeline
    property: status
    direction: target
