description: Pipeline or stage contains job relationship

table: gl_ci_edge
scope: same_namespace
edges:
  - from: {node: Stage, key: id}
    to:   {node: Job, key: stage_id}
  - from: {node: Pipeline, key: id}
    to:   {node: Job, key: pipeline_id}
