description: Entity has associated finding or vulnerability occurrence

scope: same_namespace
edges:
  - from: {node: Vulnerability, key: finding_id}
    to:   {node: VulnerabilityOccurrence, key: id}
  - from: {node: SecurityScan, key: id}
    to:   {node: Finding, key: scan_id}
