# config/ontology/edges/has_diff.yaml

description: Diff snapshots of a merge request

variants:
  - from_node: { type: MergeRequest, id: id }
    to_node: { type: MergeRequestDiff, id: id }
    fk_column: merge_request_id
    description: "Merge request has a diff snapshot."
