# config/ontology/edges/has_stage.yaml

description: Pipeline contains stage relationship
table: gl_ci_edge

variants:
  - from_node: { type: Pipeline, id: id }
    to_node: { type: Stage, id: id }
    description: "Pipeline contains stage."
