# config/ontology/edges/in_environment.yaml

description: Deployment targets an environment
table: gl_ci_edge

variants:
  - from_node: { type: Deployment, id: id }
    to_node: { type: Environment, id: id }
    description: "Deployment targets environment."
