# config/ontology/edges/in_group.yaml

description: Entity belongs to a group

variants:
  - from_node: { type: Milestone, id: id }
    to_node: { type: Group, id: id }
    description: "Milestone belongs to group."

  - from_node: { type: Label, id: id }
    to_node: { type: Group, id: id }
    description: "Label belongs to group."

  - from_node: { type: WorkItem, id: id }
    to_node: { type: Group, id: id }
    description: "Work item belongs to group."

denormalized_properties:
  - node: WorkItem
    property: state
    direction: source
  - node: WorkItem
    property: work_item_type
    direction: source
