description: Entity belongs to a milestone

edges:
  - from: {node: WorkItem, key: milestone_id}
    to:   {node: Milestone, key: id}
    mutable: true
  - from: {node: MergeRequest, key: milestone_id}
    to:   {node: Milestone, key: id}
    mutable: true
