description: User who merged a merge request

variants:
  - from_node: { type: User, id: id }
    to_node: { type: MergeRequest, id: id }
    fk_column: merge_user_id
    edge_tp_source: to
    description: "User merged a merge request."
