description: Vulnerability occurrence is an occurrence of a vulnerability

scope: same_namespace
edges:
  - from: {node: VulnerabilityOccurrence, key: vulnerability_id}
    to:   {node: Vulnerability, key: id}
