# config/ontology/edges/ran_by.yaml

description: Security scan was executed by a CI job
table: gl_ci_edge

variants:
  - from_node: { type: SecurityScan, id: id }
    to_node: { type: Job, id: id }
    description: "Security scan was run by job."
