# config/ontology/edges/resolved_by.yaml

description: User who resolved a vulnerability

variants:
  - from_node: { type: User, id: id }
    to_node: { type: Vulnerability, id: id }
    fk_column: resolved_by_id
    edge_tp_source: to
    description: "User resolved vulnerability."
