# config/ontology/edges/resolved_by.yaml

description: User who resolved an entity

variants:
  - from_node: { type: User, id: id }
    to_node: { type: Vulnerability, id: id }
    description: "User resolved vulnerability."
