# config/ontology/edges/reviewer.yaml

description: Review assignment relationship between users and merge requests

variants:
  - from_node: { type: User, id: id }
    to_node: { type: MergeRequest, id: id }
    description: "User is a reviewer of merge request."
