# config/ontology/edges/scans.yaml

description: VulnerabilityScanner scans a project for security vulnerabilities

variants:
  - from_node: { type: VulnerabilityScanner, id: id }
    to_node: { type: Project, id: id }
    fk_column: project_id
    description: "VulnerabilityScanner scans project."

sources:
  - node: VulnerabilityScanner
    from: {type: VulnerabilityScanner, id: id}
    to: {type: Project, id: project_id}
