description: Trigger relationship between entities

table: gl_ci_edge
edges:
  - from: {node: User, key: id}
    to:   {node: Pipeline, key: user_id}
    scope: prune_to_target
  - from: {node: MergeRequest, key: id}
    to:   {node: Pipeline, key: merge_request_id}
    scope: same_namespace
  - from: {node: User, key: id}
    to:   {node: Job, key: user_id}
    scope: prune_to_target
