#[global_allocator]
static GLOBAL: mimalloc::MiMalloc = mimalloc::MiMalloc;

mod content;
mod local_pipeline;
mod workspace;

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use ontology::Ontology;
use query_engine::compiler::SecurityContext;
use query_engine::formatters::{self, ResultFormatter};
use serde::Serialize;
use serde_json::Value;
use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;
use tracing::{Level, info};
use tracing_subscriber::fmt::format::FmtSpan;

/// Generate the full DuckDB DDL (graph tables + manifest) from the ontology.
fn generate_local_ddl(ontology: &Ontology) -> String {
    let schema_version = include_str!("../../../config/SCHEMA_VERSION").trim();
    let tables = query_engine::compiler::generate_local_tables(ontology);
    let mut ddl = format!(
        "-- SCHEMA_VERSION={schema_version} [AUTOGENERATED — DO NOT EDIT MANUALLY]\n\
         -- Regenerate with: mise schema:generate:ddl:local\n\n"
    );
    for t in &tables {
        ddl.push_str(&format!(
            "{};\n\n",
            query_engine::compiler::emit_duckdb_create_table(t)
        ));
    }
    ddl.push_str(duckdb_client::MANIFEST_DDL);
    ddl
}

#[derive(Debug, Clone, Copy, Default, clap::ValueEnum)]
enum OutputFormat {
    #[default]
    Pretty,
    Json,
}

#[derive(Serialize)]
struct IndexOutput {
    repository: String,
    path: String,
    time_seconds: f64,
    graph: GraphStats,
    processing: ProcessingStats,
    #[serde(skip_serializing_if = "Option::is_none")]
    database_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    detailed: Option<DetailedStats>,
}

#[derive(Serialize)]
struct GraphStats {
    directories: usize,
    files: usize,
    definitions: usize,
    imported_symbols: usize,
    relationships: usize,
}

#[derive(Serialize)]
struct ProcessingStats {
    skipped_files: usize,
    errored_files: usize,
}

#[derive(Debug, Clone, Default)]
struct IndexGraphStats {
    directories: usize,
    files: usize,
    definitions: usize,
    imported_symbols: usize,
    relationships: usize,
    relationship_types: HashMap<String, usize>,
    definition_types: HashMap<String, usize>,
}

struct IndexRunResult {
    total_processing_time: Duration,
    skipped_files: Vec<code_graph::v2::SkippedFile>,
    faulted_files: Vec<code_graph::v2::FaultedFile>,
    graph_stats: IndexGraphStats,
    database_path: Option<String>,
}

#[derive(Serialize)]
struct DetailedStats {
    #[serde(skip_serializing_if = "Vec::is_empty")]
    skipped_files: Vec<SkippedFile>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    errored_files: Vec<ErroredFile>,
    relationship_types: HashMap<String, usize>,
    definition_types: HashMap<String, usize>,
}

#[derive(Serialize)]
struct SkippedFile {
    path: String,
    reason: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    detail: String,
}

#[derive(Serialize)]
struct ErroredFile {
    path: String,
    kind: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    detail: String,
}

#[derive(Parser)]
#[command(name = "orbit")]
#[command(about = "Orbit - local code indexing and query CLI")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Index a code repository and output graph statistics as JSON
    Index {
        /// Path to the repository to index
        #[arg(value_name = "PATH")]
        path: PathBuf,

        /// Number of worker threads (0 = auto-detect based on CPU cores)
        #[arg(short, long, default_value = "0")]
        threads: usize,

        /// Include detailed statistics in output
        #[arg(short, long)]
        stats: bool,

        /// Verbose logging to stderr
        #[arg(short, long)]
        verbose: bool,
    },
    /// Query the local DuckDB graph (~/.orbit/graph.duckdb)
    Query {
        /// JSON query payload
        #[arg(value_name = "JSON")]
        json: String,

        /// Path to ontology directory (default: config/ontology)
        #[arg(long, short)]
        ontology: Option<PathBuf>,

        /// Output raw JSON graph (default is LLM-friendly text)
        #[arg(long)]
        raw: bool,
    },
    /// Compile a query to SQL without executing it
    Compile {
        /// JSON query payload
        #[arg(value_name = "JSON")]
        json: String,

        /// Traversal paths for security context (e.g., "1/2/3/"). Org ID is parsed from the first segment.
        #[arg(long, short, num_args = 1..)]
        traversal_paths: Vec<String>,

        /// Path to ontology directory (default: config/ontology)
        #[arg(long, short)]
        ontology: Option<PathBuf>,

        /// Output format: pretty (default) or json
        #[arg(long, default_value = "pretty")]
        format: OutputFormat,

        /// Compile for local DuckDB instead of ClickHouse
        #[arg(long)]
        local: bool,
    },
    /// Describe the graph schema. Requires --ontology or --query.
    Schema {
        /// Show the graph ontology (entities, edges, properties).
        #[arg(long, conflicts_with = "query")]
        ontology: bool,

        /// Show the query DSL schema (how to write queries).
        #[arg(long, conflicts_with = "ontology")]
        query: bool,

        /// Expand one or more entities to show their properties and edges.
        /// Pass `*` to expand every entity. Only valid with --ontology.
        #[arg(long, short = 'e', value_name = "NODE", num_args = 1.., requires = "ontology")]
        expand: Vec<String>,

        /// Include the full server ontology (debugging aid). Default is
        /// restricted to entities present in the local DuckDB.
        /// Only valid with --ontology.
        #[arg(long, requires = "ontology")]
        all: bool,

        /// Path to ontology directory (default: embedded).
        /// Only valid with --ontology.
        #[arg(long, short = 'p', value_name = "PATH", requires = "ontology")]
        ontology_path: Option<PathBuf>,

        /// Emit JSON instead of the default LLM-friendly TOON format.
        #[arg(long)]
        raw: bool,
    },
    /// Maintainer-only tools (DDL generation, etc.)
    Debug {
        #[command(subcommand)]
        command: DebugCommands,
    },
}

#[derive(Subcommand)]
enum DebugCommands {
    /// Generate ClickHouse DDL from the ontology
    Ddl {
        /// Path to ontology directory (default: embedded)
        #[arg(long, short)]
        ontology: Option<PathBuf>,

        /// Table prefix (e.g., "v1_" for schema version 1)
        #[arg(long, short, default_value = "")]
        prefix: String,

        /// Diff generated DDL against an existing .sql file
        #[arg(long, short)]
        diff: Option<PathBuf>,
    },
    /// Generate DuckDB DDL from the ontology (local graph tables + manifest)
    DdlLocal {
        /// Path to ontology directory (default: embedded)
        #[arg(long, short)]
        ontology: Option<PathBuf>,
    },
}

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Index {
            path,
            threads,
            stats,
            verbose,
        } => {
            let level = if verbose { Level::DEBUG } else { Level::WARN };
            let subscriber = tracing_subscriber::fmt()
                .with_max_level(level)
                .with_target(verbose)
                .with_level(verbose)
                .with_ansi(true)
                .without_time()
                .with_span_events(if verbose {
                    FmtSpan::CLOSE
                } else {
                    FmtSpan::NONE
                })
                .with_writer(std::io::stderr)
                .finish();
            tracing::subscriber::set_global_default(subscriber)
                .expect("setting default subscriber failed");

            run_index(path, threads, stats).await
        }
        Commands::Query {
            json,
            ontology,
            raw,
        } => {
            let output = run_local_query(json, ontology)?;
            if raw {
                let formatted = formatters::GraphFormatter.format(&output);
                println!("{}", serde_json::to_string(&formatted)?);
            } else {
                let formatted = formatters::GoonFormatter.format(&output);
                println!("{}", serde_json::to_string_pretty(&formatted)?);
            }
            Ok(())
        }
        Commands::Compile {
            json,
            traversal_paths,
            ontology,
            format,
            local,
        } => run_compile(json, traversal_paths, ontology, format, local),
        Commands::Schema {
            ontology,
            query,
            expand,
            all,
            ontology_path,
            raw,
        } => {
            if query {
                run_query_dsl_schema(raw)
            } else if ontology {
                run_schema_introspect(expand, raw, all, ontology_path)
            } else {
                anyhow::bail!("specify --ontology or --query (see: orbit schema --help)")
            }
        }
        Commands::Debug { command } => match command {
            DebugCommands::Ddl {
                ontology,
                prefix,
                diff,
            } => run_ddl(ontology, prefix, diff),
            DebugCommands::DdlLocal { ontology } => {
                let ont = match ontology {
                    Some(path) => {
                        Ontology::load_from_dir(&path).context("failed to load ontology")?
                    }
                    None => {
                        Ontology::load_embedded().context("failed to load embedded ontology")?
                    }
                };
                print!("{}", generate_local_ddl(&ont));
                Ok(())
            }
        },
    }
}

fn run_schema_introspect(
    expand: Vec<String>,
    raw: bool,
    all: bool,
    ontology_path: Option<PathBuf>,
) -> Result<()> {
    let ont = match ontology_path {
        Some(path) => Ontology::load_from_dir(&path).context("failed to load ontology")?,
        None => Ontology::load_embedded().context("failed to load embedded ontology")?,
    };

    let scope = if all {
        ontology::introspection::IntrospectionScope::All
    } else {
        ontology::introspection::IntrospectionScope::Local
    };

    let response = ontology::introspection::build_schema_response(&ont, scope, &expand);

    if raw {
        println!("{}", serde_json::to_string_pretty(&response)?);
    } else {
        let toon = toon_format::encode(&response, &toon_format::EncodeOptions::default())
            .map_err(|e| anyhow::anyhow!("failed to encode TOON: {e}"))?;
        println!("{toon}");
    }
    Ok(())
}

fn run_query_dsl_schema(raw: bool) -> Result<()> {
    let condensed =
        ontology::query_dsl::condensed_query_schema().map_err(|e| anyhow::anyhow!("{e}"))?;

    if raw {
        println!("{}", serde_json::to_string_pretty(&condensed)?);
    } else {
        let toon = toon_format::encode(&condensed, &toon_format::EncodeOptions::default())
            .map_err(|e| anyhow::anyhow!("failed to encode TOON: {e}"))?;
        println!("{toon}");
    }
    Ok(())
}

fn run_ddl(ontology_path: Option<PathBuf>, prefix: String, diff: Option<PathBuf>) -> Result<()> {
    let ont = match ontology_path {
        Some(path) => Ontology::load_from_dir(&path).context("failed to load ontology")?,
        None => Ontology::load_embedded().context("failed to load embedded ontology")?,
    };

    let tables = query_engine::compiler::generate_graph_tables(&ont);
    let generated: Vec<String> = tables
        .iter()
        .map(|t| {
            let t = if prefix.is_empty() {
                t.clone()
            } else {
                t.clone().with_prefix(&prefix)
            };
            format!("{};\n", query_engine::compiler::emit_create_table(&t))
        })
        .collect();

    let schema_version = include_str!("../../../config/SCHEMA_VERSION").trim();

    match diff {
        Some(path) => run_schema_diff(&generated, &path),
        None => {
            println!("-- SCHEMA_VERSION={schema_version} [AUTOGENERATED — DO NOT EDIT MANUALLY]");
            println!("-- Regenerate with: mise schema:generate:ddl");
            println!();
            for stmt in &generated {
                println!("{stmt}");
            }
            Ok(())
        }
    }
}

/// Extracts `CREATE TABLE IF NOT EXISTS` statements from SQL, keyed by table name.
/// Splits on top-level semicolons and extracts the table name from each statement.
fn extract_tables_from_sql(sql: &str) -> std::collections::BTreeMap<String, String> {
    let mut tables = std::collections::BTreeMap::new();
    let mut depth = 0i32;
    let mut in_string = false;
    let mut start = 0;

    for (i, c) in sql.char_indices() {
        match c {
            '\'' if !in_string || (i > 0 && sql.as_bytes()[i - 1] != b'\\') => {
                in_string = !in_string;
            }
            '(' if !in_string => depth += 1,
            ')' if !in_string => depth -= 1,
            ';' if !in_string && depth == 0 => {
                let stmt = sql[start..=i].trim();
                if let Some(name) = extract_create_table_name(stmt) {
                    tables.insert(name, strip_leading_comments(stmt).to_string());
                }
                start = i + 1;
            }
            _ => {}
        }
    }

    tables
}

/// Strips leading SQL comments and blank lines from a statement.
fn strip_leading_comments(stmt: &str) -> &str {
    let mut start = 0;
    for line in stmt.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with("--") {
            start += line.len() + 1; // +1 for newline
        } else {
            break;
        }
    }
    if start >= stmt.len() {
        stmt
    } else {
        &stmt[start..]
    }
}

/// Extracts the table name from a `CREATE TABLE IF NOT EXISTS <name>` statement.
fn extract_create_table_name(stmt: &str) -> Option<String> {
    let upper = stmt.to_uppercase();
    let marker = "CREATE TABLE IF NOT EXISTS ";
    let pos = upper.find(marker)?;
    let after = &stmt[pos + marker.len()..];
    let name = after
        .split(|c: char| c.is_whitespace() || c == '(')
        .next()?;
    if name.is_empty() {
        None
    } else {
        Some(name.to_string())
    }
}

fn run_schema_diff(generated_stmts: &[String], sql_path: &PathBuf) -> Result<()> {
    let existing_sql = std::fs::read_to_string(sql_path)
        .with_context(|| format!("failed to read {}", sql_path.display()))?;

    let existing = extract_tables_from_sql(&existing_sql);
    let generated_sql = generated_stmts.join("\n");
    let generated = extract_tables_from_sql(&generated_sql);

    let all_names: std::collections::BTreeSet<&str> = existing
        .keys()
        .chain(generated.keys())
        .map(|s| s.as_str())
        .collect();

    let mut ok = 0u32;
    let mut diffs = 0u32;
    let mut missing = 0u32;
    let mut extra = 0u32;

    for name in &all_names {
        // Skip control tables that aren't generated from ontology
        if *name == "gkg_schema_version" {
            continue;
        }

        match (existing.get(*name), generated.get(*name)) {
            (Some(_), None) => {
                eprintln!("MISSING from generated: {name}");
                missing += 1;
            }
            (None, Some(_)) => {
                eprintln!("EXTRA in generated: {name}");
                extra += 1;
            }
            (Some(exp), Some(got)) => {
                if exp.trim() == got.trim() {
                    ok += 1;
                } else {
                    diffs += 1;
                    eprintln!("DIFF: {name}");
                    let exp_lines: Vec<&str> = exp.lines().collect();
                    let got_lines: Vec<&str> = got.lines().collect();
                    let max = exp_lines.len().max(got_lines.len());
                    for i in 0..max {
                        let e = exp_lines.get(i).map(|s| s.trim()).unwrap_or("<missing>");
                        let g = got_lines.get(i).map(|s| s.trim()).unwrap_or("<missing>");
                        if e != g {
                            eprintln!("  L{i}: exp: {e}");
                            eprintln!("  L{i}: got: {g}");
                        }
                    }
                }
            }
            (None, None) => unreachable!(),
        }
    }

    eprintln!();
    eprintln!("{ok} OK, {diffs} DIFF, {missing} MISSING, {extra} EXTRA");

    if diffs > 0 || missing > 0 || extra > 0 {
        anyhow::bail!("DDL mismatch: {diffs} tables differ, {missing} missing, {extra} extra");
    }

    eprintln!("All tables match.");
    Ok(())
}

async fn run_index(path: PathBuf, threads: usize, show_stats: bool) -> Result<()> {
    let store = workspace::Workspace::open_default()?;
    let repos = store.resolve_repos(&path)?;

    if repos.is_empty() {
        info!("No git repositories found in {}", path.display());
        return Ok(());
    }

    let ontology_dir = std::path::PathBuf::from(env!("ONTOLOGY_DIR"));
    let ontology = Ontology::load_from_dir(&ontology_dir).context("failed to load ontology")?;

    // Ensure schema exists, then drop the connection so we don't hold
    // the write lock during parsing.
    {
        let db_path = store.db_path();
        let client =
            duckdb_client::DuckDbClient::open(&db_path).context("failed to open DuckDB")?;
        let ddl = generate_local_ddl(&ontology);
        client
            .initialize_schema(&ddl)
            .context("failed to create schema")?;
    }

    let pipeline_config = code_graph::v2::PipelineConfig {
        max_file_size: 5_000_000,
        respect_gitignore: true,
        worker_threads: threads,
        ..Default::default()
    };

    let mut failed = 0usize;

    for repo_path in &repos {
        let git = match workspace::git_info(repo_path) {
            Ok(g) => g,
            Err(e) => {
                tracing::error!("skipping {}: {e:#}", repo_path.display());
                failed += 1;
                continue;
            }
        };
        let key = git.repo_path.to_string_lossy().to_string();
        let db_path = store.db_path();

        info!(
            "Indexing repository at: {} (branch: {}, commit: {})",
            key,
            git.branch,
            git.commit_sha.get(..8).unwrap_or(&git.commit_sha)
        );

        // Mark as indexing before we start parsing.
        {
            let client =
                duckdb_client::DuckDbClient::open(&db_path).context("failed to open DuckDB")?;
            workspace::set_status(
                &client,
                &key,
                git.project_id,
                workspace::RepoStatus::Indexing,
                None,
                Some(&git),
            )?;
        }

        let result = index_repo(&git, &store, &ontology, pipeline_config.clone()).await;
        match result {
            Ok(result) => {
                let repo_name = git
                    .repo_path
                    .file_name()
                    .map(|n| n.to_string_lossy().to_string())
                    .unwrap_or_else(|| "repository".to_string());
                let mut output = build_index_output(&repo_name, &key, &result, show_stats);
                output.database_path = Some(db_path.display().to_string());
                println!("{}", serde_json::to_string_pretty(&output)?);
            }
            Err(e) => {
                tracing::error!("failed to index {key}: {e:#}");
                failed += 1;
                if let Ok(client) = duckdb_client::DuckDbClient::open(&db_path)
                    && let Err(manifest_err) = workspace::set_status(
                        &client,
                        &key,
                        git.project_id,
                        workspace::RepoStatus::Error,
                        Some(&e.to_string()),
                        None,
                    )
                {
                    tracing::warn!("failed to record error status in manifest: {manifest_err}");
                }
            }
        }
    }

    if failed > 0 {
        anyhow::bail!("{failed} of {} repositories failed to index", repos.len());
    }
    Ok(())
}

async fn index_repo(
    git: &workspace::GitInfo,
    store: &workspace::Workspace,
    ontology: &Ontology,
    mut pipeline_config: code_graph::v2::PipelineConfig,
) -> Result<IndexRunResult> {
    let key = git.repo_path.to_string_lossy().to_string();
    let root_path = key.clone();
    let start_time = std::time::Instant::now();

    let tracer = code_graph::v2::trace::Tracer::new(false);
    pipeline_config.file_inventory = Some(git_file_inventory(&git.repo_path)?);

    let db_path = store.db_path();
    let client =
        duckdb_client::DuckDbClient::open(&db_path).context("failed to open DuckDB for writing")?;

    let node_tables: Vec<String> = ontology
        .local_entity_names()
        .iter()
        .map(|name| {
            ontology
                .get_node(name)
                .expect("local entity must exist")
                .destination_table
                .clone()
        })
        .collect();
    let edge_table = ontology
        .local_edge_table_name()
        .context("local_db.edge_table.name must be configured")?;

    client
        .delete_project(git.project_id, &node_tables, edge_table)
        .context("failed to clear existing project data")?;

    let converter: std::sync::Arc<dyn code_graph::v2::GraphConverter> =
        std::sync::Arc::new(duckdb_client::DuckDbConverter {
            project_id: git.project_id,
            branch: git.branch.clone(),
            commit_sha: git.commit_sha.clone(),
            ontology: std::sync::Arc::new(ontology.clone()),
        });
    let sink: std::sync::Arc<dyn code_graph::v2::BatchSink> =
        std::sync::Arc::new(duckdb_client::DuckDbSink::new(client));

    let v2_result = code_graph::v2::Pipeline::run_with_tracer(
        std::path::Path::new(&root_path),
        pipeline_config.clone(),
        tracer,
        converter,
        sink,
    );

    if !v2_result.errors.is_empty() {
        for err in &v2_result.errors {
            tracing::warn!("pipeline error: {} ({})", err.error, err.file_path);
        }
    }
    // Re-open for workspace status (client was moved into sink)
    let client =
        duckdb_client::DuckDbClient::open(&db_path).context("failed to open DuckDB for status")?;
    workspace::set_status(
        &client,
        &key,
        git.project_id,
        workspace::RepoStatus::Indexed,
        None,
        Some(git),
    )?;

    for err in &v2_result.errors {
        tracing::warn!(stage = err.stage, error = %err.error, "task-level pipeline error");
    }

    Ok(IndexRunResult {
        total_processing_time: start_time.elapsed(),
        skipped_files: v2_result.skipped,
        faulted_files: v2_result.faults,
        graph_stats: IndexGraphStats {
            directories: v2_result.stats.directories_indexed,
            files: v2_result.stats.files_indexed,
            definitions: v2_result.stats.definitions_count,
            imported_symbols: v2_result.stats.imports_count,
            relationships: v2_result.stats.edges_count,
            relationship_types: HashMap::new(),
            definition_types: HashMap::new(),
        },
        database_path: Some(db_path.display().to_string()),
    })
}

fn git_file_inventory(
    repo_path: &std::path::Path,
) -> Result<Arc<[code_graph::v2::FileInventoryEntry]>> {
    let output = std::process::Command::new("git")
        .args([
            "-C",
            repo_path.to_str().context("repository path is not UTF-8")?,
            "ls-files",
            "-z",
            "--cached",
            "--others",
            "--exclude-standard",
        ])
        .output()
        .with_context(|| format!("failed to list git tree files in {}", repo_path.display()))?;
    if !output.status.success() {
        anyhow::bail!(
            "git ls-files failed in {}: {}",
            repo_path.display(),
            String::from_utf8_lossy(&output.stderr)
        );
    }

    let entries: Vec<_> = output
        .stdout
        .split(|b| *b == 0)
        .filter(|path| !path.is_empty())
        .map(|path| {
            let path = String::from_utf8_lossy(path).to_string();
            let size = std::fs::symlink_metadata(repo_path.join(&path))
                .ok()
                .map_or(0, |metadata| metadata.len());
            code_graph::v2::FileInventoryEntry { path, size }
        })
        .collect();
    Ok(Arc::from(entries))
}

fn build_index_output(
    repo_name: &str,
    path: &str,
    result: &IndexRunResult,
    show_stats: bool,
) -> IndexOutput {
    let stats = &result.graph_stats;
    let graph = GraphStats {
        directories: stats.directories,
        files: stats.files,
        definitions: stats.definitions,
        imported_symbols: stats.imported_symbols,
        relationships: stats.relationships,
    };

    let detailed = show_stats.then(|| DetailedStats {
        skipped_files: result
            .skipped_files
            .iter()
            .map(|s| SkippedFile {
                path: s.path.clone(),
                reason: s.kind.as_metric_label().to_string(),
                detail: s.detail.clone(),
            })
            .collect(),
        errored_files: result
            .faulted_files
            .iter()
            .map(|f| ErroredFile {
                path: f.path.clone(),
                kind: f.kind.as_metric_label().to_string(),
                detail: f.detail.clone(),
            })
            .collect(),
        relationship_types: stats.relationship_types.clone(),
        definition_types: stats.definition_types.clone(),
    });

    IndexOutput {
        repository: repo_name.to_string(),
        path: path.to_string(),
        time_seconds: result.total_processing_time.as_secs_f64(),
        graph,
        processing: ProcessingStats {
            skipped_files: result.skipped_files.len(),
            errored_files: result.faulted_files.len(),
        },
        database_path: result.database_path.clone(),
        detailed,
    }
}

#[derive(Serialize)]
struct CompileResult {
    input: Value,
    sql: String,
    params: HashMap<String, Value>,
    rendered_sql: String,
}

/// Parse a single query JSON and load the ontology.
fn parse_query_input(
    json_input: &str,
    ontology_path: Option<PathBuf>,
) -> Result<(Value, Ontology)> {
    let ontology_dir = ontology_path.unwrap_or_else(|| PathBuf::from(env!("ONTOLOGY_DIR")));
    let ontology = Ontology::load_from_dir(&ontology_dir)
        .with_context(|| format!("failed to load ontology from {}", ontology_dir.display()))?;

    let value: Value = serde_json::from_str(json_input).context("failed to parse JSON input")?;
    if value.get("query_type").is_none() {
        anyhow::bail!("JSON must contain a \"query_type\" field");
    }

    Ok((value, ontology))
}

fn run_local_query(
    json_input: String,
    ontology_path: Option<PathBuf>,
) -> Result<query_engine::shared::PipelineOutput> {
    let (_, ontology) = parse_query_input(&json_input, ontology_path)?;
    let ontology = Arc::new(ontology);

    let store = workspace::Workspace::open_default()?;
    let db_path = store.db_path();
    if !db_path.exists() {
        anyhow::bail!(
            "no local graph found at {}. Run `orbit index` first.",
            db_path.display()
        );
    }

    let project_roots = store.project_roots()?;

    local_pipeline::run(&json_input, ontology, &db_path, project_roots).context("query failed")
}

fn run_compile(
    json_input: String,
    traversal_paths: Vec<String>,
    ontology_path: Option<PathBuf>,
    format: OutputFormat,
    local: bool,
) -> Result<()> {
    let (input, ontology) = parse_query_input(&json_input, ontology_path)?;

    let security_ctx = if local {
        None
    } else {
        let first_path = traversal_paths
            .first()
            .context("--traversal-paths required for server compilation")?;
        let org_id: i64 = first_path
            .split('/')
            .next()
            .context("traversal path is empty")?
            .parse()
            .context("first segment of traversal path must be a valid org ID")?;
        Some(
            SecurityContext::new(org_id, traversal_paths)
                .map_err(|e| anyhow::anyhow!("invalid security context: {}", e))?,
        )
    };

    let compile_result = if local {
        query_engine::compiler::compile_local(&json_input, &ontology)
    } else {
        query_engine::compiler::compile(&json_input, &ontology, security_ctx.as_ref().unwrap())
    };

    match compile_result {
        Ok(result) => {
            let rendered_sql = result.base.render();
            let output = CompileResult {
                input,
                sql: result.base.sql,
                params: result
                    .base
                    .params
                    .into_iter()
                    .map(|(k, v)| (k, v.value))
                    .collect(),
                rendered_sql,
            };

            match format {
                OutputFormat::Json => {
                    println!("{}", serde_json::to_string_pretty(&output)?);
                }
                OutputFormat::Pretty => {
                    println!("**SQL:**\n```sql\n{}\n```\n", output.sql);
                    if !output.params.is_empty() {
                        println!(
                            "**Params:**\n```json\n{}\n```\n",
                            serde_json::to_string_pretty(&output.params)?
                        );
                    }
                    println!("**Rendered SQL:**\n```sql\n{}\n```", output.rendered_sql);
                }
            }
        }
        Err(e) => {
            anyhow::bail!("compilation failed: {e}");
        }
    }

    Ok(())
}
