[package]
name = "orbit-query"
description = "Orbit query frontend based on openCypher 9 syntax, with Orbit-specific restrictions and extensions"
version.workspace = true
edition = "2024"
publish = false

[dependencies]
compiler = { path = "../compiler" }
pest.workspace = true
pest_derive.workspace = true
serde_json.workspace = true

[lints]
workspace = true
