{{- $headless := include "clickhouse.headless" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  low_memory_server.xml: |
    <?xml version="1.0"?>
    <clickhouse>
        <mark_cache_size>268435456</mark_cache_size>
        <uncompressed_cache_size>268435456</uncompressed_cache_size>

        <asynchronous_metric_log>
            <flush_interval_milliseconds>60000</flush_interval_milliseconds>
        </asynchronous_metric_log>
        <metric_log>
            <flush_interval_milliseconds>60000</flush_interval_milliseconds>
        </metric_log>

        <merge_tree>
            <merge_max_block_size>1024</merge_max_block_size>
        </merge_tree>
    </clickhouse>
  low_memory_users.xml: |
    <?xml version="1.0"?>
    <clickhouse>
        <profiles>
            <default>
                <max_threads>2</max_threads>
                <max_block_size>8192</max_block_size>
                <max_download_threads>1</max_download_threads>
                <input_format_parallel_parsing>0</input_format_parallel_parsing>
                <output_format_parallel_formatting>0</output_format_parallel_formatting>
            </default>
        </profiles>
    </clickhouse>
  {{- if include "clickhouse.replicated" . }}
  cluster.xml: |
    <?xml version="1.0"?>
    <clickhouse>
        <interserver_http_host from_env="INTERSERVER_HOST"/>
        <keeper_server>
            <tcp_port>9181</tcp_port>
            <server_id from_env="KEEPER_SERVER_ID"/>
            <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
            <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
            <raft_configuration>
                {{- range $i := until (int .Values.replicas) }}
                <server>
                    <id>{{ $i }}</id>
                    <hostname>{{ $.Release.Name }}-{{ $i }}.{{ $headless }}</hostname>
                    <port>9234</port>
                </server>
                {{- end }}
            </raft_configuration>
        </keeper_server>
        <zookeeper>
            {{- range $i := until (int .Values.replicas) }}
            <node>
                <host>{{ $.Release.Name }}-{{ $i }}.{{ $headless }}</host>
                <port>9181</port>
            </node>
            {{- end }}
        </zookeeper>
        <remote_servers replace="replace">
            <default>
                <shard>
                    <internal_replication>true</internal_replication>
                    {{- range $i := until (int .Values.replicas) }}
                    <replica>
                        <host>{{ $.Release.Name }}-{{ $i }}.{{ $headless }}</host>
                        <port>9000</port>
                    </replica>
                    {{- end }}
                </shard>
            </default>
        </remote_servers>
        <macros>
            <cluster>default</cluster>
            <shard>01</shard>
            <replica from_env="POD_NAME"/>
        </macros>
        <user_directories replace="replace">
            <users_xml>
                <path>users.xml</path>
            </users_xml>
            <replicated>
                <zookeeper_path>/clickhouse/access</zookeeper_path>
            </replicated>
        </user_directories>
    </clickhouse>
  {{- end }}
