apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-initdb
data:
  00-create-databases.sql: |
    CREATE DATABASE IF NOT EXISTS datalake;
    CREATE DATABASE IF NOT EXISTS gkg;
    CREATE DATABASE IF NOT EXISTS test;

  01-create-users.sql: |
    CREATE USER IF NOT EXISTS siphon IDENTIFIED BY {{ .Values.users.siphon.password | squote }};
    CREATE USER IF NOT EXISTS gkg_siphon_reader IDENTIFIED BY {{ .Values.users.gkg_siphon_reader.password | squote }};
    CREATE USER IF NOT EXISTS gkg_writer IDENTIFIED BY {{ .Values.users.gkg_writer.password | squote }};
    CREATE USER IF NOT EXISTS gkg_reader IDENTIFIED BY {{ .Values.users.gkg_reader.password | squote }};
    CREATE USER IF NOT EXISTS gitlab IDENTIFIED BY {{ .Values.users.gitlab.password | squote }};

  02-grants.sql: |
    CREATE ROLE IF NOT EXISTS gkg_app;
    CREATE ROLE IF NOT EXISTS gkg_reader_app;
    CREATE ROLE IF NOT EXISTS gkg_siphon_reader_app;

    GRANT SELECT, INSERT, ALTER, CREATE, DROP, TRUNCATE, OPTIMIZE, dictGet ON gkg.* TO gkg_app;
    GRANT SELECT ON information_schema.* TO gkg_app;
    GRANT SELECT ON system.tables TO gkg_app;
    GRANT SELECT ON system.parts TO gkg_app;

    GRANT SELECT, dictGet ON gkg.* TO gkg_reader_app;
    GRANT SELECT ON system.query_log TO gkg_reader_app;
    GRANT SELECT ON system.dictionaries TO gkg_reader_app;

    GRANT SELECT, dictGet ON datalake.* TO gkg_siphon_reader_app;

    GRANT gkg_app TO gkg_writer;
    GRANT gkg_reader_app TO gkg_reader;
    GRANT gkg_siphon_reader_app TO gkg_siphon_reader;

    SET DEFAULT ROLE gkg_app TO gkg_writer;
    SET DEFAULT ROLE gkg_reader_app TO gkg_reader;
    SET DEFAULT ROLE gkg_siphon_reader_app TO gkg_siphon_reader;

    GRANT ALL ON datalake.* TO siphon;
    GRANT SELECT ON system.tables TO siphon;
    GRANT SELECT ON system.columns TO siphon;

    GRANT ALL ON datalake.* TO gitlab;
    GRANT SELECT ON system.tables TO gitlab;
    GRANT SELECT ON system.columns TO gitlab;
    GRANT SELECT ON system.databases TO gitlab;
