[alias]
xtask = "run --package xtask --"

[env]
CONFIG_DIR = { value = "config", relative = true }
FIXTURES_DIR = { value = "fixtures", relative = true }
SCHEMA_DIR = { value = "config/schemas", relative = true }
ONTOLOGY_DIR = { value = "config/ontology", relative = true }
SEEDS_DIR = { value = "config/seeds", relative = true }
E2E_DIR = { value = "e2e", relative = true }
HELM_DEV_DIR = { value = "helm-dev", relative = true }
SCRIPTS_DIR = { value = "scripts", relative = true }
XTASK_DIR = { value = "crates/xtask", relative = true }
GKG_SERVER_SCHEMAS_DIR = { value = "crates/gkg-server/schemas", relative = true }
