-- SCHEMA_VERSION=93 [AUTOGENERATED — DO NOT EDIT MANUALLY]
-- Regenerate with: mise schema:generate:ddl
-- Persistent objects: created once at boot, never version-prefixed or GCed.

CREATE TABLE IF NOT EXISTS namespace_storage_snapshot (
    snapshot_date Date32,
    schema_version Int64,
    logical_table String,
    top_level_namespace String,
    compressed_bytes Int64
) ENGINE = ReplacingMergeTree
ORDER BY (logical_table, top_level_namespace, snapshot_date)
TTL snapshot_date + INTERVAL 400 DAY
SETTINGS allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS code_stale_snapshots (
    traversal_path String CODEC(ZSTD(1)),
    project_id Int64 CODEC(ZSTD(1)),
    branch String CODEC(ZSTD(1)),
    stale_version DateTime64(6, 'UTC') CODEC(Delta(8), ZSTD(1)),
    retired_at DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(Delta(8), ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(Delta(8), ZSTD(1)),
    _deleted Bool DEFAULT false
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, project_id, branch, stale_version)
TTL retired_at + INTERVAL 30 DAY
SETTINGS allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS stale_rows (
    table_name String CODEC(ZSTD(1)),
    row_key String CODEC(ZSTD(1)),
    stale_version DateTime64(6, 'UTC') CODEC(Delta(8), ZSTD(1)),
    retired_at DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(Delta(8), ZSTD(1))
) ENGINE = MergeTree
ORDER BY (table_name, retired_at, row_key)
TTL retired_at + INTERVAL 30 DAY
SETTINGS allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS stale_reclaim_marks (
    ledger String,
    phase String,
    table_name String,
    reclaimed_through DateTime64(6, 'UTC'),
    reclaimed_through_key String DEFAULT '',
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(Delta(8), ZSTD(1)),
    _deleted Bool DEFAULT false
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (ledger, phase, table_name)
SETTINGS allow_experimental_replacing_merge_with_cleanup = 1;

