-- SCHEMA_VERSION=63 [AUTOGENERATED — DO NOT EDIT MANUALLY]
-- Regenerate with: mise schema:generate:ddl

CREATE TABLE IF NOT EXISTS checkpoint (
    key String CODEC(ZSTD(1)),
    watermark DateTime64(6, 'UTC') CODEC(Delta(8), ZSTD(1)),
    cursor_values String DEFAULT '' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (key)
SETTINGS allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS namespace_deletion_schedule (
    namespace_id Int64 CODEC(ZSTD(1)),
    traversal_path String CODEC(ZSTD(1)),
    scheduled_deletion_date DateTime64(6, 'UTC') CODEC(Delta(8), ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (namespace_id, traversal_path)
SETTINGS allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS code_indexing_checkpoint (
    traversal_path String CODEC(ZSTD(1)),
    project_id Int64 CODEC(ZSTD(1)),
    branch String CODEC(ZSTD(1)),
    last_task_id Int64 CODEC(ZSTD(1)),
    last_commit String DEFAULT '' CODEC(ZSTD(1)),
    indexed_at DateTime64(6, 'UTC') CODEC(Delta(8), ZSTD(1)),
    _version UInt64,
    _deleted Bool DEFAULT false
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, project_id, branch)
SETTINGS allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_branch (
    id Int64 CODEC(Delta(8), LZ4),
    traversal_path String CODEC(ZSTD(1)),
    project_id Int64 CODEC(Delta(8), LZ4),
    name String CODEC(ZSTD(1)),
    is_default Bool DEFAULT true,
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_name_ngram name TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, project_id, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_container_repository (
    id Int64 CODEC(Delta(8), LZ4),
    name String DEFAULT '' CODEC(ZSTD(1)),
    status LowCardinality(String) DEFAULT '' CODEC(LZ4),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    project_id Int64 CODEC(Delta(8), LZ4),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_name name TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_status status TYPE set(4) GRANULARITY 2,
    INDEX idx_created_at created_at TYPE minmax GRANULARITY 1,
    INDEX idx_updated_at updated_at TYPE minmax GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_definition (
    id Int64 CODEC(Delta(8), LZ4),
    traversal_path String CODEC(ZSTD(1)),
    project_id Int64 CODEC(Delta(8), LZ4),
    branch String CODEC(ZSTD(1)),
    commit_sha String DEFAULT '' CODEC(ZSTD(1)),
    file_path String CODEC(ZSTD(3)),
    fqn String CODEC(ZSTD(3)),
    name String CODEC(ZSTD(1)),
    definition_type LowCardinality(String) CODEC(LZ4),
    start_line Int64 CODEC(Delta(8), LZ4),
    end_line Int64 CODEC(Delta(8), LZ4),
    start_byte Int64 CODEC(Delta(8), LZ4),
    end_byte Int64 CODEC(Delta(8), LZ4),
    start_char Int64 CODEC(Delta(8), LZ4),
    end_char Int64 CODEC(Delta(8), LZ4),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_name_ngram name TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_fqn fqn TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_fqn_ngram fqn TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_file_path file_path TYPE text(tokenizer = splitByString(['/'])) GRANULARITY 1,
    INDEX idx_file_path_ngram file_path TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_definition_type definition_type TYPE set(20) GRANULARITY 2
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, project_id, branch, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_deployment (
    id Int64 CODEC(Delta(8), LZ4),
    iid Int64 CODEC(Delta(8), LZ4),
    project_id Int64 CODEC(Delta(8), LZ4),
    ref String DEFAULT '' CODEC(ZSTD(1)),
    tag Bool DEFAULT false,
    sha String DEFAULT '' CODEC(ZSTD(1)),
    status LowCardinality(String) DEFAULT '' CODEC(LZ4),
    deployable_type String DEFAULT '' CODEC(ZSTD(1)),
    deployable_id Nullable(Int64) CODEC(Delta(8), LZ4),
    on_stop String DEFAULT '' CODEC(ZSTD(1)),
    archived Bool DEFAULT false,
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    finished_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    environment_id Int64 CODEC(Delta(8), LZ4),
    user_id Nullable(Int64) CODEC(Delta(8), LZ4),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_status status TYPE set(8) GRANULARITY 2,
    INDEX idx_archived archived TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_ref ref TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_ref_ngram ref TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_environment_id environment_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_user_id user_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_directory (
    id Int64 CODEC(Delta(8), LZ4),
    traversal_path String CODEC(ZSTD(1)),
    project_id Int64 CODEC(Delta(8), LZ4),
    branch String CODEC(ZSTD(1)),
    commit_sha String DEFAULT '' CODEC(ZSTD(1)),
    path String CODEC(ZSTD(3)),
    name String CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_name_ngram name TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_path path TYPE text(tokenizer = splitByString(['/'])) GRANULARITY 1,
    INDEX idx_path_ngram path TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, project_id, branch, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_environment (
    id Int64 CODEC(Delta(8), LZ4),
    project_id Int64 CODEC(Delta(8), LZ4),
    name String DEFAULT '' CODEC(ZSTD(1)),
    slug String DEFAULT '' CODEC(ZSTD(1)),
    external_url String DEFAULT '' CODEC(ZSTD(1)),
    environment_type String DEFAULT '' CODEC(ZSTD(1)),
    state LowCardinality(String) DEFAULT 'available' CODEC(LZ4),
    tier LowCardinality(String) DEFAULT '' CODEC(LZ4),
    auto_stop_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    auto_delete_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    auto_stop_setting LowCardinality(String) DEFAULT 'always' CODEC(LZ4),
    cluster_agent_id Nullable(Int64) CODEC(Delta(8), LZ4),
    kubernetes_namespace String DEFAULT '' CODEC(ZSTD(1)),
    flux_resource_path String DEFAULT '' CODEC(ZSTD(1)),
    description String DEFAULT '' CODEC(ZSTD(3)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    merge_request_id Nullable(Int64) CODEC(Delta(8), LZ4),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_state state TYPE set(4) GRANULARITY 2,
    INDEX idx_tier tier TYPE set(8) GRANULARITY 2,
    INDEX idx_environment_type environment_type TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_environment_type_ngram environment_type TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_name_ngram name TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_merge_request_id merge_request_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_file (
    id Int64 CODEC(Delta(8), LZ4),
    traversal_path String CODEC(ZSTD(1)),
    project_id Int64 CODEC(Delta(8), LZ4),
    branch String CODEC(ZSTD(1)),
    commit_sha String DEFAULT '' CODEC(ZSTD(1)),
    path String CODEC(ZSTD(3)),
    name String CODEC(ZSTD(1)),
    extension LowCardinality(String) CODEC(LZ4),
    language LowCardinality(String) CODEC(LZ4),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_name_ngram name TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_path path TYPE text(tokenizer = splitByString(['/'])) GRANULARITY 1,
    INDEX idx_path_ngram path TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, project_id, branch, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_finding (
    id Int64 CODEC(Delta(8), LZ4),
    uuid String DEFAULT '' CODEC(ZSTD(1)),
    name String DEFAULT '' CODEC(ZSTD(1)),
    description String DEFAULT '' CODEC(ZSTD(3)),
    solution String DEFAULT '' CODEC(ZSTD(3)),
    severity LowCardinality(String) DEFAULT '' CODEC(LZ4),
    deduplicated Bool DEFAULT false,
    overridden_uuid String DEFAULT '' CODEC(ZSTD(1)),
    project_id Int64 CODEC(Delta(8), LZ4),
    scan_id Int64 CODEC(Delta(8), LZ4),
    scanner_id Int64 CODEC(Delta(8), LZ4),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_deduplicated deduplicated TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_name_ngram name TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_description description TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_description_ngram description TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_scan_id scan_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_scanner_id scanner_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_group (
    id Int64 CODEC(Delta(8), LZ4),
    name String DEFAULT '' CODEC(ZSTD(1)),
    description String DEFAULT '' CODEC(ZSTD(3)),
    visibility_level LowCardinality(String) DEFAULT '' CODEC(LZ4),
    full_path String DEFAULT '' CODEC(ZSTD(3)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_name_ngram name TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_full_path full_path TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_description description TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_description_ngram description TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_imported_symbol (
    id Int64 CODEC(Delta(8), LZ4),
    traversal_path String CODEC(ZSTD(1)),
    project_id Int64 CODEC(Delta(8), LZ4),
    branch String CODEC(ZSTD(1)),
    commit_sha String DEFAULT '' CODEC(ZSTD(1)),
    file_path String CODEC(ZSTD(3)),
    import_type LowCardinality(String) CODEC(LZ4),
    import_path String CODEC(ZSTD(3)),
    identifier_name String DEFAULT '' CODEC(ZSTD(1)),
    identifier_alias String DEFAULT '' CODEC(ZSTD(1)),
    start_line Int64 CODEC(Delta(8), LZ4),
    end_line Int64 CODEC(Delta(8), LZ4),
    start_byte Int64 CODEC(Delta(8), LZ4),
    end_byte Int64 CODEC(Delta(8), LZ4),
    start_char Int64 CODEC(Delta(8), LZ4),
    end_char Int64 CODEC(Delta(8), LZ4),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_identifier_name identifier_name TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_file_path file_path TYPE text(tokenizer = splitByString(['/'])) GRANULARITY 1,
    INDEX idx_file_path_ngram file_path TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_import_path import_path TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_import_path_ngram import_path TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_import_type import_type TYPE set(10) GRANULARITY 2
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, project_id, branch, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_job (
    id Int64 CODEC(Delta(8), LZ4),
    name String DEFAULT '' CODEC(ZSTD(1)),
    status LowCardinality(String) DEFAULT '' CODEC(LZ4),
    ref String DEFAULT '' CODEC(ZSTD(1)),
    tag Nullable(Bool),
    allow_failure Bool DEFAULT false,
    coverage String DEFAULT '' CODEC(ZSTD(1)),
    environment String DEFAULT '' CODEC(ZSTD(1)),
    `when` LowCardinality(String) DEFAULT '' CODEC(LZ4),
    retried Nullable(Bool),
    failure_reason String DEFAULT '' CODEC(ZSTD(1)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    started_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    finished_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    queued_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    runner_id Nullable(Int64) CODEC(Delta(8), LZ4),
    timeout Nullable(Int64) CODEC(Delta(8), LZ4),
    timeout_source LowCardinality(String) DEFAULT '' CODEC(LZ4),
    exit_code Nullable(Int64) CODEC(Delta(8), LZ4),
    scheduling_type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    project_id Int64 CODEC(Delta(8), LZ4),
    user_id Nullable(Int64) CODEC(Delta(8), LZ4),
    upstream_pipeline_id Nullable(Int64) CODEC(Delta(8), LZ4),
    stage_id Nullable(Int64) CODEC(Delta(8), LZ4),
    pipeline_id Nullable(Int64) CODEC(Delta(8), LZ4),
    auto_canceled_by_id Nullable(Int64) CODEC(Delta(8), LZ4),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_status status TYPE set(16) GRANULARITY 2,
    INDEX idx_allow_failure allow_failure TYPE minmax GRANULARITY 1,
    INDEX idx_retried retried TYPE minmax GRANULARITY 1,
    INDEX idx_created_at created_at TYPE minmax GRANULARITY 1,
    INDEX idx_started_at started_at TYPE minmax GRANULARITY 1,
    INDEX idx_finished_at finished_at TYPE minmax GRANULARITY 1,
    INDEX idx_queued_at queued_at TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_name_ngram name TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_ref ref TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_ref_ngram ref TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_user_id user_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_upstream_pipeline_id upstream_pipeline_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_stage_id stage_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_pipeline_id pipeline_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_runner_id runner_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_auto_canceled_by_id auto_canceled_by_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_label (
    id Int64 CODEC(Delta(8), LZ4),
    title String DEFAULT '' CODEC(ZSTD(1)),
    description String DEFAULT '' CODEC(ZSTD(3)),
    color String DEFAULT '' CODEC(ZSTD(1)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    project_id Nullable(Int64) CODEC(Delta(8), LZ4),
    group_id Nullable(Int64) CODEC(Delta(8), LZ4),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_title title TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_title_ngram title TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_description description TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_description_ngram description TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_group_id group_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_merge_request (
    id Int64 CODEC(Delta(8), LZ4),
    iid Nullable(Int64) CODEC(Delta(8), LZ4),
    title String DEFAULT '' CODEC(ZSTD(1)),
    description String DEFAULT '' CODEC(ZSTD(3)),
    source_branch String DEFAULT '' CODEC(ZSTD(1)),
    target_branch String DEFAULT '' CODEC(ZSTD(1)),
    state LowCardinality(String) DEFAULT '' CODEC(LZ4),
    merge_status LowCardinality(String) DEFAULT 'unchecked' CODEC(LZ4),
    draft Bool DEFAULT false,
    squash Bool DEFAULT false,
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    merge_commit_sha String DEFAULT '' CODEC(ZSTD(1)),
    discussion_locked Nullable(Bool),
    prepared_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    project_id Int64 CODEC(Delta(8), LZ4),
    merged_commit_sha String DEFAULT '' CODEC(ZSTD(1)),
    squash_commit_sha String DEFAULT '' CODEC(ZSTD(1)),
    latest_build_started_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    latest_build_finished_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    first_deployed_to_production_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    merged_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    latest_closed_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    first_comment_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    first_commit_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    last_commit_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    diff_size Nullable(Int64) CODEC(Delta(8), LZ4),
    modified_paths_size Nullable(Int64) CODEC(Delta(8), LZ4),
    commits_count Nullable(Int64) CODEC(Delta(8), LZ4),
    first_approved_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    first_reassigned_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    added_lines Nullable(Int64) CODEC(Delta(8), LZ4),
    removed_lines Nullable(Int64) CODEC(Delta(8), LZ4),
    first_contribution Bool DEFAULT false,
    reviewer_first_assigned_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    author_id Nullable(Int64) CODEC(Delta(8), LZ4),
    merge_user_id Nullable(Int64) CODEC(Delta(8), LZ4),
    updated_by_id Nullable(Int64) CODEC(Delta(8), LZ4),
    last_edited_by_id Nullable(Int64) CODEC(Delta(8), LZ4),
    closed_by_id Nullable(Int64) CODEC(Delta(8), LZ4),
    milestone_id Nullable(Int64) CODEC(Delta(8), LZ4),
    source_project_id Nullable(Int64) CODEC(Delta(8), LZ4),
    head_pipeline_id Nullable(Int64) CODEC(Delta(8), LZ4),
    latest_merge_request_diff_id Nullable(Int64) CODEC(Delta(8), LZ4),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_state state TYPE set(6) GRANULARITY 2,
    INDEX idx_draft draft TYPE minmax GRANULARITY 1,
    INDEX idx_squash squash TYPE minmax GRANULARITY 1,
    INDEX idx_discussion_locked discussion_locked TYPE minmax GRANULARITY 1,
    INDEX idx_first_contribution first_contribution TYPE minmax GRANULARITY 1,
    INDEX idx_created_at created_at TYPE minmax GRANULARITY 1,
    INDEX idx_updated_at updated_at TYPE minmax GRANULARITY 1,
    INDEX idx_merged_at merged_at TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_title title TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_title_ngram title TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_description description TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_description_ngram description TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_source_branch source_branch TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_source_branch_ngram source_branch TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_target_branch target_branch TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_target_branch_ngram target_branch TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_merge_status merge_status TYPE set(8) GRANULARITY 2,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_author_id author_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_merge_user_id merge_user_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_milestone_id milestone_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_source_project_id source_project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_updated_by_id updated_by_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_last_edited_by_id last_edited_by_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_closed_by_id closed_by_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_head_pipeline_id head_pipeline_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_latest_merge_request_diff_id latest_merge_request_diff_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_merge_request_diff (
    id Int64 CODEC(Delta(8), LZ4),
    merge_request_id Int64 CODEC(Delta(8), LZ4),
    state String DEFAULT '' CODEC(ZSTD(1)),
    base_commit_sha String DEFAULT '' CODEC(ZSTD(1)),
    head_commit_sha String DEFAULT '' CODEC(ZSTD(1)),
    start_commit_sha String DEFAULT '' CODEC(ZSTD(1)),
    commits_count Nullable(Int64) CODEC(Delta(8), LZ4),
    files_count Nullable(Int64) CODEC(Delta(8), LZ4),
    project_id Int64 CODEC(Delta(8), LZ4),
    diff_type LowCardinality(String) DEFAULT 'regular' CODEC(LZ4),
    real_size String DEFAULT '' CODEC(ZSTD(1)),
    stored_externally Bool DEFAULT false,
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_merge_request_id merge_request_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_merge_request_diff_file (
    id Int64 CODEC(Delta(8), LZ4),
    merge_request_id Int64 CODEC(Delta(8), LZ4),
    merge_request_diff_id Int64 CODEC(Delta(8), LZ4),
    project_id Int64 CODEC(Delta(8), LZ4),
    too_large Bool DEFAULT false,
    new_path String DEFAULT '' CODEC(ZSTD(3)),
    old_path String DEFAULT '' CODEC(ZSTD(3)),
    new_file Bool DEFAULT false,
    renamed_file Bool DEFAULT false,
    deleted_file Bool DEFAULT false,
    binary Nullable(Bool),
    generated Nullable(Bool),
    a_mode String DEFAULT '' CODEC(ZSTD(1)),
    b_mode String DEFAULT '' CODEC(ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_too_large too_large TYPE minmax GRANULARITY 1,
    INDEX idx_new_file new_file TYPE minmax GRANULARITY 1,
    INDEX idx_renamed_file renamed_file TYPE minmax GRANULARITY 1,
    INDEX idx_deleted_file deleted_file TYPE minmax GRANULARITY 1,
    INDEX idx_binary binary TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_new_path new_path TYPE text(tokenizer = splitByString(['/'])) GRANULARITY 1,
    INDEX idx_new_path_ngram new_path TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_old_path old_path TYPE text(tokenizer = splitByString(['/'])) GRANULARITY 1,
    INDEX idx_old_path_ngram old_path TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_merge_request_id merge_request_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_merge_request_diff_id merge_request_diff_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_milestone (
    id Int64 CODEC(Delta(8), LZ4),
    iid Nullable(Int64) CODEC(Delta(8), LZ4),
    title String DEFAULT '' CODEC(ZSTD(1)),
    description String DEFAULT '' CODEC(ZSTD(3)),
    state String DEFAULT '' CODEC(ZSTD(1)),
    due_date Nullable(Date32) CODEC(Delta(4), ZSTD(1)),
    start_date Nullable(Date32) CODEC(Delta(4), ZSTD(1)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    project_id Nullable(Int64) CODEC(Delta(8), LZ4),
    group_id Nullable(Int64) CODEC(Delta(8), LZ4),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_title title TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_title_ngram title TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_state state TYPE set(4) GRANULARITY 2,
    INDEX idx_description description TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_description_ngram description TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_group_id group_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_note (
    id Int64 CODEC(Delta(8), LZ4),
    note String DEFAULT '' CODEC(ZSTD(3)),
    noteable_type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    noteable_id Nullable(Int64) CODEC(Delta(8), LZ4),
    line_code String DEFAULT '' CODEC(ZSTD(1)),
    commit_id String DEFAULT '' CODEC(ZSTD(1)),
    st_diff String DEFAULT '' CODEC(ZSTD(3)),
    discussion_id Nullable(String) CODEC(ZSTD(1)),
    resolved_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    internal Bool DEFAULT false,
    confidential Nullable(Bool),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    project_id Nullable(Int64) CODEC(Delta(8), LZ4),
    author_id Nullable(Int64) CODEC(Delta(8), LZ4),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_noteable_type noteable_type TYPE set(14) GRANULARITY 2,
    INDEX idx_internal internal TYPE minmax GRANULARITY 1,
    INDEX idx_confidential confidential TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_note note TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_note_ngram note TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_discussion_id discussion_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_noteable_id noteable_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_author_id author_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_package (
    id Int64 CODEC(Delta(8), LZ4),
    name String DEFAULT '' CODEC(ZSTD(1)),
    version Nullable(String) CODEC(ZSTD(1)),
    package_type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    status LowCardinality(String) DEFAULT '' CODEC(LZ4),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    project_id Int64 CODEC(Delta(8), LZ4),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_name name TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_package_type package_type TYPE set(16) GRANULARITY 2,
    INDEX idx_status status TYPE set(8) GRANULARITY 2,
    INDEX idx_created_at created_at TYPE minmax GRANULARITY 1,
    INDEX idx_updated_at updated_at TYPE minmax GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_pipeline (
    id Int64 CODEC(Delta(8), LZ4),
    iid Nullable(Int64) CODEC(Delta(8), LZ4),
    sha String DEFAULT '' CODEC(ZSTD(1)),
    ref String DEFAULT '' CODEC(ZSTD(1)),
    status LowCardinality(String) DEFAULT '' CODEC(LZ4),
    source LowCardinality(String) DEFAULT '' CODEC(LZ4),
    tag Bool DEFAULT false,
    duration Nullable(Int64) CODEC(Delta(8), LZ4),
    failure_reason String DEFAULT '' CODEC(ZSTD(1)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    started_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    finished_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    committed_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    before_sha String DEFAULT '' CODEC(ZSTD(1)),
    yaml_errors String DEFAULT '' CODEC(ZSTD(3)),
    protected Nullable(Bool),
    project_id Int64 CODEC(Delta(8), LZ4),
    user_id Nullable(Int64) CODEC(Delta(8), LZ4),
    merge_request_id Nullable(Int64) CODEC(Delta(8), LZ4),
    auto_canceled_by_id Nullable(Int64) CODEC(Delta(8), LZ4),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_status status TYPE set(16) GRANULARITY 2,
    INDEX idx_tag tag TYPE minmax GRANULARITY 1,
    INDEX idx_created_at created_at TYPE minmax GRANULARITY 1,
    INDEX idx_started_at started_at TYPE minmax GRANULARITY 1,
    INDEX idx_finished_at finished_at TYPE minmax GRANULARITY 1,
    INDEX idx_committed_at committed_at TYPE minmax GRANULARITY 1,
    INDEX idx_updated_at updated_at TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_source source TYPE set(20) GRANULARITY 2,
    INDEX idx_ref ref TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_ref_ngram ref TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_user_id user_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_merge_request_id merge_request_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_auto_canceled_by_id auto_canceled_by_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_project (
    id Int64 CODEC(Delta(8), LZ4),
    name String DEFAULT '' CODEC(ZSTD(1)),
    description String DEFAULT '' CODEC(ZSTD(3)),
    visibility_level LowCardinality(String) DEFAULT '' CODEC(LZ4),
    full_path String DEFAULT '' CODEC(ZSTD(3)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    archived Nullable(Bool),
    star_count Nullable(Int64) CODEC(Delta(8), LZ4),
    last_activity_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_archived archived TYPE minmax GRANULARITY 1,
    INDEX idx_created_at created_at TYPE minmax GRANULARITY 1,
    INDEX idx_updated_at updated_at TYPE minmax GRANULARITY 1,
    INDEX idx_last_activity_at last_activity_at TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_name_ngram name TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_full_path full_path TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_description description TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_description_ngram description TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_runner (
    id Int64 CODEC(Delta(8), LZ4),
    runner_type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    name String DEFAULT '' CODEC(ZSTD(1)),
    description String DEFAULT '' CODEC(ZSTD(1)),
    active Bool DEFAULT true,
    locked Bool DEFAULT false,
    run_untagged Bool DEFAULT true,
    access_level LowCardinality(String) DEFAULT '' CODEC(LZ4),
    maximum_timeout Nullable(Int64) CODEC(Delta(8), LZ4),
    organization_id Nullable(Int64) CODEC(Delta(8), LZ4),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    contacted_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_runner_type runner_type TYPE set(4) GRANULARITY 2,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_name_ngram name TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (id) PRIMARY KEY (id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_security_scan (
    id Int64 CODEC(Delta(8), LZ4),
    scan_type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    status LowCardinality(String) DEFAULT '' CODEC(LZ4),
    latest Bool DEFAULT true,
    created_at DateTime64(6, 'UTC') DEFAULT now() CODEC(Delta(8), ZSTD(1)),
    updated_at DateTime64(6, 'UTC') DEFAULT now() CODEC(Delta(8), ZSTD(1)),
    project_id Int64 CODEC(Delta(8), LZ4),
    pipeline_id Nullable(Int64) CODEC(Delta(8), LZ4),
    build_id Int64 CODEC(Delta(8), LZ4),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_latest latest TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_pipeline_id pipeline_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_build_id build_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_stage (
    id Int64 CODEC(Delta(8), LZ4),
    name String DEFAULT '' CODEC(ZSTD(1)),
    status LowCardinality(String) DEFAULT '' CODEC(LZ4),
    position Nullable(Int64) CODEC(Delta(8), LZ4),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    project_id Int64 CODEC(Delta(8), LZ4),
    pipeline_id Nullable(Int64) CODEC(Delta(8), LZ4),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_name_ngram name TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_status status TYPE set(16) GRANULARITY 2,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_pipeline_id pipeline_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_user (
    id Int64 CODEC(Delta(8), LZ4),
    username String DEFAULT '' CODEC(ZSTD(1)),
    email String DEFAULT '' CODEC(ZSTD(1)),
    name String DEFAULT '' CODEC(ZSTD(1)),
    first_name String DEFAULT '' CODEC(ZSTD(1)),
    last_name String DEFAULT '' CODEC(ZSTD(1)),
    state LowCardinality(String) DEFAULT '' CODEC(LZ4),
    avatar_url Nullable(String) CODEC(ZSTD(1)),
    public_email String DEFAULT '' CODEC(ZSTD(1)),
    preferred_language String DEFAULT '' CODEC(ZSTD(1)),
    last_activity_on Nullable(Date32) CODEC(Delta(4), ZSTD(1)),
    private_profile Bool DEFAULT false,
    is_admin Bool DEFAULT false,
    is_auditor Bool DEFAULT false,
    is_external Bool DEFAULT false,
    user_type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_state state TYPE set(10) GRANULARITY 2,
    INDEX idx_user_type user_type TYPE set(26) GRANULARITY 2,
    INDEX idx_private_profile private_profile TYPE minmax GRANULARITY 1,
    INDEX idx_is_admin is_admin TYPE minmax GRANULARITY 1,
    INDEX idx_is_auditor is_auditor TYPE minmax GRANULARITY 1,
    INDEX idx_is_external is_external TYPE minmax GRANULARITY 1,
    INDEX idx_username username TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_username_ngram username TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_name_ngram name TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (id) PRIMARY KEY (id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_vulnerability (
    id Int64 CODEC(Delta(8), LZ4),
    title String DEFAULT '' CODEC(ZSTD(1)),
    description String DEFAULT '' CODEC(ZSTD(3)),
    state LowCardinality(String) DEFAULT '' CODEC(LZ4),
    severity LowCardinality(String) DEFAULT '' CODEC(LZ4),
    report_type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    resolved_on_default_branch Bool DEFAULT false,
    present_on_default_branch Bool DEFAULT true,
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    detected_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    resolved_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    confirmed_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    dismissed_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    project_id Int64 CODEC(Delta(8), LZ4),
    finding_id Int64 CODEC(Delta(8), LZ4),
    author_id Int64 CODEC(Delta(8), LZ4),
    confirmed_by_id Nullable(Int64) CODEC(Delta(8), LZ4),
    resolved_by_id Nullable(Int64) CODEC(Delta(8), LZ4),
    dismissed_by_id Nullable(Int64) CODEC(Delta(8), LZ4),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_state state TYPE set(4) GRANULARITY 2,
    INDEX idx_severity severity TYPE set(8) GRANULARITY 2,
    INDEX idx_report_type report_type TYPE set(4) GRANULARITY 2,
    INDEX idx_resolved_on_default_branch resolved_on_default_branch TYPE minmax GRANULARITY 1,
    INDEX idx_present_on_default_branch present_on_default_branch TYPE minmax GRANULARITY 1,
    INDEX idx_detected_at detected_at TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_title title TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_title_ngram title TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_description description TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_description_ngram description TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_finding_id finding_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_author_id author_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_confirmed_by_id confirmed_by_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_resolved_by_id resolved_by_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_dismissed_by_id dismissed_by_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_vulnerability_identifier (
    id Int64 CODEC(Delta(8), LZ4),
    external_type String DEFAULT '' CODEC(ZSTD(1)),
    external_id String DEFAULT '' CODEC(ZSTD(1)),
    name String DEFAULT '' CODEC(ZSTD(1)),
    url String DEFAULT '' CODEC(ZSTD(1)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    project_id Int64 CODEC(Delta(8), LZ4),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_external_type external_type TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_external_type_ngram external_type TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_external_id external_id TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_external_id_ngram external_id TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_name_ngram name TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_vulnerability_occurrence (
    id Int64 CODEC(Delta(8), LZ4),
    uuid String DEFAULT '' CODEC(ZSTD(1)),
    name String DEFAULT '' CODEC(ZSTD(1)),
    description String DEFAULT '' CODEC(ZSTD(3)),
    solution String DEFAULT '' CODEC(ZSTD(3)),
    cve String DEFAULT '' CODEC(ZSTD(1)),
    location String DEFAULT '{}' CODEC(ZSTD(3)),
    location_fingerprint String DEFAULT '' CODEC(ZSTD(1)),
    severity LowCardinality(String) DEFAULT '' CODEC(LZ4),
    report_type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    detection_method LowCardinality(String) DEFAULT '' CODEC(LZ4),
    created_at DateTime64(6, 'UTC') DEFAULT now() CODEC(Delta(8), ZSTD(1)),
    updated_at DateTime64(6, 'UTC') DEFAULT now() CODEC(Delta(8), ZSTD(1)),
    detected_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    project_id Int64 CODEC(Delta(8), LZ4),
    scanner_id Int64 CODEC(Delta(8), LZ4),
    vulnerability_id Nullable(Int64) CODEC(Delta(8), LZ4),
    primary_identifier_id Int64 CODEC(Delta(8), LZ4),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_name_ngram name TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_description description TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_description_ngram description TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_cve cve TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_scanner_id scanner_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_vulnerability_id vulnerability_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_primary_identifier_id primary_identifier_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_vulnerability_scanner (
    id Int64 CODEC(Delta(8), LZ4),
    external_id String DEFAULT '' CODEC(ZSTD(1)),
    name String DEFAULT '' CODEC(ZSTD(1)),
    vendor LowCardinality(String) DEFAULT 'GitLab' CODEC(LZ4),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    project_id Int64 CODEC(Delta(8), LZ4),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_name_ngram name TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_external_id external_id TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_external_id_ngram external_id TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_work_item (
    id Int64 CODEC(Delta(8), LZ4),
    iid Nullable(Int64) CODEC(Delta(8), LZ4),
    title String DEFAULT '' CODEC(ZSTD(1)),
    description String DEFAULT '' CODEC(ZSTD(3)),
    state LowCardinality(String) DEFAULT '' CODEC(LZ4),
    work_item_type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    confidential Bool DEFAULT false,
    due_date Nullable(Date32) CODEC(Delta(4), ZSTD(1)),
    start_date Nullable(Date32) CODEC(Delta(4), ZSTD(1)),
    weight Nullable(Int64) CODEC(Delta(8), LZ4),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    closed_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    project_id Nullable(Int64) CODEC(Delta(8), LZ4),
    author_id Nullable(Int64) CODEC(Delta(8), LZ4),
    milestone_id Nullable(Int64) CODEC(Delta(8), LZ4),
    namespace_id Int64 CODEC(Delta(8), LZ4),
    closed_by_id Nullable(Int64) CODEC(Delta(8), LZ4),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_state state TYPE set(10) GRANULARITY 2,
    INDEX idx_work_item_type work_item_type TYPE set(10) GRANULARITY 2,
    INDEX idx_confidential confidential TYPE minmax GRANULARITY 1,
    INDEX idx_created_at created_at TYPE minmax GRANULARITY 1,
    INDEX idx_due_date due_date TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_title title TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_title_ngram title TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_description description TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_description_ngram description TYPE ngrambf_v1(3, 512, 2, 0) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_author_id author_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_milestone_id milestone_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_namespace_id namespace_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_closed_by_id closed_by_id TYPE bloom_filter(0.0001) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_ci_edge (
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    source_id Int64 CODEC(Delta(8), LZ4),
    source_kind LowCardinality(String) CODEC(LZ4),
    relationship_kind LowCardinality(String) CODEC(LZ4),
    target_id Int64 CODEC(Delta(8), LZ4),
    target_kind LowCardinality(String) CODEC(LZ4),
    source_tags Array(LowCardinality(String)) CODEC(LZ4),
    target_tags Array(LowCardinality(String)) CODEC(LZ4),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_source_id source_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_target_id target_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX source_tags_idx source_tags TYPE text(tokenizer = 'array') GRANULARITY 64,
    INDEX target_tags_idx target_tags TYPE text(tokenizer = 'array') GRANULARITY 64
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, relationship_kind, source_id, target_id, source_kind, target_kind)
PRIMARY KEY (traversal_path, relationship_kind, source_id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_code_edge (
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    project_id Int64 CODEC(Delta(8), LZ4),
    branch String CODEC(ZSTD(1)),
    source_id Int64 CODEC(Delta(8), LZ4),
    source_kind LowCardinality(String) CODEC(LZ4),
    relationship_kind LowCardinality(String) CODEC(LZ4),
    target_id Int64 CODEC(Delta(8), LZ4),
    target_kind LowCardinality(String) CODEC(LZ4),
    source_tags Array(LowCardinality(String)) CODEC(LZ4),
    target_tags Array(LowCardinality(String)) CODEC(LZ4),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_source_id source_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_target_id target_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_project_id project_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_branch branch TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX source_tags_idx source_tags TYPE text(tokenizer = 'array') GRANULARITY 64,
    INDEX target_tags_idx target_tags TYPE text(tokenizer = 'array') GRANULARITY 64
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, relationship_kind, project_id, branch, source_id, target_id, source_kind, target_kind)
PRIMARY KEY (traversal_path, relationship_kind, project_id, branch)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE TABLE IF NOT EXISTS gl_edge (
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    source_id Int64 CODEC(Delta(8), LZ4),
    source_kind LowCardinality(String) CODEC(LZ4),
    relationship_kind LowCardinality(String) CODEC(LZ4),
    target_id Int64 CODEC(Delta(8), LZ4),
    target_kind LowCardinality(String) CODEC(LZ4),
    source_tags Array(LowCardinality(String)) CODEC(LZ4),
    target_tags Array(LowCardinality(String)) CODEC(LZ4),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_source_id source_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX idx_target_id target_id TYPE bloom_filter(0.0001) GRANULARITY 1,
    INDEX source_tags_idx source_tags TYPE text(tokenizer = 'array') GRANULARITY 64,
    INDEX target_tags_idx target_tags TYPE text(tokenizer = 'array') GRANULARITY 64
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, relationship_kind, source_id, target_id, source_kind, target_kind)
PRIMARY KEY (traversal_path, relationship_kind, source_id)
SETTINGS index_granularity = 1024, allow_experimental_replacing_merge_with_cleanup = 1, auto_statistics_types = 'minmax, uniq, countmin';

CREATE DICTIONARY IF NOT EXISTS gl_project_traversal_paths_dict (
    id Int64,
    traversal_path String
)
PRIMARY KEY id
SOURCE(CLICKHOUSE(USER 'default' QUERY $q$SELECT id, traversal_path FROM (SELECT id, argMax(traversal_path, _version) AS traversal_path FROM `default`.gl_project GROUP BY id HAVING argMax(_deleted, _version) = false)$q$))
LIFETIME(MIN 60 MAX 300)
LAYOUT(HASHED());

CREATE DICTIONARY IF NOT EXISTS gl_group_traversal_paths_dict (
    id Int64,
    traversal_path String
)
PRIMARY KEY id
SOURCE(CLICKHOUSE(USER 'default' QUERY $q$SELECT id, traversal_path FROM (SELECT id, argMax(traversal_path, _version) AS traversal_path FROM `default`.gl_group GROUP BY id HAVING argMax(_deleted, _version) = false)$q$))
LIFETIME(MIN 60 MAX 300)
LAYOUT(HASHED());

