-- SCHEMA_VERSION=39 [AUTOGENERATED — DO NOT EDIT MANUALLY]
-- Regenerate with: mise schema:generate:ddl
-- Applied by the indexer after a migrating version's backfill completes; see
-- crates/indexer/src/schema/completion.rs::apply_deferred_projections.

-- code_indexing_checkpoint ----------------------------
ALTER TABLE code_indexing_checkpoint MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE code_indexing_checkpoint ADD PROJECTION IF NOT EXISTS project_lookup (SELECT * ORDER BY project_id);
ALTER TABLE code_indexing_checkpoint MATERIALIZE PROJECTION IF EXISTS project_lookup SETTINGS mutations_sync = 2;

-- gl_branch ----------------------------
ALTER TABLE gl_branch MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_branch ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_branch MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_branch ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_branch MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_branch ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_branch MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_definition ----------------------------
ALTER TABLE gl_definition MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_definition ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_definition MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_definition ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_definition MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_definition ADD PROJECTION IF NOT EXISTS by_branch (SELECT _part_offset ORDER BY branch);
ALTER TABLE gl_definition MATERIALIZE PROJECTION IF EXISTS by_branch SETTINGS mutations_sync = 2;
ALTER TABLE gl_definition ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_definition MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_deployment ----------------------------
ALTER TABLE gl_deployment MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_deployment ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_deployment MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_deployment ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_deployment MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_deployment ADD PROJECTION IF NOT EXISTS by_environment_id (SELECT _part_offset ORDER BY environment_id);
ALTER TABLE gl_deployment MATERIALIZE PROJECTION IF EXISTS by_environment_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_deployment ADD PROJECTION IF NOT EXISTS by_user_id (SELECT _part_offset ORDER BY user_id);
ALTER TABLE gl_deployment MATERIALIZE PROJECTION IF EXISTS by_user_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_deployment ADD PROJECTION IF NOT EXISTS by_status_id (SELECT * ORDER BY (status, id));
ALTER TABLE gl_deployment MATERIALIZE PROJECTION IF EXISTS by_status_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_deployment ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_deployment MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_directory ----------------------------
ALTER TABLE gl_directory MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_directory ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_directory MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_directory ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_directory MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_directory ADD PROJECTION IF NOT EXISTS by_branch (SELECT _part_offset ORDER BY branch);
ALTER TABLE gl_directory MATERIALIZE PROJECTION IF EXISTS by_branch SETTINGS mutations_sync = 2;
ALTER TABLE gl_directory ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_directory MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_environment ----------------------------
ALTER TABLE gl_environment MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_environment ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_environment MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_environment ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_environment MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_environment ADD PROJECTION IF NOT EXISTS by_merge_request_id (SELECT _part_offset ORDER BY merge_request_id);
ALTER TABLE gl_environment MATERIALIZE PROJECTION IF EXISTS by_merge_request_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_environment ADD PROJECTION IF NOT EXISTS by_tier_state (SELECT * ORDER BY (tier, state, id));
ALTER TABLE gl_environment MATERIALIZE PROJECTION IF EXISTS by_tier_state SETTINGS mutations_sync = 2;
ALTER TABLE gl_environment ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_environment MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_file ----------------------------
ALTER TABLE gl_file MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_file ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_file MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_file ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_file MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_file ADD PROJECTION IF NOT EXISTS by_branch (SELECT _part_offset ORDER BY branch);
ALTER TABLE gl_file MATERIALIZE PROJECTION IF EXISTS by_branch SETTINGS mutations_sync = 2;
ALTER TABLE gl_file ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_file MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_finding ----------------------------
ALTER TABLE gl_finding MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_finding ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_finding MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_finding ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_finding MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_finding ADD PROJECTION IF NOT EXISTS by_scan_id (SELECT _part_offset ORDER BY scan_id);
ALTER TABLE gl_finding MATERIALIZE PROJECTION IF EXISTS by_scan_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_finding ADD PROJECTION IF NOT EXISTS by_scanner_id (SELECT _part_offset ORDER BY scanner_id);
ALTER TABLE gl_finding MATERIALIZE PROJECTION IF EXISTS by_scanner_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_finding ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_finding MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_group ----------------------------
ALTER TABLE gl_group MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_group ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_group MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_group ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_group MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_imported_symbol ----------------------------
ALTER TABLE gl_imported_symbol MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_imported_symbol ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_imported_symbol MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_imported_symbol ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_imported_symbol MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_imported_symbol ADD PROJECTION IF NOT EXISTS by_branch (SELECT _part_offset ORDER BY branch);
ALTER TABLE gl_imported_symbol MATERIALIZE PROJECTION IF EXISTS by_branch SETTINGS mutations_sync = 2;
ALTER TABLE gl_imported_symbol ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_imported_symbol MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_job ----------------------------
ALTER TABLE gl_job MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_job ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_job MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_job ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_job MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_job ADD PROJECTION IF NOT EXISTS by_user_id (SELECT _part_offset ORDER BY user_id);
ALTER TABLE gl_job MATERIALIZE PROJECTION IF EXISTS by_user_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_job ADD PROJECTION IF NOT EXISTS by_upstream_pipeline_id (SELECT _part_offset ORDER BY upstream_pipeline_id);
ALTER TABLE gl_job MATERIALIZE PROJECTION IF EXISTS by_upstream_pipeline_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_job ADD PROJECTION IF NOT EXISTS by_stage_id (SELECT _part_offset ORDER BY stage_id);
ALTER TABLE gl_job MATERIALIZE PROJECTION IF EXISTS by_stage_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_job ADD PROJECTION IF NOT EXISTS by_pipeline_id (SELECT _part_offset ORDER BY pipeline_id);
ALTER TABLE gl_job MATERIALIZE PROJECTION IF EXISTS by_pipeline_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_job ADD PROJECTION IF NOT EXISTS by_runner_id (SELECT _part_offset ORDER BY runner_id);
ALTER TABLE gl_job MATERIALIZE PROJECTION IF EXISTS by_runner_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_job ADD PROJECTION IF NOT EXISTS by_auto_canceled_by_id (SELECT _part_offset ORDER BY auto_canceled_by_id);
ALTER TABLE gl_job MATERIALIZE PROJECTION IF EXISTS by_auto_canceled_by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_job ADD PROJECTION IF NOT EXISTS by_status_id (SELECT * ORDER BY (status, id));
ALTER TABLE gl_job MATERIALIZE PROJECTION IF EXISTS by_status_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_job ADD PROJECTION IF NOT EXISTS by_pipeline_status (SELECT * ORDER BY (traversal_path, pipeline_id, status, id));
ALTER TABLE gl_job MATERIALIZE PROJECTION IF EXISTS by_pipeline_status SETTINGS mutations_sync = 2;
ALTER TABLE gl_job ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_job MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_job_metadata ----------------------------
ALTER TABLE gl_job_metadata MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_job_metadata ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_job_metadata MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_job_metadata ADD PROJECTION IF NOT EXISTS by_build_id (SELECT _part_offset ORDER BY build_id);
ALTER TABLE gl_job_metadata MATERIALIZE PROJECTION IF EXISTS by_build_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_job_metadata ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_job_metadata MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_job_metadata ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_job_metadata MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_label ----------------------------
ALTER TABLE gl_label MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_label ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_label MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_label ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_label MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_label ADD PROJECTION IF NOT EXISTS by_group_id (SELECT _part_offset ORDER BY group_id);
ALTER TABLE gl_label MATERIALIZE PROJECTION IF EXISTS by_group_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_label ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_label MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_merge_request ----------------------------
ALTER TABLE gl_merge_request MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_merge_request ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_merge_request MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_merge_request MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request ADD PROJECTION IF NOT EXISTS by_author_id (SELECT _part_offset ORDER BY author_id);
ALTER TABLE gl_merge_request MATERIALIZE PROJECTION IF EXISTS by_author_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request ADD PROJECTION IF NOT EXISTS by_merge_user_id (SELECT _part_offset ORDER BY merge_user_id);
ALTER TABLE gl_merge_request MATERIALIZE PROJECTION IF EXISTS by_merge_user_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request ADD PROJECTION IF NOT EXISTS by_milestone_id (SELECT _part_offset ORDER BY milestone_id);
ALTER TABLE gl_merge_request MATERIALIZE PROJECTION IF EXISTS by_milestone_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request ADD PROJECTION IF NOT EXISTS by_source_project_id (SELECT _part_offset ORDER BY source_project_id);
ALTER TABLE gl_merge_request MATERIALIZE PROJECTION IF EXISTS by_source_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request ADD PROJECTION IF NOT EXISTS by_updated_by_id (SELECT _part_offset ORDER BY updated_by_id);
ALTER TABLE gl_merge_request MATERIALIZE PROJECTION IF EXISTS by_updated_by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request ADD PROJECTION IF NOT EXISTS by_last_edited_by_id (SELECT _part_offset ORDER BY last_edited_by_id);
ALTER TABLE gl_merge_request MATERIALIZE PROJECTION IF EXISTS by_last_edited_by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request ADD PROJECTION IF NOT EXISTS by_closed_by_id (SELECT _part_offset ORDER BY closed_by_id);
ALTER TABLE gl_merge_request MATERIALIZE PROJECTION IF EXISTS by_closed_by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request ADD PROJECTION IF NOT EXISTS by_head_pipeline_id (SELECT _part_offset ORDER BY head_pipeline_id);
ALTER TABLE gl_merge_request MATERIALIZE PROJECTION IF EXISTS by_head_pipeline_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request ADD PROJECTION IF NOT EXISTS by_latest_merge_request_diff_id (SELECT _part_offset ORDER BY latest_merge_request_diff_id);
ALTER TABLE gl_merge_request MATERIALIZE PROJECTION IF EXISTS by_latest_merge_request_diff_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request ADD PROJECTION IF NOT EXISTS by_state_id (SELECT * ORDER BY (state, id));
ALTER TABLE gl_merge_request MATERIALIZE PROJECTION IF EXISTS by_state_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request ADD PROJECTION IF NOT EXISTS by_project_state (SELECT * ORDER BY (traversal_path, project_id, state, id));
ALTER TABLE gl_merge_request MATERIALIZE PROJECTION IF EXISTS by_project_state SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_merge_request MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_merge_request_diff ----------------------------
ALTER TABLE gl_merge_request_diff MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_merge_request_diff ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_merge_request_diff MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request_diff ADD PROJECTION IF NOT EXISTS by_merge_request_id (SELECT _part_offset ORDER BY merge_request_id);
ALTER TABLE gl_merge_request_diff MATERIALIZE PROJECTION IF EXISTS by_merge_request_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request_diff ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_merge_request_diff MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request_diff ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_merge_request_diff MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_merge_request_diff_file ----------------------------
ALTER TABLE gl_merge_request_diff_file MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_merge_request_diff_file ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_merge_request_diff_file MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request_diff_file ADD PROJECTION IF NOT EXISTS by_merge_request_id (SELECT _part_offset ORDER BY merge_request_id);
ALTER TABLE gl_merge_request_diff_file MATERIALIZE PROJECTION IF EXISTS by_merge_request_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request_diff_file ADD PROJECTION IF NOT EXISTS by_merge_request_diff_id (SELECT _part_offset ORDER BY merge_request_diff_id);
ALTER TABLE gl_merge_request_diff_file MATERIALIZE PROJECTION IF EXISTS by_merge_request_diff_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request_diff_file ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_merge_request_diff_file MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_merge_request_diff_file ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_merge_request_diff_file MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_milestone ----------------------------
ALTER TABLE gl_milestone MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_milestone ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_milestone MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_milestone ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_milestone MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_milestone ADD PROJECTION IF NOT EXISTS by_group_id (SELECT _part_offset ORDER BY group_id);
ALTER TABLE gl_milestone MATERIALIZE PROJECTION IF EXISTS by_group_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_milestone ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_milestone MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_note ----------------------------
ALTER TABLE gl_note MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_note ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_note MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_note ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_note MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_note ADD PROJECTION IF NOT EXISTS by_author_id (SELECT _part_offset ORDER BY author_id);
ALTER TABLE gl_note MATERIALIZE PROJECTION IF EXISTS by_author_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_note ADD PROJECTION IF NOT EXISTS by_noteable (SELECT * ORDER BY (traversal_path, noteable_type, noteable_id, id));
ALTER TABLE gl_note MATERIALIZE PROJECTION IF EXISTS by_noteable SETTINGS mutations_sync = 2;
ALTER TABLE gl_note ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_note MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_pipeline ----------------------------
ALTER TABLE gl_pipeline MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_pipeline ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_pipeline MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_pipeline ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_pipeline MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_pipeline ADD PROJECTION IF NOT EXISTS by_user_id (SELECT _part_offset ORDER BY user_id);
ALTER TABLE gl_pipeline MATERIALIZE PROJECTION IF EXISTS by_user_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_pipeline ADD PROJECTION IF NOT EXISTS by_merge_request_id (SELECT _part_offset ORDER BY merge_request_id);
ALTER TABLE gl_pipeline MATERIALIZE PROJECTION IF EXISTS by_merge_request_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_pipeline ADD PROJECTION IF NOT EXISTS by_auto_canceled_by_id (SELECT _part_offset ORDER BY auto_canceled_by_id);
ALTER TABLE gl_pipeline MATERIALIZE PROJECTION IF EXISTS by_auto_canceled_by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_pipeline ADD PROJECTION IF NOT EXISTS by_status_id (SELECT * ORDER BY (status, id));
ALTER TABLE gl_pipeline MATERIALIZE PROJECTION IF EXISTS by_status_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_pipeline ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_pipeline MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_project ----------------------------
ALTER TABLE gl_project MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_project ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_project MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_project ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_project MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_runner ----------------------------
ALTER TABLE gl_runner MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_runner ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_runner MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_runner ADD PROJECTION IF NOT EXISTS by_runner_type (SELECT * ORDER BY (runner_type, id));
ALTER TABLE gl_runner MATERIALIZE PROJECTION IF EXISTS by_runner_type SETTINGS mutations_sync = 2;

-- gl_security_scan ----------------------------
ALTER TABLE gl_security_scan MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_security_scan ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_security_scan MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_security_scan ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_security_scan MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_security_scan ADD PROJECTION IF NOT EXISTS by_pipeline_id (SELECT _part_offset ORDER BY pipeline_id);
ALTER TABLE gl_security_scan MATERIALIZE PROJECTION IF EXISTS by_pipeline_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_security_scan ADD PROJECTION IF NOT EXISTS by_build_id (SELECT _part_offset ORDER BY build_id);
ALTER TABLE gl_security_scan MATERIALIZE PROJECTION IF EXISTS by_build_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_security_scan ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_security_scan MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_stage ----------------------------
ALTER TABLE gl_stage MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_stage ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_stage MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_stage ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_stage MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_stage ADD PROJECTION IF NOT EXISTS by_pipeline_id (SELECT _part_offset ORDER BY pipeline_id);
ALTER TABLE gl_stage MATERIALIZE PROJECTION IF EXISTS by_pipeline_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_stage ADD PROJECTION IF NOT EXISTS by_pipeline (SELECT * ORDER BY (traversal_path, pipeline_id, id));
ALTER TABLE gl_stage MATERIALIZE PROJECTION IF EXISTS by_pipeline SETTINGS mutations_sync = 2;
ALTER TABLE gl_stage ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_stage MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_vulnerability ----------------------------
ALTER TABLE gl_vulnerability MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_vulnerability ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_vulnerability MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_vulnerability ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_vulnerability MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_vulnerability ADD PROJECTION IF NOT EXISTS by_finding_id (SELECT _part_offset ORDER BY finding_id);
ALTER TABLE gl_vulnerability MATERIALIZE PROJECTION IF EXISTS by_finding_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_vulnerability ADD PROJECTION IF NOT EXISTS by_author_id (SELECT _part_offset ORDER BY author_id);
ALTER TABLE gl_vulnerability MATERIALIZE PROJECTION IF EXISTS by_author_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_vulnerability ADD PROJECTION IF NOT EXISTS by_confirmed_by_id (SELECT _part_offset ORDER BY confirmed_by_id);
ALTER TABLE gl_vulnerability MATERIALIZE PROJECTION IF EXISTS by_confirmed_by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_vulnerability ADD PROJECTION IF NOT EXISTS by_resolved_by_id (SELECT _part_offset ORDER BY resolved_by_id);
ALTER TABLE gl_vulnerability MATERIALIZE PROJECTION IF EXISTS by_resolved_by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_vulnerability ADD PROJECTION IF NOT EXISTS by_dismissed_by_id (SELECT _part_offset ORDER BY dismissed_by_id);
ALTER TABLE gl_vulnerability MATERIALIZE PROJECTION IF EXISTS by_dismissed_by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_vulnerability ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_vulnerability MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_vulnerability_identifier ----------------------------
ALTER TABLE gl_vulnerability_identifier MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_vulnerability_identifier ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_vulnerability_identifier MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_vulnerability_identifier ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_vulnerability_identifier MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_vulnerability_identifier ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_vulnerability_identifier MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_vulnerability_occurrence ----------------------------
ALTER TABLE gl_vulnerability_occurrence MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_vulnerability_occurrence ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_vulnerability_occurrence MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_vulnerability_occurrence ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_vulnerability_occurrence MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_vulnerability_occurrence ADD PROJECTION IF NOT EXISTS by_scanner_id (SELECT _part_offset ORDER BY scanner_id);
ALTER TABLE gl_vulnerability_occurrence MATERIALIZE PROJECTION IF EXISTS by_scanner_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_vulnerability_occurrence ADD PROJECTION IF NOT EXISTS by_vulnerability_id (SELECT _part_offset ORDER BY vulnerability_id);
ALTER TABLE gl_vulnerability_occurrence MATERIALIZE PROJECTION IF EXISTS by_vulnerability_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_vulnerability_occurrence ADD PROJECTION IF NOT EXISTS by_primary_identifier_id (SELECT _part_offset ORDER BY primary_identifier_id);
ALTER TABLE gl_vulnerability_occurrence MATERIALIZE PROJECTION IF EXISTS by_primary_identifier_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_vulnerability_occurrence ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_vulnerability_occurrence MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_vulnerability_scanner ----------------------------
ALTER TABLE gl_vulnerability_scanner MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_vulnerability_scanner ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_vulnerability_scanner MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_vulnerability_scanner ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_vulnerability_scanner MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_vulnerability_scanner ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_vulnerability_scanner MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_work_item ----------------------------
ALTER TABLE gl_work_item MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_work_item ADD PROJECTION IF NOT EXISTS by_id (SELECT * ORDER BY id);
ALTER TABLE gl_work_item MATERIALIZE PROJECTION IF EXISTS by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_work_item ADD PROJECTION IF NOT EXISTS by_project_id (SELECT _part_offset ORDER BY project_id);
ALTER TABLE gl_work_item MATERIALIZE PROJECTION IF EXISTS by_project_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_work_item ADD PROJECTION IF NOT EXISTS by_author_id (SELECT _part_offset ORDER BY author_id);
ALTER TABLE gl_work_item MATERIALIZE PROJECTION IF EXISTS by_author_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_work_item ADD PROJECTION IF NOT EXISTS by_milestone_id (SELECT _part_offset ORDER BY milestone_id);
ALTER TABLE gl_work_item MATERIALIZE PROJECTION IF EXISTS by_milestone_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_work_item ADD PROJECTION IF NOT EXISTS by_namespace_id (SELECT _part_offset ORDER BY namespace_id);
ALTER TABLE gl_work_item MATERIALIZE PROJECTION IF EXISTS by_namespace_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_work_item ADD PROJECTION IF NOT EXISTS by_closed_by_id (SELECT _part_offset ORDER BY closed_by_id);
ALTER TABLE gl_work_item MATERIALIZE PROJECTION IF EXISTS by_closed_by_id SETTINGS mutations_sync = 2;
ALTER TABLE gl_work_item ADD PROJECTION IF NOT EXISTS tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    );
ALTER TABLE gl_work_item MATERIALIZE PROJECTION IF EXISTS tp_count SETTINGS mutations_sync = 2;

-- gl_ci_edge ----------------------------
ALTER TABLE gl_ci_edge MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_ci_edge ADD PROJECTION IF NOT EXISTS by_source (SELECT * ORDER BY (source_id, relationship_kind, target_id, traversal_path, source_kind, target_kind));
ALTER TABLE gl_ci_edge MATERIALIZE PROJECTION IF EXISTS by_source SETTINGS mutations_sync = 2;
ALTER TABLE gl_ci_edge ADD PROJECTION IF NOT EXISTS by_target (SELECT * ORDER BY (target_id, relationship_kind, source_id, traversal_path, source_kind, target_kind));
ALTER TABLE gl_ci_edge MATERIALIZE PROJECTION IF EXISTS by_target SETTINGS mutations_sync = 2;
ALTER TABLE gl_ci_edge ADD PROJECTION IF NOT EXISTS by_rel_source_kind (SELECT * ORDER BY (relationship_kind, source_kind, source_id, target_id, traversal_path, target_kind));
ALTER TABLE gl_ci_edge MATERIALIZE PROJECTION IF EXISTS by_rel_source_kind SETTINGS mutations_sync = 2;
ALTER TABLE gl_ci_edge ADD PROJECTION IF NOT EXISTS by_rel_target_kind (SELECT * ORDER BY (relationship_kind, target_kind, target_id, source_id, traversal_path, source_kind));
ALTER TABLE gl_ci_edge MATERIALIZE PROJECTION IF EXISTS by_rel_target_kind SETTINGS mutations_sync = 2;
ALTER TABLE gl_ci_edge ADD PROJECTION IF NOT EXISTS agg_counts_by_source (
      SELECT relationship_kind, target_kind, source_id, traversal_path, count()
      GROUP BY relationship_kind, target_kind, source_id, traversal_path
    );
ALTER TABLE gl_ci_edge MATERIALIZE PROJECTION IF EXISTS agg_counts_by_source SETTINGS mutations_sync = 2;
ALTER TABLE gl_ci_edge ADD PROJECTION IF NOT EXISTS agg_counts_by_target (
      SELECT relationship_kind, source_kind, target_id, traversal_path, count()
      GROUP BY relationship_kind, source_kind, target_id, traversal_path
    );
ALTER TABLE gl_ci_edge MATERIALIZE PROJECTION IF EXISTS agg_counts_by_target SETTINGS mutations_sync = 2;

-- gl_code_edge ----------------------------
ALTER TABLE gl_code_edge MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_code_edge ADD PROJECTION IF NOT EXISTS by_source (SELECT * ORDER BY (source_id, relationship_kind, target_id, traversal_path, source_kind, target_kind));
ALTER TABLE gl_code_edge MATERIALIZE PROJECTION IF EXISTS by_source SETTINGS mutations_sync = 2;
ALTER TABLE gl_code_edge ADD PROJECTION IF NOT EXISTS by_target (SELECT * ORDER BY (target_id, relationship_kind, source_id, traversal_path, source_kind, target_kind));
ALTER TABLE gl_code_edge MATERIALIZE PROJECTION IF EXISTS by_target SETTINGS mutations_sync = 2;
ALTER TABLE gl_code_edge ADD PROJECTION IF NOT EXISTS by_rel_source_kind (SELECT * ORDER BY (relationship_kind, source_kind, source_id, target_id, traversal_path, target_kind));
ALTER TABLE gl_code_edge MATERIALIZE PROJECTION IF EXISTS by_rel_source_kind SETTINGS mutations_sync = 2;
ALTER TABLE gl_code_edge ADD PROJECTION IF NOT EXISTS by_rel_target_kind (SELECT * ORDER BY (relationship_kind, target_kind, target_id, source_id, traversal_path, source_kind));
ALTER TABLE gl_code_edge MATERIALIZE PROJECTION IF EXISTS by_rel_target_kind SETTINGS mutations_sync = 2;
ALTER TABLE gl_code_edge ADD PROJECTION IF NOT EXISTS agg_counts_by_source (
      SELECT relationship_kind, target_kind, source_id, traversal_path, count()
      GROUP BY relationship_kind, target_kind, source_id, traversal_path
    );
ALTER TABLE gl_code_edge MATERIALIZE PROJECTION IF EXISTS agg_counts_by_source SETTINGS mutations_sync = 2;
ALTER TABLE gl_code_edge ADD PROJECTION IF NOT EXISTS agg_counts_by_target (
      SELECT relationship_kind, source_kind, target_id, traversal_path, count()
      GROUP BY relationship_kind, source_kind, target_id, traversal_path
    );
ALTER TABLE gl_code_edge MATERIALIZE PROJECTION IF EXISTS agg_counts_by_target SETTINGS mutations_sync = 2;

-- gl_edge ----------------------------
ALTER TABLE gl_edge MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';
ALTER TABLE gl_edge ADD PROJECTION IF NOT EXISTS by_source (SELECT * ORDER BY (source_id, relationship_kind, target_id, traversal_path, source_kind, target_kind));
ALTER TABLE gl_edge MATERIALIZE PROJECTION IF EXISTS by_source SETTINGS mutations_sync = 2;
ALTER TABLE gl_edge ADD PROJECTION IF NOT EXISTS by_target (SELECT * ORDER BY (target_id, relationship_kind, source_id, traversal_path, source_kind, target_kind));
ALTER TABLE gl_edge MATERIALIZE PROJECTION IF EXISTS by_target SETTINGS mutations_sync = 2;
ALTER TABLE gl_edge ADD PROJECTION IF NOT EXISTS by_rel_source_kind (SELECT * ORDER BY (relationship_kind, source_kind, source_id, target_id, traversal_path, target_kind));
ALTER TABLE gl_edge MATERIALIZE PROJECTION IF EXISTS by_rel_source_kind SETTINGS mutations_sync = 2;
ALTER TABLE gl_edge ADD PROJECTION IF NOT EXISTS by_rel_target_kind (SELECT * ORDER BY (relationship_kind, target_kind, target_id, source_id, traversal_path, source_kind));
ALTER TABLE gl_edge MATERIALIZE PROJECTION IF EXISTS by_rel_target_kind SETTINGS mutations_sync = 2;
ALTER TABLE gl_edge ADD PROJECTION IF NOT EXISTS agg_counts (
      SELECT relationship_kind, source_kind, target_id, traversal_path, count()
      GROUP BY relationship_kind, source_kind, target_id, traversal_path
    );
ALTER TABLE gl_edge MATERIALIZE PROJECTION IF EXISTS agg_counts SETTINGS mutations_sync = 2;
ALTER TABLE gl_edge ADD PROJECTION IF NOT EXISTS agg_counts_by_source (
      SELECT relationship_kind, target_kind, source_id, traversal_path, count()
      GROUP BY relationship_kind, target_kind, source_id, traversal_path
    );
ALTER TABLE gl_edge MATERIALIZE PROJECTION IF EXISTS agg_counts_by_source SETTINGS mutations_sync = 2;
ALTER TABLE gl_edge ADD PROJECTION IF NOT EXISTS node_edge_counts (
      SELECT traversal_path, source_kind, target_kind, relationship_kind, uniq(source_id), uniq(target_id), uniq(source_id, target_id)
      GROUP BY traversal_path, source_kind, target_kind, relationship_kind
    );
ALTER TABLE gl_edge MATERIALIZE PROJECTION IF EXISTS node_edge_counts SETTINGS mutations_sync = 2;
