-- SCHEMA_VERSION=27 [AUTOGENERATED — DO NOT EDIT MANUALLY]
-- Regenerate with: mise schema:generate:ddl

CREATE TABLE IF NOT EXISTS checkpoint (
    key String CODEC(ZSTD(1)),
    watermark DateTime64(6, 'UTC') CODEC(Delta(8), ZSTD(1)),
    cursor_values String DEFAULT '' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (key)
SETTINGS allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS namespace_deletion_schedule (
    namespace_id Int64 CODEC(ZSTD(1)),
    traversal_path String CODEC(ZSTD(1)),
    scheduled_deletion_date DateTime64(6, 'UTC') CODEC(Delta(8), ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (namespace_id, traversal_path)
SETTINGS allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS code_indexing_checkpoint (
    traversal_path String CODEC(ZSTD(1)),
    project_id Int64 CODEC(ZSTD(1)),
    branch String CODEC(ZSTD(1)),
    last_task_id Int64 CODEC(ZSTD(1)),
    last_commit Nullable(String) CODEC(ZSTD(1)),
    indexed_at DateTime64(6, 'UTC') CODEC(Delta(8), ZSTD(1)),
    _version UInt64,
    _deleted Bool DEFAULT false,
    PROJECTION project_lookup (SELECT * ORDER BY project_id)
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, project_id, branch)
SETTINGS deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_branch (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    traversal_path String CODEC(ZSTD(1)),
    project_id Int64 CODEC(Delta(8), ZSTD(1)),
    name String CODEC(ZSTD(1)),
    is_default Bool DEFAULT true,
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, project_id, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_definition (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    traversal_path String CODEC(ZSTD(1)),
    project_id Int64 CODEC(Delta(8), ZSTD(1)),
    branch String CODEC(ZSTD(1)),
    commit_sha String DEFAULT '' CODEC(ZSTD(1)),
    file_path String CODEC(ZSTD(3)),
    fqn String CODEC(ZSTD(3)),
    name String CODEC(ZSTD(1)),
    definition_type LowCardinality(String) CODEC(LZ4),
    start_line Int64 CODEC(ZSTD(1)),
    end_line Int64 CODEC(ZSTD(1)),
    start_byte Int64 CODEC(ZSTD(1)),
    end_byte Int64 CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_fqn fqn TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_file_path file_path TYPE text(tokenizer = splitByString(['/'])) GRANULARITY 1,
    INDEX idx_definition_type definition_type TYPE set(20) GRANULARITY 2,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, project_id, branch, id)
SETTINGS index_granularity = 1024, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_deployment (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    iid Int64 CODEC(ZSTD(1)),
    project_id Int64 CODEC(ZSTD(1)),
    ref String DEFAULT '' CODEC(ZSTD(1)),
    tag Bool DEFAULT false,
    sha String DEFAULT '' CODEC(ZSTD(1)),
    status LowCardinality(String) DEFAULT '' CODEC(LZ4),
    deployable_type String DEFAULT '' CODEC(ZSTD(1)),
    deployable_id Nullable(Int64) CODEC(ZSTD(1)),
    on_stop Nullable(String) CODEC(ZSTD(1)),
    archived Bool DEFAULT false,
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    finished_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_status status TYPE set(8) GRANULARITY 2,
    INDEX idx_archived archived TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_ref ref TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION by_status_id (SELECT * ORDER BY (status, id)),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1;

CREATE TABLE IF NOT EXISTS gl_directory (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    traversal_path String CODEC(ZSTD(1)),
    project_id Int64 CODEC(Delta(8), ZSTD(1)),
    branch String CODEC(ZSTD(1)),
    commit_sha String DEFAULT '' CODEC(ZSTD(1)),
    path String CODEC(ZSTD(3)),
    name String CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_path path TYPE text(tokenizer = splitByString(['/'])) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, project_id, branch, id)
SETTINGS index_granularity = 1024, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_environment (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    project_id Int64 CODEC(ZSTD(1)),
    name String DEFAULT '' CODEC(ZSTD(1)),
    slug String DEFAULT '' CODEC(ZSTD(1)),
    external_url Nullable(String) CODEC(ZSTD(1)),
    environment_type Nullable(String) CODEC(ZSTD(1)),
    state LowCardinality(String) DEFAULT 'available' CODEC(LZ4),
    tier LowCardinality(Nullable(String)) CODEC(LZ4),
    auto_stop_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    auto_delete_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    auto_stop_setting LowCardinality(String) DEFAULT 'always' CODEC(LZ4),
    cluster_agent_id Nullable(Int64) CODEC(ZSTD(1)),
    kubernetes_namespace Nullable(String) CODEC(ZSTD(1)),
    flux_resource_path Nullable(String) CODEC(ZSTD(1)),
    description Nullable(String) CODEC(ZSTD(3)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_state state TYPE set(4) GRANULARITY 2,
    INDEX idx_tier tier TYPE set(8) GRANULARITY 2,
    INDEX idx_environment_type environment_type TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION by_tier_state (SELECT * ORDER BY (tier, state, id)),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_file (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    traversal_path String CODEC(ZSTD(1)),
    project_id Int64 CODEC(Delta(8), ZSTD(1)),
    branch String CODEC(ZSTD(1)),
    commit_sha String DEFAULT '' CODEC(ZSTD(1)),
    path String CODEC(ZSTD(3)),
    name String CODEC(ZSTD(1)),
    extension LowCardinality(String) CODEC(LZ4),
    language LowCardinality(String) CODEC(LZ4),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_path path TYPE text(tokenizer = splitByString(['/'])) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, project_id, branch, id)
SETTINGS index_granularity = 1024, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_finding (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    uuid String DEFAULT '' CODEC(ZSTD(1)),
    name Nullable(String) CODEC(ZSTD(1)),
    description Nullable(String) CODEC(ZSTD(3)),
    solution Nullable(String) CODEC(ZSTD(3)),
    severity LowCardinality(String) DEFAULT '' CODEC(LZ4),
    deduplicated Bool DEFAULT false,
    overridden_uuid Nullable(String) CODEC(ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_deduplicated deduplicated TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_description description TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_group (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    name Nullable(String) CODEC(ZSTD(1)),
    description Nullable(String) CODEC(ZSTD(3)),
    visibility_level LowCardinality(Nullable(String)) CODEC(LZ4),
    full_path Nullable(String) CODEC(ZSTD(3)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_full_path full_path TYPE text(tokenizer = splitByString(['/'])) GRANULARITY 1,
    INDEX idx_description description TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_imported_symbol (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    traversal_path String CODEC(ZSTD(1)),
    project_id Int64 CODEC(Delta(8), ZSTD(1)),
    branch String CODEC(ZSTD(1)),
    commit_sha String DEFAULT '' CODEC(ZSTD(1)),
    file_path String CODEC(ZSTD(3)),
    import_type LowCardinality(String) CODEC(LZ4),
    import_path String CODEC(ZSTD(3)),
    identifier_name Nullable(String) CODEC(ZSTD(1)),
    identifier_alias Nullable(String) CODEC(ZSTD(1)),
    start_line Int64 CODEC(ZSTD(1)),
    end_line Int64 CODEC(ZSTD(1)),
    start_byte Int64 CODEC(ZSTD(1)),
    end_byte Int64 CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_identifier_name identifier_name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_file_path file_path TYPE text(tokenizer = splitByString(['/'])) GRANULARITY 1,
    INDEX idx_import_path import_path TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_import_type import_type TYPE set(10) GRANULARITY 2,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, project_id, branch, id)
SETTINGS index_granularity = 1024, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_job (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    name Nullable(String) CODEC(ZSTD(1)),
    status LowCardinality(String) DEFAULT '' CODEC(LZ4),
    ref Nullable(String) CODEC(ZSTD(1)),
    tag Nullable(Bool),
    allow_failure Bool DEFAULT false,
    coverage Nullable(String) CODEC(ZSTD(1)),
    environment Nullable(String) CODEC(ZSTD(1)),
    `when` Nullable(String) CODEC(ZSTD(1)),
    retried Nullable(Bool),
    failure_reason Nullable(String) CODEC(ZSTD(1)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    started_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    finished_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    queued_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    runner_id Nullable(Int64) CODEC(ZSTD(1)),
    timeout Nullable(Int64) CODEC(ZSTD(1)),
    timeout_source LowCardinality(Nullable(String)) CODEC(LZ4),
    exit_code Nullable(Int64) CODEC(ZSTD(1)),
    scheduling_type LowCardinality(Nullable(String)) CODEC(LZ4),
    pipeline_id Nullable(Int64) CODEC(ZSTD(1)),
    auto_canceled_by_id Nullable(Int64) CODEC(ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_status status TYPE set(16) GRANULARITY 2,
    INDEX idx_allow_failure allow_failure TYPE minmax GRANULARITY 1,
    INDEX idx_retried retried TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_ref ref TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION by_status_id (SELECT * ORDER BY (status, id)),
    PROJECTION by_pipeline_status (SELECT * ORDER BY (traversal_path, pipeline_id, status, id)),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1;

CREATE TABLE IF NOT EXISTS gl_job_metadata (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    build_id Int64 CODEC(Delta(8), ZSTD(1)),
    interruptible Nullable(Bool),
    timeout Nullable(Int64) CODEC(ZSTD(1)),
    timeout_source LowCardinality(Nullable(String)) CODEC(LZ4),
    exit_code Nullable(Int64) CODEC(ZSTD(1)),
    has_exposed_artifacts Nullable(Bool),
    expanded_environment_name Nullable(String) CODEC(ZSTD(1)),
    environment_auto_stop_in Nullable(String) CODEC(ZSTD(1)),
    debug_trace_enabled Bool DEFAULT false,
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_build_id build_id TYPE bloom_filter(0.01) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION by_build_id (SELECT * ORDER BY build_id),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, build_id) PRIMARY KEY (traversal_path, build_id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_label (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    title Nullable(String) CODEC(ZSTD(1)),
    description Nullable(String) CODEC(ZSTD(3)),
    color Nullable(String) CODEC(ZSTD(1)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_title title TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_description description TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_merge_request (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    iid Nullable(Int64) CODEC(ZSTD(1)),
    title String DEFAULT '' CODEC(ZSTD(1)),
    description String DEFAULT '' CODEC(ZSTD(3)),
    source_branch String DEFAULT '' CODEC(ZSTD(1)),
    target_branch String DEFAULT '' CODEC(ZSTD(1)),
    state LowCardinality(String) DEFAULT '' CODEC(LZ4),
    merge_status LowCardinality(String) DEFAULT 'unchecked' CODEC(LZ4),
    draft Bool DEFAULT false,
    squash Bool DEFAULT false,
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    merge_commit_sha Nullable(String) CODEC(ZSTD(1)),
    discussion_locked Nullable(Bool),
    prepared_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    project_id Int64 CODEC(ZSTD(1)),
    merged_commit_sha Nullable(String) CODEC(ZSTD(1)),
    squash_commit_sha Nullable(String) CODEC(ZSTD(1)),
    latest_build_started_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    latest_build_finished_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    first_deployed_to_production_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    merged_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    latest_closed_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    first_comment_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    first_commit_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    last_commit_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    diff_size Nullable(Int64) CODEC(ZSTD(1)),
    modified_paths_size Nullable(Int64) CODEC(ZSTD(1)),
    commits_count Nullable(Int64) CODEC(ZSTD(1)),
    first_approved_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    first_reassigned_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    added_lines Nullable(Int64) CODEC(ZSTD(1)),
    removed_lines Nullable(Int64) CODEC(ZSTD(1)),
    first_contribution Bool DEFAULT false,
    reviewer_first_assigned_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_state state TYPE set(6) GRANULARITY 2,
    INDEX idx_draft draft TYPE minmax GRANULARITY 1,
    INDEX idx_squash squash TYPE minmax GRANULARITY 1,
    INDEX idx_discussion_locked discussion_locked TYPE minmax GRANULARITY 1,
    INDEX idx_first_contribution first_contribution TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_title title TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_description description TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_source_branch source_branch TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_target_branch target_branch TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_merge_status merge_status TYPE set(8) GRANULARITY 2,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION by_state_id (SELECT * ORDER BY (state, id)),
    PROJECTION by_project_state (SELECT * ORDER BY (traversal_path, project_id, state, id)),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1;

CREATE TABLE IF NOT EXISTS gl_merge_request_diff (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    merge_request_id Int64 CODEC(ZSTD(1)),
    state Nullable(String) CODEC(ZSTD(1)),
    base_commit_sha Nullable(String) CODEC(ZSTD(1)),
    head_commit_sha Nullable(String) CODEC(ZSTD(1)),
    start_commit_sha Nullable(String) CODEC(ZSTD(1)),
    commits_count Nullable(Int64) CODEC(ZSTD(1)),
    files_count Nullable(Int64) CODEC(ZSTD(1)),
    project_id Int64 CODEC(ZSTD(1)),
    diff_type LowCardinality(String) DEFAULT 'regular' CODEC(LZ4),
    real_size Nullable(String) CODEC(ZSTD(1)),
    stored_externally Bool DEFAULT false,
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_merge_request_diff_file (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    merge_request_id Int64 CODEC(ZSTD(1)),
    merge_request_diff_id Int64 CODEC(ZSTD(1)),
    project_id Int64 CODEC(ZSTD(1)),
    too_large Bool DEFAULT false,
    new_path Nullable(String) CODEC(ZSTD(3)),
    old_path String DEFAULT '' CODEC(ZSTD(3)),
    new_file Bool DEFAULT false,
    renamed_file Bool DEFAULT false,
    deleted_file Bool DEFAULT false,
    binary Nullable(Bool),
    generated Nullable(Bool),
    a_mode String DEFAULT '' CODEC(ZSTD(1)),
    b_mode String DEFAULT '' CODEC(ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_too_large too_large TYPE minmax GRANULARITY 1,
    INDEX idx_new_file new_file TYPE minmax GRANULARITY 1,
    INDEX idx_renamed_file renamed_file TYPE minmax GRANULARITY 1,
    INDEX idx_deleted_file deleted_file TYPE minmax GRANULARITY 1,
    INDEX idx_binary binary TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_new_path new_path TYPE text(tokenizer = splitByString(['/'])) GRANULARITY 1,
    INDEX idx_old_path old_path TYPE text(tokenizer = splitByString(['/'])) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_milestone (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    iid Nullable(Int64) CODEC(ZSTD(1)),
    title String DEFAULT '' CODEC(ZSTD(1)),
    description Nullable(String) CODEC(ZSTD(3)),
    state Nullable(String) CODEC(ZSTD(1)),
    due_date Nullable(Date32) CODEC(Delta(4), ZSTD(1)),
    start_date Nullable(Date32) CODEC(Delta(4), ZSTD(1)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_title title TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_state state TYPE set(4) GRANULARITY 2,
    INDEX idx_description description TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_note (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    note Nullable(String) CODEC(ZSTD(3)),
    noteable_type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    noteable_id Nullable(Int64) CODEC(ZSTD(1)),
    line_code Nullable(String) CODEC(ZSTD(1)),
    commit_id Nullable(String) CODEC(ZSTD(1)),
    st_diff Nullable(String) CODEC(ZSTD(3)),
    discussion_id Nullable(String) CODEC(ZSTD(1)),
    resolved_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    internal Bool DEFAULT false,
    confidential Nullable(Bool),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_noteable_type noteable_type TYPE set(14) GRANULARITY 2,
    INDEX idx_internal internal TYPE minmax GRANULARITY 1,
    INDEX idx_confidential confidential TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_note note TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_discussion_id discussion_id TYPE bloom_filter(0.01) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION by_noteable (SELECT * ORDER BY (traversal_path, noteable_type, noteable_id, id)),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1;

CREATE TABLE IF NOT EXISTS gl_pipeline (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    iid Nullable(Int64) CODEC(ZSTD(1)),
    sha Nullable(String) CODEC(ZSTD(1)),
    ref Nullable(String) CODEC(ZSTD(1)),
    status LowCardinality(String) DEFAULT '' CODEC(LZ4),
    source LowCardinality(String) DEFAULT '' CODEC(LZ4),
    tag Bool DEFAULT false,
    duration Nullable(Int64) CODEC(ZSTD(1)),
    failure_reason Nullable(String) CODEC(ZSTD(1)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    started_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    finished_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    committed_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    before_sha Nullable(String) CODEC(ZSTD(1)),
    yaml_errors Nullable(String) CODEC(ZSTD(3)),
    protected Nullable(Bool),
    auto_canceled_by_id Nullable(Int64) CODEC(ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_status status TYPE set(16) GRANULARITY 2,
    INDEX idx_tag tag TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_source source TYPE set(20) GRANULARITY 2,
    INDEX idx_ref ref TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION by_status_id (SELECT * ORDER BY (status, id)),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1;

CREATE TABLE IF NOT EXISTS gl_project (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    name Nullable(String) CODEC(ZSTD(1)),
    description Nullable(String) CODEC(ZSTD(3)),
    visibility_level LowCardinality(Nullable(String)) CODEC(LZ4),
    full_path Nullable(String) CODEC(ZSTD(3)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    archived Nullable(Bool),
    star_count Nullable(Int64) CODEC(ZSTD(1)),
    last_activity_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_archived archived TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_full_path full_path TYPE text(tokenizer = splitByString(['/'])) GRANULARITY 1,
    INDEX idx_description description TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_runner (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    runner_type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    name Nullable(String) CODEC(ZSTD(1)),
    description Nullable(String) CODEC(ZSTD(1)),
    active Bool DEFAULT true,
    locked Bool DEFAULT false,
    run_untagged Bool DEFAULT true,
    access_level LowCardinality(String) DEFAULT '' CODEC(LZ4),
    maximum_timeout Nullable(Int64) CODEC(ZSTD(1)),
    organization_id Nullable(Int64) CODEC(ZSTD(1)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    contacted_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_runner_type runner_type TYPE set(4) GRANULARITY 2,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION by_runner_type (SELECT * ORDER BY (runner_type, id))
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (id) PRIMARY KEY (id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_security_scan (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    scan_type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    status LowCardinality(String) DEFAULT '' CODEC(LZ4),
    latest Bool DEFAULT true,
    created_at DateTime64(6, 'UTC') DEFAULT now() CODEC(Delta(8), ZSTD(1)),
    updated_at DateTime64(6, 'UTC') DEFAULT now() CODEC(Delta(8), ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_latest latest TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_stage (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    name Nullable(String) CODEC(ZSTD(1)),
    status LowCardinality(String) DEFAULT '' CODEC(LZ4),
    position Nullable(Int64) CODEC(ZSTD(1)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    pipeline_id Nullable(Int64) CODEC(ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_status status TYPE set(16) GRANULARITY 2,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION by_pipeline (SELECT * ORDER BY (traversal_path, pipeline_id, id)),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_user (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    username String DEFAULT '' CODEC(ZSTD(1)),
    email String DEFAULT '' CODEC(ZSTD(1)),
    name String DEFAULT '' CODEC(ZSTD(1)),
    first_name String DEFAULT '' CODEC(ZSTD(1)),
    last_name String DEFAULT '' CODEC(ZSTD(1)),
    state LowCardinality(String) DEFAULT '' CODEC(LZ4),
    avatar_url Nullable(String) CODEC(ZSTD(1)),
    public_email Nullable(String) CODEC(ZSTD(1)),
    preferred_language Nullable(String) CODEC(ZSTD(1)),
    last_activity_on Nullable(Date32) CODEC(Delta(4), ZSTD(1)),
    private_profile Bool DEFAULT false,
    is_admin Bool DEFAULT false,
    is_auditor Bool DEFAULT false,
    is_external Bool DEFAULT false,
    user_type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_state state TYPE set(10) GRANULARITY 2,
    INDEX idx_user_type user_type TYPE set(26) GRANULARITY 2,
    INDEX idx_private_profile private_profile TYPE minmax GRANULARITY 1,
    INDEX idx_is_admin is_admin TYPE minmax GRANULARITY 1,
    INDEX idx_is_auditor is_auditor TYPE minmax GRANULARITY 1,
    INDEX idx_is_external is_external TYPE minmax GRANULARITY 1,
    INDEX idx_username username TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (id) PRIMARY KEY (id)
SETTINGS index_granularity = 2048, allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_vulnerability (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    title String DEFAULT '' CODEC(ZSTD(1)),
    description Nullable(String) CODEC(ZSTD(3)),
    state LowCardinality(String) DEFAULT '' CODEC(LZ4),
    severity LowCardinality(String) DEFAULT '' CODEC(LZ4),
    report_type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    resolved_on_default_branch Bool DEFAULT false,
    present_on_default_branch Bool DEFAULT true,
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    detected_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    resolved_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    confirmed_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    dismissed_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_state state TYPE set(4) GRANULARITY 2,
    INDEX idx_severity severity TYPE set(8) GRANULARITY 2,
    INDEX idx_report_type report_type TYPE set(4) GRANULARITY 2,
    INDEX idx_resolved_on_default_branch resolved_on_default_branch TYPE minmax GRANULARITY 1,
    INDEX idx_present_on_default_branch present_on_default_branch TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_title title TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_description description TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1;

CREATE TABLE IF NOT EXISTS gl_vulnerability_identifier (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    external_type String DEFAULT '' CODEC(ZSTD(1)),
    external_id String DEFAULT '' CODEC(ZSTD(1)),
    name String DEFAULT '' CODEC(ZSTD(1)),
    url Nullable(String) CODEC(ZSTD(1)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_external_type external_type TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_external_id external_id TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_vulnerability_occurrence (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    uuid String DEFAULT '' CODEC(ZSTD(1)),
    name String DEFAULT '' CODEC(ZSTD(1)),
    description Nullable(String) CODEC(ZSTD(3)),
    solution Nullable(String) CODEC(ZSTD(3)),
    cve Nullable(String) CODEC(ZSTD(1)),
    location Nullable(String) CODEC(ZSTD(3)),
    location_fingerprint String DEFAULT '' CODEC(ZSTD(1)),
    severity LowCardinality(String) DEFAULT '' CODEC(LZ4),
    report_type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    detection_method LowCardinality(String) DEFAULT '' CODEC(LZ4),
    created_at DateTime64(6, 'UTC') DEFAULT now() CODEC(Delta(8), ZSTD(1)),
    updated_at DateTime64(6, 'UTC') DEFAULT now() CODEC(Delta(8), ZSTD(1)),
    detected_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_description description TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_cve cve TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_vulnerability_scanner (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    external_id String DEFAULT '' CODEC(ZSTD(1)),
    name String DEFAULT '' CODEC(ZSTD(1)),
    vendor LowCardinality(String) DEFAULT 'GitLab' CODEC(LZ4),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_name name TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_external_id external_id TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_work_item (
    id Int64 CODEC(Delta(8), ZSTD(1)),
    iid Nullable(Int64) CODEC(ZSTD(1)),
    title String DEFAULT '' CODEC(ZSTD(1)),
    description Nullable(String) CODEC(ZSTD(3)),
    state LowCardinality(String) DEFAULT '' CODEC(LZ4),
    work_item_type LowCardinality(String) DEFAULT '' CODEC(LZ4),
    confidential Bool DEFAULT false,
    due_date Nullable(Date32) CODEC(Delta(4), ZSTD(1)),
    start_date Nullable(Date32) CODEC(Delta(4), ZSTD(1)),
    weight Nullable(Int64) CODEC(ZSTD(1)),
    created_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    updated_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    closed_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_state state TYPE set(10) GRANULARITY 2,
    INDEX idx_work_item_type work_item_type TYPE set(10) GRANULARITY 2,
    INDEX idx_confidential confidential TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_title title TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    INDEX idx_description description TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1,
    PROJECTION by_id (SELECT * ORDER BY id),
    PROJECTION tp_count (
      SELECT traversal_path, uniq(id)
      GROUP BY traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, id) PRIMARY KEY (traversal_path, id)
SETTINGS index_granularity = 2048, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1, add_minmax_index_for_temporal_columns = 1;

CREATE TABLE IF NOT EXISTS gl_ci_edge (
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    source_id Int64 CODEC(Delta(8), ZSTD(1)),
    source_kind LowCardinality(String) CODEC(LZ4),
    relationship_kind LowCardinality(String) CODEC(LZ4),
    target_id Int64 CODEC(Delta(8), ZSTD(1)),
    target_kind LowCardinality(String) CODEC(LZ4),
    source_tags Array(LowCardinality(String)),
    target_tags Array(LowCardinality(String)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_relationship relationship_kind TYPE set(50) GRANULARITY 2,
    INDEX source_tags_idx source_tags TYPE text(tokenizer = 'array') GRANULARITY 64,
    INDEX target_tags_idx target_tags TYPE text(tokenizer = 'array') GRANULARITY 64,
    PROJECTION by_source (SELECT * ORDER BY (source_id, relationship_kind, target_id, traversal_path, source_kind, target_kind)),
    PROJECTION by_target (SELECT * ORDER BY (target_id, relationship_kind, source_id, traversal_path, source_kind, target_kind)),
    PROJECTION by_rel_source_kind (SELECT * ORDER BY (relationship_kind, source_kind, source_id, target_id, traversal_path, target_kind)),
    PROJECTION by_rel_target_kind (SELECT * ORDER BY (relationship_kind, target_kind, target_id, source_id, traversal_path, source_kind)),
    PROJECTION agg_counts_by_source (
      SELECT relationship_kind, target_kind, source_id, traversal_path, count()
      GROUP BY relationship_kind, target_kind, source_id, traversal_path
    ),
    PROJECTION agg_counts_by_target (
      SELECT relationship_kind, source_kind, target_id, traversal_path, count()
      GROUP BY relationship_kind, source_kind, target_id, traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, source_id, relationship_kind, target_id, source_kind, target_kind)
PRIMARY KEY (traversal_path, source_id, relationship_kind)
SETTINGS index_granularity = 1024, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_code_edge (
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    source_id Int64 CODEC(Delta(8), ZSTD(1)),
    source_kind LowCardinality(String) CODEC(LZ4),
    relationship_kind LowCardinality(String) CODEC(LZ4),
    target_id Int64 CODEC(Delta(8), ZSTD(1)),
    target_kind LowCardinality(String) CODEC(LZ4),
    source_tags Array(LowCardinality(String)),
    target_tags Array(LowCardinality(String)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_relationship relationship_kind TYPE set(50) GRANULARITY 2,
    INDEX source_tags_idx source_tags TYPE text(tokenizer = 'array') GRANULARITY 64,
    INDEX target_tags_idx target_tags TYPE text(tokenizer = 'array') GRANULARITY 64,
    PROJECTION by_source (SELECT * ORDER BY (source_id, relationship_kind, target_id, traversal_path, source_kind, target_kind)),
    PROJECTION by_target (SELECT * ORDER BY (target_id, relationship_kind, source_id, traversal_path, source_kind, target_kind)),
    PROJECTION by_rel_source_kind (SELECT * ORDER BY (relationship_kind, source_kind, source_id, target_id, traversal_path, target_kind)),
    PROJECTION by_rel_target_kind (SELECT * ORDER BY (relationship_kind, target_kind, target_id, source_id, traversal_path, source_kind)),
    PROJECTION agg_counts_by_source (
      SELECT relationship_kind, target_kind, source_id, traversal_path, count()
      GROUP BY relationship_kind, target_kind, source_id, traversal_path
    ),
    PROJECTION agg_counts_by_target (
      SELECT relationship_kind, source_kind, target_id, traversal_path, count()
      GROUP BY relationship_kind, source_kind, target_id, traversal_path
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, source_id, relationship_kind, target_id, source_kind, target_kind)
PRIMARY KEY (traversal_path, source_id, relationship_kind)
SETTINGS index_granularity = 1024, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

CREATE TABLE IF NOT EXISTS gl_edge (
    traversal_path String DEFAULT '0/' CODEC(ZSTD(1)),
    source_id Int64 CODEC(Delta(8), ZSTD(1)),
    source_kind LowCardinality(String) CODEC(LZ4),
    relationship_kind LowCardinality(String) CODEC(LZ4),
    target_id Int64 CODEC(Delta(8), ZSTD(1)),
    target_kind LowCardinality(String) CODEC(LZ4),
    source_tags Array(LowCardinality(String)),
    target_tags Array(LowCardinality(String)),
    _version DateTime64(6, 'UTC') DEFAULT now64(6) CODEC(ZSTD(1)),
    _deleted Bool DEFAULT false,
    INDEX idx_relationship relationship_kind TYPE set(50) GRANULARITY 2,
    INDEX source_tags_idx source_tags TYPE text(tokenizer = 'array') GRANULARITY 64,
    INDEX target_tags_idx target_tags TYPE text(tokenizer = 'array') GRANULARITY 64,
    PROJECTION by_source (SELECT * ORDER BY (source_id, relationship_kind, target_id, traversal_path, source_kind, target_kind)),
    PROJECTION by_target (SELECT * ORDER BY (target_id, relationship_kind, source_id, traversal_path, source_kind, target_kind)),
    PROJECTION by_rel_source_kind (SELECT * ORDER BY (relationship_kind, source_kind, source_id, target_id, traversal_path, target_kind)),
    PROJECTION by_rel_target_kind (SELECT * ORDER BY (relationship_kind, target_kind, target_id, source_id, traversal_path, source_kind)),
    PROJECTION agg_counts (
      SELECT relationship_kind, source_kind, target_id, traversal_path, count()
      GROUP BY relationship_kind, source_kind, target_id, traversal_path
    ),
    PROJECTION agg_counts_by_source (
      SELECT relationship_kind, target_kind, source_id, traversal_path, count()
      GROUP BY relationship_kind, target_kind, source_id, traversal_path
    ),
    PROJECTION node_edge_counts (
      SELECT traversal_path, source_kind, target_kind, relationship_kind, uniq(source_id), uniq(target_id), uniq(source_id, target_id)
      GROUP BY traversal_path, source_kind, target_kind, relationship_kind
    )
) ENGINE = ReplacingMergeTree(_version, _deleted)
ORDER BY (traversal_path, source_id, relationship_kind, target_id, source_kind, target_kind)
PRIMARY KEY (traversal_path, source_id, relationship_kind)
SETTINGS index_granularity = 1024, deduplicate_merge_projection_mode = 'rebuild', allow_experimental_replacing_merge_with_cleanup = 1;

