//! Bake pinned Iglu schema versions and their JSON bodies into the binary
//! at compile time. Eliminates the runtime `std::fs::read_to_string` calls
//! that previously needed `config/schemas/` and `vendor/iglu/` to be present
//! in the runtime image.

use std::fs;
use std::path::PathBuf;

const SCHEMAS: &[&str] = &["orbit_common", "orbit_query"];

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let schema_dir = PathBuf::from(env_or_fail("SCHEMA_DIR"));
    let iglu_dir = PathBuf::from(env_or_fail("IGLU_DIR"));
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs - do not edit\n\n");

    for name in SCHEMAS {
        let version_path = schema_dir.join("iglu").join(format!("{name}.version"));
        println!("cargo:rerun-if-changed={}", version_path.display());
        let version = fs::read_to_string(&version_path)
            .unwrap_or_else(|e| panic!("read {}: {e}", version_path.display()))
            .trim()
            .to_string();

        let schema_path = iglu_dir.join(name).join("jsonschema").join(&version);
        println!("cargo:rerun-if-changed={}", schema_path.display());
        let schema_json = fs::read_to_string(&schema_path).unwrap_or_else(|e| {
            panic!(
                "read {}: {e} (did `vendir sync` run?)",
                schema_path.display()
            )
        });

        let upper = name.to_uppercase();
        let schema_uri = format!("iglu:com.gitlab/{name}/jsonschema/{version}");
        generated.push_str(&format!(
            "#[allow(dead_code)]\n\
             pub const {upper}_VERSION: &str = {version:?};\n"
        ));
        generated.push_str(&format!(
            "pub const {upper}_SCHEMA: &str = {schema_uri:?};\n"
        ));
        generated.push_str(&format!(
            "pub const {upper}_SCHEMA_JSON: &str = {schema_json:?};\n"
        ));
    }

    fs::write(out_dir.join("iglu_schemas.rs"), generated).expect("write generated iglu_schemas.rs");
}

fn env_or_fail(name: &str) -> String {
    std::env::var(name).unwrap_or_else(|_| {
        panic!("{name} must be set via .cargo/config.toml [env] when building gkg-analytics")
    })
}
