//! Proto-style codegen for Iglu schemas.
//!
//! For each `<name>` in [`SCHEMAS`], reads
//! `SCHEMA_DIR/iglu/<name>.version` and
//! `SCHEMA_DIR/iglu/<name>/<version>.json`, runs the JSON Schema through
//! [`typify::TypeSpace`] to produce idiomatic Rust types, and emits one
//! `pub mod <name> { ... }` block per schema into
//! `OUT_DIR/iglu_schemas.rs`. Each module exposes:
//!
//! - A `<TypeName>` struct (and any supporting enums) generated from the
//!   schema's `properties` / `enum` constraints. The runtime owns these
//!   directly — they implement `Serialize` + `Deserialize`.
//! - `pub const VERSION: &str` — the pinned version from `<name>.version`.
//! - `pub const SCHEMA_URI: &str` — the full Iglu URI.
//! - `pub const SCHEMA_JSON: &str` — the raw JSON body, embedded for
//!   test-time validator compilation.
//!
//! The runtime binary never reads the on-disk schema files.

use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;
use typify::{TypeSpace, TypeSpaceSettings};

const VENDOR: &str = "com.gitlab";

/// `(schema_name, generated_root_type_name)` — the second element is the
/// Rust identifier we want for the generated struct. Typify uses the
/// schema's `title` to pick a name; we inject one to keep the surface
/// stable across schema revisions.
const SCHEMAS: &[(&str, &str)] = &[
    ("orbit_common", "OrbitCommon"),
    ("orbit_query", "OrbitQuery"),
    ("orbit_sdlc_indexing", "OrbitSdlcIndexing"),
    ("orbit_code_indexing", "OrbitCodeIndexing"),
];

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let schema_dir = PathBuf::from(std::env::var("SCHEMA_DIR").unwrap_or_else(|_| {
        panic!("SCHEMA_DIR must be set via .cargo/config.toml [env] when building gkg-analytics")
    }));
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let iglu_dir = schema_dir.join("iglu");

    let mut emitted = String::new();
    emitted.push_str("// @generated by build.rs - do not edit\n\n");

    for (schema_name, type_name) in SCHEMAS {
        emitted.push_str(&render_module(&iglu_dir, schema_name, type_name));
    }

    fs::write(out_dir.join("iglu_schemas.rs"), emitted).expect("write generated iglu_schemas.rs");
}

fn render_module(iglu_dir: &Path, schema_name: &str, type_name: &str) -> String {
    let version_path = iglu_dir.join(format!("{schema_name}.version"));
    println!("cargo:rerun-if-changed={}", version_path.display());
    let version = fs::read_to_string(&version_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", version_path.display()))
        .trim()
        .to_string();

    let schema_path = iglu_dir.join(schema_name).join(format!("{version}.json"));
    println!("cargo:rerun-if-changed={}", schema_path.display());
    let schema_raw = fs::read_to_string(&schema_path).unwrap_or_else(|e| {
        panic!(
            "read {}: {e} (run `mise iglu:bump` to re-fetch)",
            schema_path.display()
        )
    });

    let mut parsed: Value = serde_json::from_str(&schema_raw)
        .unwrap_or_else(|e| panic!("invalid JSON in {}: {e}", schema_path.display()));
    assert_self_matches_path(&parsed, &schema_path, schema_name, &version);

    // Strip Iglu-specific top-level keys typify doesn't understand, and
    // inject `title` so the generated root struct is named deterministically.
    if let Some(obj) = parsed.as_object_mut() {
        obj.remove("$schema");
        obj.remove("self");
        obj.insert("title".to_string(), Value::String((*type_name).to_string()));
    }
    inject_defaults(&mut parsed, schema_name);
    promote_defaults_on_required(&mut parsed);

    let mut type_space = TypeSpace::new(
        TypeSpaceSettings::default()
            .with_struct_builder(false)
            .with_derive("Clone".to_string())
            .with_derive("Debug".to_string())
            .with_derive("PartialEq".to_string()),
    );
    // Type-inference picks up schemars::schema::RootSchema (typify's
    // public input type) without us naming the crate explicitly.
    type_space
        .add_root_schema(
            serde_json::from_value(parsed.clone())
                .unwrap_or_else(|e| panic!("typify cannot read {}: {e}", schema_path.display())),
        )
        .unwrap_or_else(|e| panic!("typify::add_root_schema failed for {schema_name}: {e}"));

    let body_tokens = type_space.to_stream();
    let body_file = syn::parse2::<syn::File>(body_tokens)
        .unwrap_or_else(|e| panic!("typify output is not valid Rust for {schema_name}: {e}"));
    let body_pretty = prettyplease::unparse(&body_file);

    let schema_uri = format!("iglu:{VENDOR}/{schema_name}/jsonschema/{version}");

    let mut out = String::new();
    out.push_str(&format!("pub mod {schema_name} {{\n"));
    out.push_str("    #![allow(clippy::all, dead_code, unused_imports)]\n");
    out.push_str("    use serde::{Deserialize, Serialize};\n\n");
    for line in body_pretty.lines() {
        out.push_str("    ");
        out.push_str(line);
        out.push('\n');
    }
    out.push('\n');
    out.push_str(&format!("    pub const VERSION: &str = {version:?};\n"));
    out.push_str(&format!(
        "    pub const SCHEMA_URI: &str = {schema_uri:?};\n"
    ));
    out.push_str(&format!(
        "    pub const SCHEMA_JSON: &str = {schema_raw:?};\n"
    ));
    out.push_str("}\n\n");
    out
}

/// Inject property defaults that GKG needs for `derive(Default)` but that
/// don't belong in the canonical Iglu schema. Runs before
/// `promote_defaults_on_required` so the injected defaults get the same
/// treatment as any naturally present ones.
fn inject_defaults(schema: &mut Value, schema_name: &str) {
    if schema_name == "orbit_query" {
        if let Some(source_type) = schema
            .pointer_mut("/properties/source_type")
            .and_then(Value::as_object_mut)
        {
            source_type
                .entry("default")
                .or_insert(Value::String("rest".to_string()));
        }
    }
}

/// Remove required properties that carry a `default` so typify generates
/// `#[serde(default)]` on those fields, enabling `derive(Default)` on the struct.
fn promote_defaults_on_required(schema: &mut Value) {
    let Some(obj) = schema.as_object_mut() else {
        return;
    };
    let props = obj
        .get("properties")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();
    if let Some(Value::Array(req)) = obj.get_mut("required") {
        req.retain(|r| {
            r.as_str()
                .and_then(|name| props.get(name))
                .and_then(|p| p.get("default"))
                .is_none()
        });
    }
}

fn assert_self_matches_path(parsed: &Value, schema_path: &Path, schema_name: &str, version: &str) {
    let self_block = parsed.get("self").unwrap_or_else(|| {
        panic!(
            "{} is missing top-level `self` (not a self-describing Iglu schema)",
            schema_path.display()
        )
    });
    assert_eq!(
        self_block.get("vendor").and_then(Value::as_str),
        Some(VENDOR),
        "{}: self.vendor must be {VENDOR:?}",
        schema_path.display()
    );
    assert_eq!(
        self_block.get("name").and_then(Value::as_str),
        Some(schema_name),
        "{}: self.name must match file path",
        schema_path.display()
    );
    assert_eq!(
        self_block.get("version").and_then(Value::as_str),
        Some(version),
        "{}: self.version must match pinned `{schema_name}.version`",
        schema_path.display()
    );
}
