[package]
name = "tree-dsl"
version = "0.1.0"
edition = "2024"

[dependencies]
tree-sitter = "0.26.3"
tree-sitter-bash = "0.25.1"
tree-sitter-c = "0.24.2"
tree-sitter-c-sharp = "0.23.0"
tree-sitter-cpp = "0.23.4"
tree-sitter-elixir = "0.3.5"
tree-sitter-go = "0.25.0"
tree-sitter-hcl = "1.1.0"
tree-sitter-java = "0.23.0"
tree-sitter-kotlin-sg = "0.4.0"
tree-sitter-lua = "0.5.0"
tree-sitter-php = "0.24.2"
tree-sitter-python = "0.25.0"
tree-sitter-ruby = "0.23.0"
tree-sitter-rust = "0.24.0"
tree-sitter-scala = "0.24.0"
tree-sitter-swift = "0.7.2"
tree-sitter-typescript = "0.23.2"
tree-sitter-zig = "1.1.2"
tree-sitter-haskell = "0.23.1"
tree-sitter-ocaml = "0.25.0"
smallvec = "1"
smol_str = "0.3"
serde = { workspace = true }
serde_yaml = "0.9"
stacker = "0.1"
rustc-hash = "2"
pest = { workspace = true }
pest_derive = { workspace = true }
pest_consume = { workspace = true }


