[package]
name = "gitlab-client"
version.workspace = true
edition = "2024"
license = "LicenseRef-EE"

[features]
testkit = [
    "dep:rcgen",
    "dep:tokio-rustls",
    "dep:tokio-stream",
    "dep:tonic-prost",
]

[dependencies]
circuit-breaker = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
gitaly-protos = { path = "../gitaly-protos" }
hyper-util = { workspace = true }
orbit-server-config = { path = "../orbit-server-config" }
jsonwebtoken = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
rustls-platform-verifier = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
tokio-stream = { workspace = true, optional = true }
tonic-prost = { workspace = true, optional = true }
rcgen = { workspace = true, optional = true }
tokio-rustls = { workspace = true, optional = true }

[dev-dependencies]
axum = { workspace = true }
rcgen = { workspace = true }
tokio-rustls = { workspace = true }
tokio-stream = { workspace = true }
tonic-prost = { workspace = true }
