import pytest


@pytest.fixture
def checks(repo, fake_tools):
    repo.copy(*(f"ci/{name}" for name in (
        "check_generated.py", "check_migration_ledger.py", "check-repository.py", "skip_check.py",
    )))
    for name in ("bin/cargo", "bin/git", "ci/dashboards.py"):
        fake_tools.install(name)
    return fake_tools


@pytest.fixture
def generated(repo, checks):
    repo.write("config/versions.yaml", "schema: 42\n")
    files = {"config/schemas/config.schema.json": b'{}\n'}
    checks.responses.update({command: {} for command in (
        "cargo xtask metrics-catalog --check", "dashboards.py --check", "cargo xtask query-docs --check",
    )})
    checks.responses["cargo xtask schema"] = {"stdout": "{}\n"}
    for target, filename in (("remote", "graph.sql"), ("remote-persistent", "graph_persistent.sql"), ("local", "graph_local.sql")):
        content = f"-- AUTOGENERATED SCHEMA_VERSION=42\n{target}\n"
        files[f"config/{filename}"] = content.encode()
        checks.responses[f"cargo xtask ddl --target {target}"] = {"stdout": content + "\n"}
    for filename, content in files.items():
        repo.write(filename, content)
    return files


@pytest.mark.parametrize("failed", [False, True])
def test_generated_checks_run_all_and_preserve_files(repo, checks, generated, failed):
    if failed:
        for response in checks.responses.values():
            response["status"] = 7
    output = checks.invoke("check_generated.py", status=int(failed))
    assert output.count("failed (exit 7)") == (7 if failed else 0)
    assert len(checks.calls()) == 7
    assert {name: (repo.root / name).read_bytes() for name in generated} == generated


def test_matching_output_from_failed_generator_still_fails(checks, generated):
    checks.responses["cargo xtask ddl --target remote"]["status"] = 7
    assert "failed (exit 7)" in checks.invoke("check_generated.py", "ddl", status=1)
    assert len(checks.calls()) == 3


@pytest.mark.parametrize("content", [b'{}', b'{}\r\n'])
def test_schema_compares_exact_bytes(repo, checks, generated, content):
    path = repo.write("config/schemas/config.schema.json", content)
    assert "config.schema.json is out of date" in checks.invoke("check_generated.py", status=1)
    assert path.read_bytes() == content


def test_ddl_reports_each_drift(repo, checks, generated):
    for filename, content in generated.items():
        if filename.endswith(".sql"):
            repo.write(filename, content + b" ")
    assert checks.invoke("check_generated.py", "ddl", status=1).count("is out of date") == 3


def test_bad_ddl_headers_and_missing_files_do_not_stop_remaining_checks(repo, checks, generated):
    path = repo.write("config/graph.sql", "-- SCHEMA_VERSION=41\n")
    repo.write("config/graph_persistent.sql", "-- no header\n")
    output = checks.invoke("check_generated.py", "ddl", status=1)
    assert "pins schema: 42" in output
    assert "missing the AUTOGENERATED header" in output
    assert checks.calls() == [["cargo", "xtask", "ddl", "--target", "local"]]
    path.unlink()
    assert "No such file" in checks.invoke("check_generated.py", "ddl", status=1)


@pytest.fixture
def toolchain(repo, checks):
    repo.write("mise.toml", '[tools]\nrust = {version = "1.98.1", components = "rustfmt, clippy"}\n')
    return (b"# Generated from mise.toml. Run: mise run toolchain:generate\n"
            b'[toolchain]\nchannel = "1.98.1"\ncomponents = ["rustfmt", "clippy"]\n')


def test_toolchain_check_write_and_missing_file(repo, checks, toolchain):
    path = repo.root / "rust-toolchain.toml"
    checks.invoke("check-repository.py", "toolchain", status=1)
    assert not path.exists()
    checks.invoke("check-repository.py", "toolchain", "--write")
    assert path.read_bytes() == toolchain
    checks.invoke("check-repository.py", "toolchain")
    stale = toolchain.replace(b"\n", b"\r\n")
    path.write_bytes(stale)
    checks.invoke("check-repository.py", "toolchain", status=1)
    assert path.read_bytes() == stale
    checks.invoke("check-repository.py", "toolchain", "--write")
    assert path.read_bytes() == toolchain


def test_repository_metadata_and_write_selection(repo, checks, toolchain):
    repo.write("AGENTS.md", "agents\n")
    repo.write("CLAUDE.md", "different\n")
    path = repo.write("rust-toolchain.toml", "stale\n")
    output = checks.invoke("check-repository.py", status=1)
    assert "must be identical" in output
    assert "Run mise toolchain:generate" in output
    checks.invoke("check-repository.py", "--write", status=2)
    assert path.read_bytes() == b"stale\n"
    checks.invoke("check-repository.py", "toolchain", "--write")
    repo.write("CLAUDE.md", "agents\n")
    checks.invoke("check-repository.py", "all")


@pytest.mark.parametrize("key,value", [
    ("SKIP_MIGRATION_LEDGER_CHECK", "1"),
    ("CI_MERGE_REQUEST_DESCRIPTION", "text [skip migration-ledger-check] text"),
    ("CI_MERGE_REQUEST_TITLE", "text [skip migration-ledger-check]"),
])
def test_migration_skip_controls_run_no_commands(checks, monkeypatch, key, value):
    monkeypatch.setenv(key, value)
    assert "skipping" in checks.invoke("check_migration_ledger.py")
    assert checks.calls() == []


def test_migration_default_base_git_failure_and_cargo_status(checks, monkeypatch):
    monkeypatch.setenv("SKIP_MIGRATION_LEDGER_CHECK", "true")
    checks.responses.update({
        "git log origin/main...HEAD --format=%B": {"status": 128},
        "cargo xtask migration-ledger check --base origin/main": {"status": 7},
    })
    checks.invoke("check_migration_ledger.py", status=7)
    assert len(checks.calls()) == 2


@pytest.mark.parametrize("script,token,args", [
    ("check_migration_ledger.py", "migration-ledger-check", ("--base", "custom base")),
    ("skip_check.py", "custom-check", ("custom-check",)),
])
def test_commit_skip_and_custom_base_survive_failed_fetch(checks, monkeypatch, script, token, args):
    monkeypatch.setenv("BASE_REF", "custom base")
    monkeypatch.setenv("CI_MERGE_REQUEST_DIFF_BASE_SHA", "abc123")
    checks.responses.update({
        "git fetch origin abc123 --depth=1": {"status": 1},
        "git log custom base...HEAD --format=%B": {"stdout": f"[skip {token}]\n" + "later message\n" * 10000},
    })
    checks.invoke(script, *args)
    assert checks.calls() == [["git", "fetch", "origin", "abc123", "--depth=1"],
                              ["git", "log", "custom base...HEAD", "--format=%B"]]


def test_migration_custom_base_is_one_argument(checks):
    checks.responses.update({"git log custom base...HEAD --format=%B": {},
                             "cargo xtask migration-ledger check --base custom base": {}})
    checks.invoke("check_migration_ledger.py", "--base", "custom base")
    assert checks.calls()[-1] == ["cargo", "xtask", "migration-ledger", "check", "--base", "custom base"]


@pytest.mark.parametrize("environment,status", [
    ({"SKIP_CUSTOM_CHECK": "true"}, 1),
    ({"SKIP_CUSTOM_CHECK": "1"}, 0),
    ({"BASE_REF": "", "CI_MERGE_REQUEST_DIFF_BASE_SHA": "abc123"}, 1),
])
def test_skip_cli_requires_literal_controls_without_empty_base_git_calls(checks, monkeypatch, environment, status):
    for key, value in environment.items():
        monkeypatch.setenv(key, value)
    checks.invoke("skip_check.py", "custom-check", status=status)
    assert checks.calls() == []
