import json
import os
import sys

from generators_test import CI, GeneratorTests


class RepositoryChecksTests(GeneratorTests):
    def setUp(self):
        super().setUp()
        self.env = {
            key: value for key, value in self.env.items()
            if not key.startswith(("CI", "GIT_", "SKIP_"))
        }
        for script in ("check_generated.py", "check_migration_ledger.py", "check-repository.py", "skip_check.py"):
            self.write(f"ci/{script}", (CI / script).read_text())
        self.responses = {}
        program = f"""#!{sys.executable}
import json
from pathlib import Path
import sys

command = [Path(sys.argv[0]).name, *sys.argv[1:]]
with Path('calls.jsonl').open('a') as log:
    log.write(json.dumps(command) + '\\n')
response = json.loads(Path('responses.json').read_text())[' '.join(command)]
sys.stdout.buffer.write(response.get('stdout', '').encode())
sys.exit(response.get('status', 0))
"""
        for name in ("bin/cargo", "bin/git", "ci/dashboards.py"):
            self.write(name, program).chmod(0o755)
        self.env["PATH"] = str(self.root / "bin") + os.pathsep + self.env["PATH"]

    def check(self, script, *args, status=0):
        self.write("responses.json", json.dumps(self.responses))
        return self.run_script(str(self.root / "ci" / script), *args, status=status)

    def calls(self):
        path = self.root / "calls.jsonl"
        return [json.loads(line) for line in path.read_text().splitlines()] if path.exists() else []


class GeneratedChecksTests(RepositoryChecksTests):
    def setUp(self):
        super().setUp()
        self.write("config/versions.yaml", "schema: 42\n")
        self.files = {"config/schemas/config.schema.json": b'{}\n'}
        self.responses = {
            "cargo xtask schema": {"stdout": "{}\n"},
            "cargo xtask metrics-catalog --check": {},
            "dashboards.py --check": {},
            "cargo xtask query-docs --check": {},
        }
        for target, filename in (
            ("remote", "graph.sql"),
            ("remote-persistent", "graph_persistent.sql"),
            ("local", "graph_local.sql"),
        ):
            content = f"-- AUTOGENERATED SCHEMA_VERSION=42\n{target}\n"
            self.files[f"config/{filename}"] = content.encode()
            self.responses[f"cargo xtask ddl --target {target}"] = {"stdout": content + "\n"}
        for filename, content in self.files.items():
            self.write(filename, content.decode())

    def test_all_checks_pass_and_ddl_ignores_only_trailing_newlines(self):
        self.check("check_generated.py")
        self.assertEqual(len(self.calls()), 7)
        for filename, content in self.files.items():
            self.assertEqual((self.root / filename).read_bytes(), content)

    def test_all_failures_are_reported_and_files_are_not_rewritten(self):
        for response in self.responses.values():
            response["status"] = 7
        output = self.check("check_generated.py", status=1)
        self.assertEqual(output.count("failed (exit 7)"), 7)
        self.assertEqual(len(self.calls()), 7)
        for filename, content in self.files.items():
            self.assertEqual((self.root / filename).read_bytes(), content)

    def test_matching_output_from_failed_generator_still_fails(self):
        self.responses["cargo xtask ddl --target remote"]["status"] = 7
        output = self.check("check_generated.py", "ddl", status=1)
        self.assertIn("failed (exit 7)", output)
        self.assertEqual(len(self.calls()), 3)

    def test_schema_compares_exact_bytes_and_ddl_reports_each_drift(self):
        schema = self.root / "config/schemas/config.schema.json"
        for content in (b'{}', b'{}\r\n'):
            with self.subTest(content=content):
                schema.write_bytes(content)
                self.assertIn("config.schema.json is out of date", self.check("check_generated.py", status=1))
                self.assertEqual(schema.read_bytes(), content)
        for filename in self.files:
            if filename.endswith(".sql"):
                with (self.root / filename).open("ab") as output:
                    output.write(b" ")
        output = self.check("check_generated.py", "ddl", status=1)
        self.assertEqual(output.count("is out of date"), 3)

    def test_ddl_selection_reports_bad_headers_and_missing_files_then_checks_remaining(self):
        self.write("config/graph.sql", "-- SCHEMA_VERSION=41\n")
        self.write("config/graph_persistent.sql", "-- no header\n")
        output = self.check("check_generated.py", "ddl", status=1)
        self.assertIn("pins schema: 42", output)
        self.assertIn("missing the AUTOGENERATED header", output)
        self.assertEqual(self.calls(), [["cargo", "xtask", "ddl", "--target", "local"]])
        (self.root / "config/graph.sql").unlink()
        self.assertIn("No such file", self.check("check_generated.py", "ddl", status=1))


class ToolchainChecksTests(RepositoryChecksTests):
    def setUp(self):
        super().setUp()
        self.write("mise.toml", '[tools]\nrust = {version = "1.98.1", components = "rustfmt, clippy"}\n')
        self.expected = (
            b"# Generated from mise.toml. Run: mise run toolchain:generate\n"
            b'[toolchain]\nchannel = "1.98.1"\ncomponents = ["rustfmt", "clippy"]\n'
        )

    def test_toolchain_check_write_and_missing_file(self):
        path = self.root / "rust-toolchain.toml"
        self.check("check-repository.py", "toolchain", status=1)
        self.assertFalse(path.exists())
        self.check("check-repository.py", "toolchain", "--write")
        self.assertEqual(path.read_bytes(), self.expected)
        self.check("check-repository.py", "toolchain")
        stale = self.expected.replace(b"\n", b"\r\n")
        path.write_bytes(stale)
        self.check("check-repository.py", "toolchain", status=1)
        self.assertEqual(path.read_bytes(), stale)
        self.check("check-repository.py", "toolchain", "--write")
        self.assertEqual(path.read_bytes(), self.expected)

    def test_all_checks_metadata_and_rejects_write(self):
        self.write("AGENTS.md", "agents\n")
        self.write("CLAUDE.md", "different\n")
        self.write("rust-toolchain.toml", "stale\n")
        output = self.check("check-repository.py", status=1)
        self.assertIn("must be identical", output)
        self.assertIn("Run mise toolchain:generate", output)
        self.check("check-repository.py", "--write", status=2)
        self.assertEqual((self.root / "rust-toolchain.toml").read_bytes(), b"stale\n")
        self.check("check-repository.py", "toolchain", "--write")
        self.write("CLAUDE.md", "agents\n")
        self.check("check-repository.py", "all")


class MigrationLedgerChecksTests(RepositoryChecksTests):
    def test_skip_environment_description_and_title_do_not_run_commands(self):
        for key, value in (
            ("SKIP_MIGRATION_LEDGER_CHECK", "1"),
            ("CI_MERGE_REQUEST_DESCRIPTION", "text [skip migration-ledger-check] text"),
            ("CI_MERGE_REQUEST_TITLE", "text [skip migration-ledger-check]"),
        ):
            with self.subTest(key=key):
                self.env[key] = value
                self.assertIn("skipping", self.check("check_migration_ledger.py"))
                del self.env[key]
        self.assertEqual(self.calls(), [])

    def test_default_base_git_failure_and_cargo_exit_status(self):
        self.env["SKIP_MIGRATION_LEDGER_CHECK"] = "true"
        self.responses = {
            "git log origin/main...HEAD --format=%B": {"status": 128},
            "cargo xtask migration-ledger check --base origin/main": {"status": 7},
        }
        self.check("check_migration_ledger.py", status=7)
        self.assertEqual(len(self.calls()), 2)

    def test_custom_base_and_commit_skip_survive_failed_fetch(self):
        self.env["CI_MERGE_REQUEST_DIFF_BASE_SHA"] = "abc123"
        self.responses = {
            "git fetch origin abc123 --depth=1": {"status": 1},
            "git log custom base...HEAD --format=%B": {"stdout": "message\n[skip migration-ledger-check]\n"},
        }
        self.check("check_migration_ledger.py", "--base", "custom base")
        self.assertEqual(self.calls(), [
            ["git", "fetch", "origin", "abc123", "--depth=1"],
            ["git", "log", "custom base...HEAD", "--format=%B"],
        ])

    def test_custom_base_is_forwarded_as_one_argument(self):
        self.responses = {
            "git log custom base...HEAD --format=%B": {},
            "cargo xtask migration-ledger check --base custom base": {},
        }
        self.check("check_migration_ledger.py", "--base", "custom base")
        self.assertEqual(self.calls()[-1], [
            "cargo", "xtask", "migration-ledger", "check", "--base", "custom base",
        ])


class SkipCheckTests(RepositoryChecksTests):
    def test_cli_maps_check_name_and_requires_literal_skip_controls(self):
        self.env.pop("BASE_REF", None)
        self.env["SKIP_CUSTOM_CHECK"] = "true"
        self.check("skip_check.py", "custom-check", status=1)
        self.env["SKIP_CUSTOM_CHECK"] = "1"
        self.check("skip_check.py", "custom-check")
        self.assertEqual(self.calls(), [])

    def test_empty_base_does_not_fetch_or_read_commit_messages(self):
        self.env.update(BASE_REF="", CI_MERGE_REQUEST_DIFF_BASE_SHA="abc123")
        self.check("skip_check.py", "custom-check", status=1)
        self.assertEqual(self.calls(), [])

    def test_cli_uses_exported_base_and_buffers_commit_messages(self):
        self.env.update(BASE_REF="custom base", CI_MERGE_REQUEST_DIFF_BASE_SHA="abc123")
        self.responses = {
            "git fetch origin abc123 --depth=1": {"status": 1},
            "git log custom base...HEAD --format=%B": {
                "stdout": "[skip custom-check]\n" + "later message\n" * 10000,
            },
        }
        self.check("skip_check.py", "custom-check")
        self.assertEqual(self.calls(), [
            ["git", "fetch", "origin", "abc123", "--depth=1"],
            ["git", "log", "custom base...HEAD", "--format=%B"],
        ])
