use std::collections::BTreeMap;

pub const DEFAULT_TRANSFORM: &str = "datafusion";

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum EtlScope {
    Global,
    Namespaced,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Pipeline {
    pub name: String,
    pub scope: EtlScope,
    pub extract: Extract,
    pub transform: Transform,
}

/// Where a pipeline's extract reads from and what it reads. ClickHouse is the
/// only source today; a future non-ClickHouse source adds a variant here.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Extract {
    ClickHouse(ClickHouseExtract),
}

/// Declarative extract: what to read. The ClickHouse SQL is generated by the
/// indexer from this model — the ontology never builds dialect SQL itself (the
/// `Sql` escape hatch carries authored SQL verbatim).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ClickHouseExtract {
    pub tables: Vec<String>,
    pub order_by: Vec<String>,
    pub watermark: String,
    pub deleted: String,
    pub query: ExtractQuery,
}

/// How the indexer obtains the extract SQL — the one place the Generated vs
/// authored split lives.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ExtractQuery {
    Generated {
        /// Extra `_batch` WHERE predicate (e.g. `state = 5`).
        filter: Option<String>,
    },
    /// Raw content of a co-located `.sql` file (escape hatch). Markers are
    /// substituted and validated by the indexer, not here.
    Sql(String),
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct ReindexSource {
    pub table: String,
    pub target: String,
    pub traversal_path: PathResolution,
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum PathResolution {
    Column(String),
    Dictionary {
        dictionary: String,
        key_column: String,
    },
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Transform {
    DataFusion { edges: Vec<EdgeMapping> },
    Rust(String),
}

impl Transform {
    pub fn edges(&self) -> &[EdgeMapping] {
        match self {
            Self::DataFusion { edges } => edges,
            Self::Rust(_) => &[],
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EdgeMapping {
    pub label: String,
    pub source: NodeRef,
    pub target: NodeRef,
    pub array_field: Option<String>,
    pub mutable: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NodeRef {
    pub field: String,
    pub kind: NodeRefKind,
    pub enrich: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum NodeRefKind {
    Literal(String),
    Derived {
        column: String,
        mapping: BTreeMap<String, String>,
    },
}
