#!/usr/bin/env bash
# Verify config/graph.sql, config/graph_local.sql, and
# config/graph_unversioned.sql match the ontology. The first two carry a
# SCHEMA_VERSION header; the unversioned file is version-agnostic by design.
set -euo pipefail

XTASK="${1:-cargo xtask}"
SCHEMA_VERSION=$(cat config/SCHEMA_VERSION | tr -d '[:space:]')
FAILED=0

check_file() {
    local cmd="$1"
    local file="$2"

    # Header must exist and match SCHEMA_VERSION.
    local header_version
    header_version=$(head -1 "$file" | grep -o 'SCHEMA_VERSION=[0-9]*' | grep -o '[0-9]*')
    if [ -z "$header_version" ]; then
        echo "❌ $file is missing the AUTOGENERATED header."
        FAILED=1
        return
    fi
    if [ "$header_version" != "$SCHEMA_VERSION" ]; then
        echo "❌ $file header says SCHEMA_VERSION=$header_version but config/SCHEMA_VERSION is $SCHEMA_VERSION."
        FAILED=1
        return
    fi

    # Content must match what the generator produces.
    local generated
    generated=$(eval "$cmd" 2>/dev/null)
    if ! diff -q <(printf '%s' "$generated") <(printf '%s' "$(cat "$file")") >/dev/null 2>&1; then
        echo "❌ $file is out of date. Run: mise schema:generate:ddl"
        FAILED=1
    else
        echo "✅ $file is up to date (SCHEMA_VERSION=$SCHEMA_VERSION)."
    fi
}

check_versionless_file() {
    local cmd="$1"
    local file="$2"

    if ! head -1 "$file" | grep -q 'AUTOGENERATED'; then
        echo "❌ $file is missing the AUTOGENERATED header."
        FAILED=1
        return
    fi

    local generated
    generated=$(eval "$cmd" 2>/dev/null)
    if ! diff -q <(printf '%s' "$generated") <(printf '%s' "$(cat "$file")") >/dev/null 2>&1; then
        echo "❌ $file is out of date. Run: mise schema:generate:ddl"
        FAILED=1
    else
        echo "✅ $file is up to date."
    fi
}

check_file "$XTASK ddl --target remote" "config/graph.sql"
check_file "$XTASK ddl --target local" "config/graph_local.sql"
check_versionless_file "$XTASK ddl --target unversioned" "config/graph_unversioned.sql"

exit $FAILED
