[package]
name = "tree-dsl-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
tree-dsl = { path = "../tree-dsl" }
tree-dsl-tests = { path = "../tree-dsl-tests" }
clap = { workspace = true }
serde_yaml = { workspace = true }
anyhow = { workspace = true }
walkdir = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[[bin]]
name = "tree-dsl"
path = "src/main.rs"
