[package]
name = "tree-dsl-tests"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
tree-dsl = { path = "../tree-dsl" }
integration-tests-codegraph = { path = "../integration-tests-codegraph" }
ontology = { path = "../ontology" }
orbit-utils = { path = "../utils" }
walkdir = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
