//! Generates the Siphon datalake column-name constants from the ontology.
//!
//! Reads `ONTOLOGY_DIR/schema.yaml` and emits `OUT_DIR/siphon_columns.rs`
//! with `SIPHON_WATERMARK_COLUMN` and `SIPHON_DELETED_COLUMN` consts taken
//! from `settings.etl.default_watermark` / `settings.etl.default_deleted`.
//! `schema.yaml` is the single source of truth; the consts are derived from
//! it at build time so the indexer's compile-time `concatcp!` SQL and the
//! runtime ontology loader can never disagree.

use std::fs;
use std::path::PathBuf;

use serde_yaml::Value;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let ontology_dir = PathBuf::from(std::env::var("ONTOLOGY_DIR").unwrap_or_else(|_| {
        panic!("ONTOLOGY_DIR must be set via .cargo/config.toml [env] when building ontology")
    }));
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));

    let schema_path = ontology_dir.join("schema.yaml");
    println!("cargo:rerun-if-changed={}", schema_path.display());

    let schema_raw = fs::read_to_string(&schema_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", schema_path.display()));
    let schema: Value = serde_yaml::from_str(&schema_raw)
        .unwrap_or_else(|e| panic!("parse {}: {e}", schema_path.display()));

    let etl = &schema["settings"]["etl"];
    let watermark = required_str(etl, "default_watermark", &schema_path);
    let deleted = required_str(etl, "default_deleted", &schema_path);

    let emitted = format!(
        "// @generated by build.rs from config/ontology/schema.yaml - do not edit\n\
         \n\
         /// Siphon datalake watermark column used for `argMax` deduplication and\n\
         /// incremental-pull windowing. Derived from `schema.yaml`'s\n\
         /// `settings.etl.default_watermark`.\n\
         pub const SIPHON_WATERMARK_COLUMN: &str = {watermark:?};\n\
         \n\
         /// Siphon datalake soft-delete flag column. Derived from `schema.yaml`'s\n\
         /// `settings.etl.default_deleted`.\n\
         pub const SIPHON_DELETED_COLUMN: &str = {deleted:?};\n"
    );

    fs::write(out_dir.join("siphon_columns.rs"), emitted)
        .expect("write generated siphon_columns.rs");
}

fn required_str<'a>(node: &'a Value, key: &str, path: &std::path::Path) -> &'a str {
    node[key]
        .as_str()
        .unwrap_or_else(|| panic!("{}: settings.etl.{key} must be a string", path.display()))
}
