[package]
name = "ontology"
version.workspace = true
edition = "2024"

[dependencies]
const_format = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
minijinja = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
orbit-utils = { path = "../utils" }
sha2 = { workspace = true }
rust-embed = { workspace = true, features = ["include-exclude"] }
strum = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
