[package]
name = "integration-tests-codegraph"
version.workspace = true
edition = "2024"
publish = false

[dependencies]
code-graph = { path = "../code-graph" }
compiler = { path = "../query-engine/compiler" }
duckdb-client = { path = "../duckdb-client" }
ontology = { path = "../ontology" }

arrow = { workspace = true }

crossbeam-channel = "0.5"
globset = { workspace = true }
rayon = { workspace = true }
petgraph = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
orbit-utils = { path = "../utils" }
tabled = { workspace = true }
anyhow = { workspace = true }
tempfile = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
