// GitLab Knowledge Graph gRPC service definition.
//
// Serves the Orbit dashboard, MCP agents, and glab CLI.
// All data RPCs accept a ResponseFormat to switch between structured JSON (RAW)
// and token-efficient text (LLM) for AI consumers.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: gkg.proto

package gkgpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Controls output serialization across all data RPCs.
// RAW returns structured JSON for programmatic consumers (dashboard, CLI).
// LLM returns compact text (GOON for queries, TOON for schema/health) optimized for token budgets.
type ResponseFormat int32

const (
	ResponseFormat_RESPONSE_FORMAT_RAW ResponseFormat = 0
	ResponseFormat_RESPONSE_FORMAT_LLM ResponseFormat = 1
)

// Enum value maps for ResponseFormat.
var (
	ResponseFormat_name = map[int32]string{
		0: "RESPONSE_FORMAT_RAW",
		1: "RESPONSE_FORMAT_LLM",
	}
	ResponseFormat_value = map[string]int32{
		"RESPONSE_FORMAT_RAW": 0,
		"RESPONSE_FORMAT_LLM": 1,
	}
)

func (x ResponseFormat) Enum() *ResponseFormat {
	p := new(ResponseFormat)
	*p = x
	return p
}

func (x ResponseFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_gkg_proto_enumTypes[0].Descriptor()
}

func (ResponseFormat) Type() protoreflect.EnumType {
	return &file_gkg_proto_enumTypes[0]
}

func (x ResponseFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseFormat.Descriptor instead.
func (ResponseFormat) EnumDescriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{0}
}

// Concrete encoding produced by the server. QueryMetadata carries this
// alongside format_version so consumers can route/parse without inspecting
// the payload body. UNSPECIFIED is reserved for stubs that do not yet
// emit a tagged format.
type FormatName int32

const (
	FormatName_FORMAT_NAME_UNSPECIFIED FormatName = 0
	FormatName_FORMAT_NAME_RAW         FormatName = 1
	FormatName_FORMAT_NAME_GOON        FormatName = 2
	FormatName_FORMAT_NAME_TOON        FormatName = 3
)

// Enum value maps for FormatName.
var (
	FormatName_name = map[int32]string{
		0: "FORMAT_NAME_UNSPECIFIED",
		1: "FORMAT_NAME_RAW",
		2: "FORMAT_NAME_GOON",
		3: "FORMAT_NAME_TOON",
	}
	FormatName_value = map[string]int32{
		"FORMAT_NAME_UNSPECIFIED": 0,
		"FORMAT_NAME_RAW":         1,
		"FORMAT_NAME_GOON":        2,
		"FORMAT_NAME_TOON":        3,
	}
)

func (x FormatName) Enum() *FormatName {
	p := new(FormatName)
	*p = x
	return p
}

func (x FormatName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FormatName) Descriptor() protoreflect.EnumDescriptor {
	return file_gkg_proto_enumTypes[1].Descriptor()
}

func (FormatName) Type() protoreflect.EnumType {
	return &file_gkg_proto_enumTypes[1]
}

func (x FormatName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FormatName.Descriptor instead.
func (FormatName) EnumDescriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{1}
}

// Query language selector. Only JSON DSL is supported today.
type QueryType int32

const (
	QueryType_QUERY_TYPE_JSON QueryType = 0
)

// Enum value maps for QueryType.
var (
	QueryType_name = map[int32]string{
		0: "QUERY_TYPE_JSON",
	}
	QueryType_value = map[string]int32{
		"QUERY_TYPE_JSON": 0,
	}
)

func (x QueryType) Enum() *QueryType {
	p := new(QueryType)
	*p = x
	return p
}

func (x QueryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryType) Descriptor() protoreflect.EnumDescriptor {
	return file_gkg_proto_enumTypes[2].Descriptor()
}

func (QueryType) Type() protoreflect.EnumType {
	return &file_gkg_proto_enumTypes[2]
}

func (x QueryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryType.Descriptor instead.
func (QueryType) EnumDescriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{2}
}

type ClusterStatus int32

const (
	ClusterStatus_CLUSTER_STATUS_UNSPECIFIED ClusterStatus = 0
	ClusterStatus_CLUSTER_STATUS_HEALTHY     ClusterStatus = 1
	ClusterStatus_CLUSTER_STATUS_DEGRADED    ClusterStatus = 2
	ClusterStatus_CLUSTER_STATUS_UNHEALTHY   ClusterStatus = 3
)

// Enum value maps for ClusterStatus.
var (
	ClusterStatus_name = map[int32]string{
		0: "CLUSTER_STATUS_UNSPECIFIED",
		1: "CLUSTER_STATUS_HEALTHY",
		2: "CLUSTER_STATUS_DEGRADED",
		3: "CLUSTER_STATUS_UNHEALTHY",
	}
	ClusterStatus_value = map[string]int32{
		"CLUSTER_STATUS_UNSPECIFIED": 0,
		"CLUSTER_STATUS_HEALTHY":     1,
		"CLUSTER_STATUS_DEGRADED":    2,
		"CLUSTER_STATUS_UNHEALTHY":   3,
	}
)

func (x ClusterStatus) Enum() *ClusterStatus {
	p := new(ClusterStatus)
	*p = x
	return p
}

func (x ClusterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gkg_proto_enumTypes[3].Descriptor()
}

func (ClusterStatus) Type() protoreflect.EnumType {
	return &file_gkg_proto_enumTypes[3]
}

func (x ClusterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterStatus.Descriptor instead.
func (ClusterStatus) EnumDescriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{3}
}

// Envelope for the execute_query stream. Each message carries exactly one of:
// request (client initial), redaction exchange (server/client), result, or error.
type ExecuteQueryMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*ExecuteQueryMessage_Request
	//	*ExecuteQueryMessage_Redaction
	//	*ExecuteQueryMessage_Result
	//	*ExecuteQueryMessage_Error
	Content       isExecuteQueryMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryMessage) Reset() {
	*x = ExecuteQueryMessage{}
	mi := &file_gkg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryMessage) ProtoMessage() {}

func (x *ExecuteQueryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryMessage.ProtoReflect.Descriptor instead.
func (*ExecuteQueryMessage) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteQueryMessage) GetContent() isExecuteQueryMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ExecuteQueryMessage) GetRequest() *ExecuteQueryRequest {
	if x != nil {
		if x, ok := x.Content.(*ExecuteQueryMessage_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *ExecuteQueryMessage) GetRedaction() *RedactionExchange {
	if x != nil {
		if x, ok := x.Content.(*ExecuteQueryMessage_Redaction); ok {
			return x.Redaction
		}
	}
	return nil
}

func (x *ExecuteQueryMessage) GetResult() *ExecuteQueryResult {
	if x != nil {
		if x, ok := x.Content.(*ExecuteQueryMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ExecuteQueryMessage) GetError() *ExecuteQueryError {
	if x != nil {
		if x, ok := x.Content.(*ExecuteQueryMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isExecuteQueryMessage_Content interface {
	isExecuteQueryMessage_Content()
}

type ExecuteQueryMessage_Request struct {
	Request *ExecuteQueryRequest `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type ExecuteQueryMessage_Redaction struct {
	Redaction *RedactionExchange `protobuf:"bytes,2,opt,name=redaction,proto3,oneof"`
}

type ExecuteQueryMessage_Result struct {
	Result *ExecuteQueryResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

type ExecuteQueryMessage_Error struct {
	Error *ExecuteQueryError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*ExecuteQueryMessage_Request) isExecuteQueryMessage_Content() {}

func (*ExecuteQueryMessage_Redaction) isExecuteQueryMessage_Content() {}

func (*ExecuteQueryMessage_Result) isExecuteQueryMessage_Content() {}

func (*ExecuteQueryMessage_Error) isExecuteQueryMessage_Content() {}

// Client-sent initial message to start a query.
type ExecuteQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                                                 // JSON DSL query string
	Format        ResponseFormat         `protobuf:"varint,2,opt,name=format,proto3,enum=gkg.v1.ResponseFormat" json:"format,omitempty"`                   // RAW: tabular JSON rows; LLM: GOON text
	QueryType     QueryType              `protobuf:"varint,3,opt,name=query_type,json=queryType,proto3,enum=gkg.v1.QueryType" json:"query_type,omitempty"` // defaults to JSON DSL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryRequest) Reset() {
	*x = ExecuteQueryRequest{}
	mi := &file_gkg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryRequest) ProtoMessage() {}

func (x *ExecuteQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteQueryRequest) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ExecuteQueryRequest) GetFormat() ResponseFormat {
	if x != nil {
		return x.Format
	}
	return ResponseFormat_RESPONSE_FORMAT_RAW
}

func (x *ExecuteQueryRequest) GetQueryType() QueryType {
	if x != nil {
		return x.QueryType
	}
	return QueryType_QUERY_TYPE_JSON
}

// Server-sent final message with query results.
type ExecuteQueryResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*ExecuteQueryResult_ResultJson
	//	*ExecuteQueryResult_FormattedText
	Content       isExecuteQueryResult_Content `protobuf_oneof:"content"`
	Metadata      *QueryMetadata               `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryResult) Reset() {
	*x = ExecuteQueryResult{}
	mi := &file_gkg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryResult) ProtoMessage() {}

func (x *ExecuteQueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryResult.ProtoReflect.Descriptor instead.
func (*ExecuteQueryResult) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteQueryResult) GetContent() isExecuteQueryResult_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ExecuteQueryResult) GetResultJson() string {
	if x != nil {
		if x, ok := x.Content.(*ExecuteQueryResult_ResultJson); ok {
			return x.ResultJson
		}
	}
	return ""
}

func (x *ExecuteQueryResult) GetFormattedText() string {
	if x != nil {
		if x, ok := x.Content.(*ExecuteQueryResult_FormattedText); ok {
			return x.FormattedText
		}
	}
	return ""
}

func (x *ExecuteQueryResult) GetMetadata() *QueryMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isExecuteQueryResult_Content interface {
	isExecuteQueryResult_Content()
}

type ExecuteQueryResult_ResultJson struct {
	ResultJson string `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3,oneof"` // format = RAW: structured JSON
}

type ExecuteQueryResult_FormattedText struct {
	FormattedText string `protobuf:"bytes,2,opt,name=formatted_text,json=formattedText,proto3,oneof"` // format = LLM: compact text
}

func (*ExecuteQueryResult_ResultJson) isExecuteQueryResult_Content() {}

func (*ExecuteQueryResult_FormattedText) isExecuteQueryResult_Content() {}

type QueryMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	QueryType       string                 `protobuf:"bytes,1,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`                     // e.g. "traversal", "aggregation", "search"
	RawQueryStrings []string               `protobuf:"bytes,2,rep,name=raw_query_strings,json=rawQueryStrings,proto3" json:"raw_query_strings,omitempty"` // compiled ClickHouse SQL(s) for debugging
	RowCount        int32                  `protobuf:"varint,3,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`                       // rows returned after redaction (and cursor slicing if applicable)
	FormatVersion   string                 `protobuf:"bytes,4,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`         // semver string, e.g. "1.0.0"; empty when FORMAT_NAME_UNSPECIFIED
	FormatName      FormatName             `protobuf:"varint,5,opt,name=format_name,json=formatName,proto3,enum=gkg.v1.FormatName" json:"format_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryMetadata) Reset() {
	*x = QueryMetadata{}
	mi := &file_gkg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetadata) ProtoMessage() {}

func (x *QueryMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetadata.ProtoReflect.Descriptor instead.
func (*QueryMetadata) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{3}
}

func (x *QueryMetadata) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

func (x *QueryMetadata) GetRawQueryStrings() []string {
	if x != nil {
		return x.RawQueryStrings
	}
	return nil
}

func (x *QueryMetadata) GetRowCount() int32 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *QueryMetadata) GetFormatVersion() string {
	if x != nil {
		return x.FormatVersion
	}
	return ""
}

func (x *QueryMetadata) GetFormatName() FormatName {
	if x != nil {
		return x.FormatName
	}
	return FormatName_FORMAT_NAME_UNSPECIFIED
}

// Server-sent error when query compilation or execution fails.
type ExecuteQueryError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"` // e.g. "compile_error", "execution_error"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryError) Reset() {
	*x = ExecuteQueryError{}
	mi := &file_gkg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryError) ProtoMessage() {}

func (x *ExecuteQueryError) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryError.ProtoReflect.Descriptor instead.
func (*ExecuteQueryError) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteQueryError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteQueryError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// Request to retrieve the graph schema with optional node expansion.
type GetGraphSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpandNodes   []string               `protobuf:"bytes,1,rep,name=expand_nodes,json=expandNodes,proto3" json:"expand_nodes,omitempty"` // node names to include full properties/relationships; pass "*" to expand all
	Format        ResponseFormat         `protobuf:"varint,2,opt,name=format,proto3,enum=gkg.v1.ResponseFormat" json:"format,omitempty"`  // RAW: StructuredSchema; LLM: TOON text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphSchemaRequest) Reset() {
	*x = GetGraphSchemaRequest{}
	mi := &file_gkg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphSchemaRequest) ProtoMessage() {}

func (x *GetGraphSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetGraphSchemaRequest) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{5}
}

func (x *GetGraphSchemaRequest) GetExpandNodes() []string {
	if x != nil {
		return x.ExpandNodes
	}
	return nil
}

func (x *GetGraphSchemaRequest) GetFormat() ResponseFormat {
	if x != nil {
		return x.Format
	}
	return ResponseFormat_RESPONSE_FORMAT_RAW
}

// Schema response — exactly one of structured or text depending on format.
type GetGraphSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*GetGraphSchemaResponse_Structured
	//	*GetGraphSchemaResponse_FormattedText
	Content       isGetGraphSchemaResponse_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphSchemaResponse) Reset() {
	*x = GetGraphSchemaResponse{}
	mi := &file_gkg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphSchemaResponse) ProtoMessage() {}

func (x *GetGraphSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetGraphSchemaResponse) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{6}
}

func (x *GetGraphSchemaResponse) GetContent() isGetGraphSchemaResponse_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GetGraphSchemaResponse) GetStructured() *StructuredSchema {
	if x != nil {
		if x, ok := x.Content.(*GetGraphSchemaResponse_Structured); ok {
			return x.Structured
		}
	}
	return nil
}

func (x *GetGraphSchemaResponse) GetFormattedText() string {
	if x != nil {
		if x, ok := x.Content.(*GetGraphSchemaResponse_FormattedText); ok {
			return x.FormattedText
		}
	}
	return ""
}

type isGetGraphSchemaResponse_Content interface {
	isGetGraphSchemaResponse_Content()
}

type GetGraphSchemaResponse_Structured struct {
	Structured *StructuredSchema `protobuf:"bytes,1,opt,name=structured,proto3,oneof"` // format = RAW
}

type GetGraphSchemaResponse_FormattedText struct {
	FormattedText string `protobuf:"bytes,2,opt,name=formatted_text,json=formattedText,proto3,oneof"` // format = LLM (TOON notation)
}

func (*GetGraphSchemaResponse_Structured) isGetGraphSchemaResponse_Content() {}

func (*GetGraphSchemaResponse_FormattedText) isGetGraphSchemaResponse_Content() {}

// Full structured schema with domains, nodes, and edges.
type StructuredSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Domains       []*SchemaDomain        `protobuf:"bytes,2,rep,name=domains,proto3" json:"domains,omitempty"`
	Nodes         []*SchemaNode          `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*SchemaEdge          `protobuf:"bytes,4,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructuredSchema) Reset() {
	*x = StructuredSchema{}
	mi := &file_gkg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructuredSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructuredSchema) ProtoMessage() {}

func (x *StructuredSchema) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructuredSchema.ProtoReflect.Descriptor instead.
func (*StructuredSchema) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{7}
}

func (x *StructuredSchema) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *StructuredSchema) GetDomains() []*SchemaDomain {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *StructuredSchema) GetNodes() []*SchemaNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *StructuredSchema) GetEdges() []*SchemaEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

// Logical grouping of related node types (e.g. "ci", "core", "plan").
type SchemaDomain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	NodeNames     []string               `protobuf:"bytes,3,rep,name=node_names,json=nodeNames,proto3" json:"node_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaDomain) Reset() {
	*x = SchemaDomain{}
	mi := &file_gkg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaDomain) ProtoMessage() {}

func (x *SchemaDomain) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaDomain.ProtoReflect.Descriptor instead.
func (*SchemaDomain) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{8}
}

func (x *SchemaDomain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaDomain) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SchemaDomain) GetNodeNames() []string {
	if x != nil {
		return x.NodeNames
	}
	return nil
}

// A node type in the ontology. Properties, style, and edges are only
// populated when the node name appears in expand_nodes.
type SchemaNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PrimaryKey    string                 `protobuf:"bytes,4,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	LabelField    string                 `protobuf:"bytes,5,opt,name=label_field,json=labelField,proto3" json:"label_field,omitempty"`
	Properties    []*SchemaProperty      `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty"`                            // populated when expanded
	Style         *SchemaNodeStyle       `protobuf:"bytes,7,opt,name=style,proto3" json:"style,omitempty"`                                      // populated when expanded
	OutgoingEdges []string               `protobuf:"bytes,8,rep,name=outgoing_edges,json=outgoingEdges,proto3" json:"outgoing_edges,omitempty"` // populated when expanded
	IncomingEdges []string               `protobuf:"bytes,9,rep,name=incoming_edges,json=incomingEdges,proto3" json:"incoming_edges,omitempty"` // populated when expanded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaNode) Reset() {
	*x = SchemaNode{}
	mi := &file_gkg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaNode) ProtoMessage() {}

func (x *SchemaNode) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaNode.ProtoReflect.Descriptor instead.
func (*SchemaNode) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{9}
}

func (x *SchemaNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaNode) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *SchemaNode) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SchemaNode) GetPrimaryKey() string {
	if x != nil {
		return x.PrimaryKey
	}
	return ""
}

func (x *SchemaNode) GetLabelField() string {
	if x != nil {
		return x.LabelField
	}
	return ""
}

func (x *SchemaNode) GetProperties() []*SchemaProperty {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *SchemaNode) GetStyle() *SchemaNodeStyle {
	if x != nil {
		return x.Style
	}
	return nil
}

func (x *SchemaNode) GetOutgoingEdges() []string {
	if x != nil {
		return x.OutgoingEdges
	}
	return nil
}

func (x *SchemaNode) GetIncomingEdges() []string {
	if x != nil {
		return x.IncomingEdges
	}
	return nil
}

// A single property on a node type.
type SchemaProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DataType      string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"` // e.g. "int64", "string", "datetime"
	Nullable      bool                   `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	EnumValues    []string               `protobuf:"bytes,4,rep,name=enum_values,json=enumValues,proto3" json:"enum_values,omitempty"` // allowed values for enum-typed properties
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaProperty) Reset() {
	*x = SchemaProperty{}
	mi := &file_gkg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaProperty) ProtoMessage() {}

func (x *SchemaProperty) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaProperty.ProtoReflect.Descriptor instead.
func (*SchemaProperty) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{10}
}

func (x *SchemaProperty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaProperty) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *SchemaProperty) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *SchemaProperty) GetEnumValues() []string {
	if x != nil {
		return x.EnumValues
	}
	return nil
}

// A named relationship type with its valid source/target combinations.
type SchemaEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // e.g. "AUTHORED", "CONTAINS", "MEMBER_OF"
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Variants      []*SchemaEdgeVariant   `protobuf:"bytes,3,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaEdge) Reset() {
	*x = SchemaEdge{}
	mi := &file_gkg_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaEdge) ProtoMessage() {}

func (x *SchemaEdge) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaEdge.ProtoReflect.Descriptor instead.
func (*SchemaEdge) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{11}
}

func (x *SchemaEdge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaEdge) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SchemaEdge) GetVariants() []*SchemaEdgeVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

// One valid source->target pair for an edge type.
type SchemaEdgeVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceType    string                 `protobuf:"bytes,1,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	TargetType    string                 `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaEdgeVariant) Reset() {
	*x = SchemaEdgeVariant{}
	mi := &file_gkg_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaEdgeVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaEdgeVariant) ProtoMessage() {}

func (x *SchemaEdgeVariant) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaEdgeVariant.ProtoReflect.Descriptor instead.
func (*SchemaEdgeVariant) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{12}
}

func (x *SchemaEdgeVariant) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *SchemaEdgeVariant) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

// Visual styling hints for graph rendering (Three.js dashboard).
type SchemaNodeStyle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int32                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`  // relative node size in the graph visualization
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"` // hex color, e.g. "#6366f1"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaNodeStyle) Reset() {
	*x = SchemaNodeStyle{}
	mi := &file_gkg_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaNodeStyle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaNodeStyle) ProtoMessage() {}

func (x *SchemaNodeStyle) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaNodeStyle.ProtoReflect.Descriptor instead.
func (*SchemaNodeStyle) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{13}
}

func (x *SchemaNodeStyle) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SchemaNodeStyle) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

// Wrapper for the redaction handshake within a streaming query.
// Server sends `required` with resources to check, client responds with decisions.
type RedactionExchange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*RedactionExchange_Required
	//	*RedactionExchange_Response
	Content       isRedactionExchange_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedactionExchange) Reset() {
	*x = RedactionExchange{}
	mi := &file_gkg_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedactionExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedactionExchange) ProtoMessage() {}

func (x *RedactionExchange) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedactionExchange.ProtoReflect.Descriptor instead.
func (*RedactionExchange) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{14}
}

func (x *RedactionExchange) GetContent() isRedactionExchange_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *RedactionExchange) GetRequired() *RedactionRequired {
	if x != nil {
		if x, ok := x.Content.(*RedactionExchange_Required); ok {
			return x.Required
		}
	}
	return nil
}

func (x *RedactionExchange) GetResponse() *RedactionResponse {
	if x != nil {
		if x, ok := x.Content.(*RedactionExchange_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isRedactionExchange_Content interface {
	isRedactionExchange_Content()
}

type RedactionExchange_Required struct {
	Required *RedactionRequired `protobuf:"bytes,1,opt,name=required,proto3,oneof"` // server -> client
}

type RedactionExchange_Response struct {
	Response *RedactionResponse `protobuf:"bytes,2,opt,name=response,proto3,oneof"` // client -> server
}

func (*RedactionExchange_Required) isRedactionExchange_Content() {}

func (*RedactionExchange_Response) isRedactionExchange_Content() {}

// Server asks Rails to authorize a set of resources before returning results.
type RedactionRequired struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultId      string                 `protobuf:"bytes,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"` // correlates request with response
	Resources     []*ResourceToAuthorize `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedactionRequired) Reset() {
	*x = RedactionRequired{}
	mi := &file_gkg_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedactionRequired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedactionRequired) ProtoMessage() {}

func (x *RedactionRequired) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedactionRequired.ProtoReflect.Descriptor instead.
func (*RedactionRequired) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{15}
}

func (x *RedactionRequired) GetResultId() string {
	if x != nil {
		return x.ResultId
	}
	return ""
}

func (x *RedactionRequired) GetResources() []*ResourceToAuthorize {
	if x != nil {
		return x.Resources
	}
	return nil
}

// A batch of resource IDs that need authorization checks.
type ResourceToAuthorize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // e.g. "project", "merge_request"
	ResourceIds   []int64                `protobuf:"varint,2,rep,packed,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	Abilities     []string               `protobuf:"bytes,3,rep,name=abilities,proto3" json:"abilities,omitempty"` // e.g. ["read_project"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceToAuthorize) Reset() {
	*x = ResourceToAuthorize{}
	mi := &file_gkg_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceToAuthorize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceToAuthorize) ProtoMessage() {}

func (x *ResourceToAuthorize) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceToAuthorize.ProtoReflect.Descriptor instead.
func (*ResourceToAuthorize) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{16}
}

func (x *ResourceToAuthorize) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ResourceToAuthorize) GetResourceIds() []int64 {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

func (x *ResourceToAuthorize) GetAbilities() []string {
	if x != nil {
		return x.Abilities
	}
	return nil
}

// Rails responds with per-resource authorization decisions.
type RedactionResponse struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	ResultId       string                   `protobuf:"bytes,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	Authorizations []*ResourceAuthorization `protobuf:"bytes,2,rep,name=authorizations,proto3" json:"authorizations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RedactionResponse) Reset() {
	*x = RedactionResponse{}
	mi := &file_gkg_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedactionResponse) ProtoMessage() {}

func (x *RedactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedactionResponse.ProtoReflect.Descriptor instead.
func (*RedactionResponse) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{17}
}

func (x *RedactionResponse) GetResultId() string {
	if x != nil {
		return x.ResultId
	}
	return ""
}

func (x *RedactionResponse) GetAuthorizations() []*ResourceAuthorization {
	if x != nil {
		return x.Authorizations
	}
	return nil
}

// Authorization decisions for one resource type. Keys are resource IDs,
// values are true (authorized) or false (redact).
type ResourceAuthorization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Authorized    map[int64]bool         `protobuf:"bytes,2,rep,name=authorized,proto3" json:"authorized,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceAuthorization) Reset() {
	*x = ResourceAuthorization{}
	mi := &file_gkg_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceAuthorization) ProtoMessage() {}

func (x *ResourceAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceAuthorization.ProtoReflect.Descriptor instead.
func (*ResourceAuthorization) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{18}
}

func (x *ResourceAuthorization) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ResourceAuthorization) GetAuthorized() map[int64]bool {
	if x != nil {
		return x.Authorized
	}
	return nil
}

type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_gkg_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{19}
}

type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolDefinition      `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_gkg_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{20}
}

func (x *ListToolsResponse) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

// An MCP-compatible tool definition. The Rust service is the single source of
// truth for tool metadata — Rails passes these through to MCP and REST consumers.
type ToolDefinition struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                               // e.g. "query_graph", "get_graph_schema"
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                                                 // includes TOON schema context for query_graph
	ParametersJsonSchema string                 `protobuf:"bytes,3,opt,name=parameters_json_schema,json=parametersJsonSchema,proto3" json:"parameters_json_schema,omitempty"` // JSON Schema for the tool's input parameters
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_gkg_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{21}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetParametersJsonSchema() string {
	if x != nil {
		return x.ParametersJsonSchema
	}
	return ""
}

// Request for cluster health, with optional LLM formatting.
type GetClusterHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        ResponseFormat         `protobuf:"varint,1,opt,name=format,proto3,enum=gkg.v1.ResponseFormat" json:"format,omitempty"` // RAW: structured JSON; LLM: TOON text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterHealthRequest) Reset() {
	*x = GetClusterHealthRequest{}
	mi := &file_gkg_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterHealthRequest) ProtoMessage() {}

func (x *GetClusterHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterHealthRequest.ProtoReflect.Descriptor instead.
func (*GetClusterHealthRequest) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{22}
}

func (x *GetClusterHealthRequest) GetFormat() ResponseFormat {
	if x != nil {
		return x.Format
	}
	return ResponseFormat_RESPONSE_FORMAT_RAW
}

// Health response — structured or TOON text depending on format.
type GetClusterHealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*GetClusterHealthResponse_Structured
	//	*GetClusterHealthResponse_FormattedText
	Content       isGetClusterHealthResponse_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterHealthResponse) Reset() {
	*x = GetClusterHealthResponse{}
	mi := &file_gkg_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterHealthResponse) ProtoMessage() {}

func (x *GetClusterHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterHealthResponse.ProtoReflect.Descriptor instead.
func (*GetClusterHealthResponse) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{23}
}

func (x *GetClusterHealthResponse) GetContent() isGetClusterHealthResponse_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GetClusterHealthResponse) GetStructured() *StructuredClusterHealth {
	if x != nil {
		if x, ok := x.Content.(*GetClusterHealthResponse_Structured); ok {
			return x.Structured
		}
	}
	return nil
}

func (x *GetClusterHealthResponse) GetFormattedText() string {
	if x != nil {
		if x, ok := x.Content.(*GetClusterHealthResponse_FormattedText); ok {
			return x.FormattedText
		}
	}
	return ""
}

type isGetClusterHealthResponse_Content interface {
	isGetClusterHealthResponse_Content()
}

type GetClusterHealthResponse_Structured struct {
	Structured *StructuredClusterHealth `protobuf:"bytes,1,opt,name=structured,proto3,oneof"` // format = RAW
}

type GetClusterHealthResponse_FormattedText struct {
	FormattedText string `protobuf:"bytes,2,opt,name=formatted_text,json=formattedText,proto3,oneof"` // format = LLM
}

func (*GetClusterHealthResponse_Structured) isGetClusterHealthResponse_Content() {}

func (*GetClusterHealthResponse_FormattedText) isGetClusterHealthResponse_Content() {}

// Structured cluster health with per-component breakdown.
type StructuredClusterHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ClusterStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=gkg.v1.ClusterStatus" json:"status,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Components    []*ComponentHealth     `protobuf:"bytes,4,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructuredClusterHealth) Reset() {
	*x = StructuredClusterHealth{}
	mi := &file_gkg_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructuredClusterHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructuredClusterHealth) ProtoMessage() {}

func (x *StructuredClusterHealth) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructuredClusterHealth.ProtoReflect.Descriptor instead.
func (*StructuredClusterHealth) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{24}
}

func (x *StructuredClusterHealth) GetStatus() ClusterStatus {
	if x != nil {
		return x.Status
	}
	return ClusterStatus_CLUSTER_STATUS_UNSPECIFIED
}

func (x *StructuredClusterHealth) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *StructuredClusterHealth) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StructuredClusterHealth) GetComponents() []*ComponentHealth {
	if x != nil {
		return x.Components
	}
	return nil
}

// Health of a single service component (clickhouse, indexer, webserver).
type ComponentHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        ClusterStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=gkg.v1.ClusterStatus" json:"status,omitempty"`
	Replicas      *ReplicaStatus         `protobuf:"bytes,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Metrics       map[string]string      `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // component-specific metrics (e.g. query_latency_p99_ms)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentHealth) Reset() {
	*x = ComponentHealth{}
	mi := &file_gkg_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentHealth) ProtoMessage() {}

func (x *ComponentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentHealth.ProtoReflect.Descriptor instead.
func (*ComponentHealth) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{25}
}

func (x *ComponentHealth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentHealth) GetStatus() ClusterStatus {
	if x != nil {
		return x.Status
	}
	return ClusterStatus_CLUSTER_STATUS_UNSPECIFIED
}

func (x *ComponentHealth) GetReplicas() *ReplicaStatus {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *ComponentHealth) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ReplicaStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         int32                  `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Desired       int32                  `protobuf:"varint,2,opt,name=desired,proto3" json:"desired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaStatus) Reset() {
	*x = ReplicaStatus{}
	mi := &file_gkg_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaStatus) ProtoMessage() {}

func (x *ReplicaStatus) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaStatus.ProtoReflect.Descriptor instead.
func (*ReplicaStatus) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{26}
}

func (x *ReplicaStatus) GetReady() int32 {
	if x != nil {
		return x.Ready
	}
	return 0
}

func (x *ReplicaStatus) GetDesired() int32 {
	if x != nil {
		return x.Desired
	}
	return 0
}

// Request for graph entity counts scoped by traversal_path prefix.
type GetGraphStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraversalPath string                 `protobuf:"bytes,1,opt,name=traversal_path,json=traversalPath,proto3" json:"traversal_path,omitempty"` // traversal_path prefix to scope counts (e.g. "1/2/")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphStatsRequest) Reset() {
	*x = GetGraphStatsRequest{}
	mi := &file_gkg_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphStatsRequest) ProtoMessage() {}

func (x *GetGraphStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphStatsRequest.ProtoReflect.Descriptor instead.
func (*GetGraphStatsRequest) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{27}
}

func (x *GetGraphStatsRequest) GetTraversalPath() string {
	if x != nil {
		return x.TraversalPath
	}
	return ""
}

// Response containing entity counts grouped by domain.
type GetGraphStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []*GraphStatsDomain    `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphStatsResponse) Reset() {
	*x = GetGraphStatsResponse{}
	mi := &file_gkg_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphStatsResponse) ProtoMessage() {}

func (x *GetGraphStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphStatsResponse.ProtoReflect.Descriptor instead.
func (*GetGraphStatsResponse) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{28}
}

func (x *GetGraphStatsResponse) GetDomains() []*GraphStatsDomain {
	if x != nil {
		return x.Domains
	}
	return nil
}

// Entity counts for a single domain (e.g. "ci", "core", "plan").
type GraphStatsDomain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Items         []*GraphStatsItem      `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphStatsDomain) Reset() {
	*x = GraphStatsDomain{}
	mi := &file_gkg_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphStatsDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphStatsDomain) ProtoMessage() {}

func (x *GraphStatsDomain) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphStatsDomain.ProtoReflect.Descriptor instead.
func (*GraphStatsDomain) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{29}
}

func (x *GraphStatsDomain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GraphStatsDomain) GetItems() []*GraphStatsItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// Count for a single entity type (e.g. "Project": 42).
type GraphStatsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphStatsItem) Reset() {
	*x = GraphStatsItem{}
	mi := &file_gkg_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphStatsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphStatsItem) ProtoMessage() {}

func (x *GraphStatsItem) ProtoReflect() protoreflect.Message {
	mi := &file_gkg_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphStatsItem.ProtoReflect.Descriptor instead.
func (*GraphStatsItem) Descriptor() ([]byte, []int) {
	return file_gkg_proto_rawDescGZIP(), []int{30}
}

func (x *GraphStatsItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GraphStatsItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_gkg_proto protoreflect.FileDescriptor

const file_gkg_proto_rawDesc = "" +
	"\n" +
	"\tgkg.proto\x12\x06gkg.v1\"\xfd\x01\n" +
	"\x13ExecuteQueryMessage\x127\n" +
	"\arequest\x18\x01 \x01(\v2\x1b.gkg.v1.ExecuteQueryRequestH\x00R\arequest\x129\n" +
	"\tredaction\x18\x02 \x01(\v2\x19.gkg.v1.RedactionExchangeH\x00R\tredaction\x124\n" +
	"\x06result\x18\x03 \x01(\v2\x1a.gkg.v1.ExecuteQueryResultH\x00R\x06result\x121\n" +
	"\x05error\x18\x04 \x01(\v2\x19.gkg.v1.ExecuteQueryErrorH\x00R\x05errorB\t\n" +
	"\acontent\"\x8d\x01\n" +
	"\x13ExecuteQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12.\n" +
	"\x06format\x18\x02 \x01(\x0e2\x16.gkg.v1.ResponseFormatR\x06format\x120\n" +
	"\n" +
	"query_type\x18\x03 \x01(\x0e2\x11.gkg.v1.QueryTypeR\tqueryType\"\x9e\x01\n" +
	"\x12ExecuteQueryResult\x12!\n" +
	"\vresult_json\x18\x01 \x01(\tH\x00R\n" +
	"resultJson\x12'\n" +
	"\x0eformatted_text\x18\x02 \x01(\tH\x00R\rformattedText\x121\n" +
	"\bmetadata\x18\x03 \x01(\v2\x15.gkg.v1.QueryMetadataR\bmetadataB\t\n" +
	"\acontent\"\xd3\x01\n" +
	"\rQueryMetadata\x12\x1d\n" +
	"\n" +
	"query_type\x18\x01 \x01(\tR\tqueryType\x12*\n" +
	"\x11raw_query_strings\x18\x02 \x03(\tR\x0frawQueryStrings\x12\x1b\n" +
	"\trow_count\x18\x03 \x01(\x05R\browCount\x12%\n" +
	"\x0eformat_version\x18\x04 \x01(\tR\rformatVersion\x123\n" +
	"\vformat_name\x18\x05 \x01(\x0e2\x12.gkg.v1.FormatNameR\n" +
	"formatName\"A\n" +
	"\x11ExecuteQueryError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"j\n" +
	"\x15GetGraphSchemaRequest\x12!\n" +
	"\fexpand_nodes\x18\x01 \x03(\tR\vexpandNodes\x12.\n" +
	"\x06format\x18\x02 \x01(\x0e2\x16.gkg.v1.ResponseFormatR\x06format\"\x88\x01\n" +
	"\x16GetGraphSchemaResponse\x12:\n" +
	"\n" +
	"structured\x18\x01 \x01(\v2\x18.gkg.v1.StructuredSchemaH\x00R\n" +
	"structured\x12'\n" +
	"\x0eformatted_text\x18\x02 \x01(\tH\x00R\rformattedTextB\t\n" +
	"\acontent\"\xbd\x01\n" +
	"\x10StructuredSchema\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12.\n" +
	"\adomains\x18\x02 \x03(\v2\x14.gkg.v1.SchemaDomainR\adomains\x12(\n" +
	"\x05nodes\x18\x03 \x03(\v2\x12.gkg.v1.SchemaNodeR\x05nodes\x12(\n" +
	"\x05edges\x18\x04 \x03(\v2\x12.gkg.v1.SchemaEdgeR\x05edges\"c\n" +
	"\fSchemaDomain\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"node_names\x18\x03 \x03(\tR\tnodeNames\"\xd1\x02\n" +
	"\n" +
	"SchemaNode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vprimary_key\x18\x04 \x01(\tR\n" +
	"primaryKey\x12\x1f\n" +
	"\vlabel_field\x18\x05 \x01(\tR\n" +
	"labelField\x126\n" +
	"\n" +
	"properties\x18\x06 \x03(\v2\x16.gkg.v1.SchemaPropertyR\n" +
	"properties\x12-\n" +
	"\x05style\x18\a \x01(\v2\x17.gkg.v1.SchemaNodeStyleR\x05style\x12%\n" +
	"\x0eoutgoing_edges\x18\b \x03(\tR\routgoingEdges\x12%\n" +
	"\x0eincoming_edges\x18\t \x03(\tR\rincomingEdges\"~\n" +
	"\x0eSchemaProperty\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12\x1a\n" +
	"\bnullable\x18\x03 \x01(\bR\bnullable\x12\x1f\n" +
	"\venum_values\x18\x04 \x03(\tR\n" +
	"enumValues\"y\n" +
	"\n" +
	"SchemaEdge\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x125\n" +
	"\bvariants\x18\x03 \x03(\v2\x19.gkg.v1.SchemaEdgeVariantR\bvariants\"U\n" +
	"\x11SchemaEdgeVariant\x12\x1f\n" +
	"\vsource_type\x18\x01 \x01(\tR\n" +
	"sourceType\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\tR\n" +
	"targetType\";\n" +
	"\x0fSchemaNodeStyle\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\"\x90\x01\n" +
	"\x11RedactionExchange\x127\n" +
	"\brequired\x18\x01 \x01(\v2\x19.gkg.v1.RedactionRequiredH\x00R\brequired\x127\n" +
	"\bresponse\x18\x02 \x01(\v2\x19.gkg.v1.RedactionResponseH\x00R\bresponseB\t\n" +
	"\acontent\"k\n" +
	"\x11RedactionRequired\x12\x1b\n" +
	"\tresult_id\x18\x01 \x01(\tR\bresultId\x129\n" +
	"\tresources\x18\x02 \x03(\v2\x1b.gkg.v1.ResourceToAuthorizeR\tresources\"{\n" +
	"\x13ResourceToAuthorize\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12!\n" +
	"\fresource_ids\x18\x02 \x03(\x03R\vresourceIds\x12\x1c\n" +
	"\tabilities\x18\x03 \x03(\tR\tabilities\"w\n" +
	"\x11RedactionResponse\x12\x1b\n" +
	"\tresult_id\x18\x01 \x01(\tR\bresultId\x12E\n" +
	"\x0eauthorizations\x18\x02 \x03(\v2\x1d.gkg.v1.ResourceAuthorizationR\x0eauthorizations\"\xca\x01\n" +
	"\x15ResourceAuthorization\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12M\n" +
	"\n" +
	"authorized\x18\x02 \x03(\v2-.gkg.v1.ResourceAuthorization.AuthorizedEntryR\n" +
	"authorized\x1a=\n" +
	"\x0fAuthorizedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\x12\n" +
	"\x10ListToolsRequest\"A\n" +
	"\x11ListToolsResponse\x12,\n" +
	"\x05tools\x18\x01 \x03(\v2\x16.gkg.v1.ToolDefinitionR\x05tools\"|\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x124\n" +
	"\x16parameters_json_schema\x18\x03 \x01(\tR\x14parametersJsonSchema\"I\n" +
	"\x17GetClusterHealthRequest\x12.\n" +
	"\x06format\x18\x01 \x01(\x0e2\x16.gkg.v1.ResponseFormatR\x06format\"\x91\x01\n" +
	"\x18GetClusterHealthResponse\x12A\n" +
	"\n" +
	"structured\x18\x01 \x01(\v2\x1f.gkg.v1.StructuredClusterHealthH\x00R\n" +
	"structured\x12'\n" +
	"\x0eformatted_text\x18\x02 \x01(\tH\x00R\rformattedTextB\t\n" +
	"\acontent\"\xb9\x01\n" +
	"\x17StructuredClusterHealth\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.gkg.v1.ClusterStatusR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x127\n" +
	"\n" +
	"components\x18\x04 \x03(\v2\x17.gkg.v1.ComponentHealthR\n" +
	"components\"\x83\x02\n" +
	"\x0fComponentHealth\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.gkg.v1.ClusterStatusR\x06status\x121\n" +
	"\breplicas\x18\x03 \x01(\v2\x15.gkg.v1.ReplicaStatusR\breplicas\x12>\n" +
	"\ametrics\x18\x04 \x03(\v2$.gkg.v1.ComponentHealth.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\rReplicaStatus\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\x05R\x05ready\x12\x18\n" +
	"\adesired\x18\x02 \x01(\x05R\adesired\"=\n" +
	"\x14GetGraphStatsRequest\x12%\n" +
	"\x0etraversal_path\x18\x01 \x01(\tR\rtraversalPath\"K\n" +
	"\x15GetGraphStatsResponse\x122\n" +
	"\adomains\x18\x01 \x03(\v2\x18.gkg.v1.GraphStatsDomainR\adomains\"T\n" +
	"\x10GraphStatsDomain\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.gkg.v1.GraphStatsItemR\x05items\":\n" +
	"\x0eGraphStatsItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count*B\n" +
	"\x0eResponseFormat\x12\x17\n" +
	"\x13RESPONSE_FORMAT_RAW\x10\x00\x12\x17\n" +
	"\x13RESPONSE_FORMAT_LLM\x10\x01*j\n" +
	"\n" +
	"FormatName\x12\x1b\n" +
	"\x17FORMAT_NAME_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fFORMAT_NAME_RAW\x10\x01\x12\x14\n" +
	"\x10FORMAT_NAME_GOON\x10\x02\x12\x14\n" +
	"\x10FORMAT_NAME_TOON\x10\x03* \n" +
	"\tQueryType\x12\x13\n" +
	"\x0fQUERY_TYPE_JSON\x10\x00*\x86\x01\n" +
	"\rClusterStatus\x12\x1e\n" +
	"\x1aCLUSTER_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CLUSTER_STATUS_HEALTHY\x10\x01\x12\x1b\n" +
	"\x17CLUSTER_STATUS_DEGRADED\x10\x02\x12\x1c\n" +
	"\x18CLUSTER_STATUS_UNHEALTHY\x10\x032\x9d\x03\n" +
	"\x15KnowledgeGraphService\x12@\n" +
	"\tListTools\x12\x18.gkg.v1.ListToolsRequest\x1a\x19.gkg.v1.ListToolsResponse\x12L\n" +
	"\fExecuteQuery\x12\x1b.gkg.v1.ExecuteQueryMessage\x1a\x1b.gkg.v1.ExecuteQueryMessage(\x010\x01\x12O\n" +
	"\x0eGetGraphSchema\x12\x1d.gkg.v1.GetGraphSchemaRequest\x1a\x1e.gkg.v1.GetGraphSchemaResponse\x12U\n" +
	"\x10GetClusterHealth\x12\x1f.gkg.v1.GetClusterHealthRequest\x1a .gkg.v1.GetClusterHealthResponse\x12L\n" +
	"\rGetGraphStats\x12\x1c.gkg.v1.GetGraphStatsRequest\x1a\x1d.gkg.v1.GetGraphStatsResponseb\x06proto3"

var (
	file_gkg_proto_rawDescOnce sync.Once
	file_gkg_proto_rawDescData []byte
)

func file_gkg_proto_rawDescGZIP() []byte {
	file_gkg_proto_rawDescOnce.Do(func() {
		file_gkg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gkg_proto_rawDesc), len(file_gkg_proto_rawDesc)))
	})
	return file_gkg_proto_rawDescData
}

var file_gkg_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_gkg_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_gkg_proto_goTypes = []any{
	(ResponseFormat)(0),              // 0: gkg.v1.ResponseFormat
	(FormatName)(0),                  // 1: gkg.v1.FormatName
	(QueryType)(0),                   // 2: gkg.v1.QueryType
	(ClusterStatus)(0),               // 3: gkg.v1.ClusterStatus
	(*ExecuteQueryMessage)(nil),      // 4: gkg.v1.ExecuteQueryMessage
	(*ExecuteQueryRequest)(nil),      // 5: gkg.v1.ExecuteQueryRequest
	(*ExecuteQueryResult)(nil),       // 6: gkg.v1.ExecuteQueryResult
	(*QueryMetadata)(nil),            // 7: gkg.v1.QueryMetadata
	(*ExecuteQueryError)(nil),        // 8: gkg.v1.ExecuteQueryError
	(*GetGraphSchemaRequest)(nil),    // 9: gkg.v1.GetGraphSchemaRequest
	(*GetGraphSchemaResponse)(nil),   // 10: gkg.v1.GetGraphSchemaResponse
	(*StructuredSchema)(nil),         // 11: gkg.v1.StructuredSchema
	(*SchemaDomain)(nil),             // 12: gkg.v1.SchemaDomain
	(*SchemaNode)(nil),               // 13: gkg.v1.SchemaNode
	(*SchemaProperty)(nil),           // 14: gkg.v1.SchemaProperty
	(*SchemaEdge)(nil),               // 15: gkg.v1.SchemaEdge
	(*SchemaEdgeVariant)(nil),        // 16: gkg.v1.SchemaEdgeVariant
	(*SchemaNodeStyle)(nil),          // 17: gkg.v1.SchemaNodeStyle
	(*RedactionExchange)(nil),        // 18: gkg.v1.RedactionExchange
	(*RedactionRequired)(nil),        // 19: gkg.v1.RedactionRequired
	(*ResourceToAuthorize)(nil),      // 20: gkg.v1.ResourceToAuthorize
	(*RedactionResponse)(nil),        // 21: gkg.v1.RedactionResponse
	(*ResourceAuthorization)(nil),    // 22: gkg.v1.ResourceAuthorization
	(*ListToolsRequest)(nil),         // 23: gkg.v1.ListToolsRequest
	(*ListToolsResponse)(nil),        // 24: gkg.v1.ListToolsResponse
	(*ToolDefinition)(nil),           // 25: gkg.v1.ToolDefinition
	(*GetClusterHealthRequest)(nil),  // 26: gkg.v1.GetClusterHealthRequest
	(*GetClusterHealthResponse)(nil), // 27: gkg.v1.GetClusterHealthResponse
	(*StructuredClusterHealth)(nil),  // 28: gkg.v1.StructuredClusterHealth
	(*ComponentHealth)(nil),          // 29: gkg.v1.ComponentHealth
	(*ReplicaStatus)(nil),            // 30: gkg.v1.ReplicaStatus
	(*GetGraphStatsRequest)(nil),     // 31: gkg.v1.GetGraphStatsRequest
	(*GetGraphStatsResponse)(nil),    // 32: gkg.v1.GetGraphStatsResponse
	(*GraphStatsDomain)(nil),         // 33: gkg.v1.GraphStatsDomain
	(*GraphStatsItem)(nil),           // 34: gkg.v1.GraphStatsItem
	nil,                              // 35: gkg.v1.ResourceAuthorization.AuthorizedEntry
	nil,                              // 36: gkg.v1.ComponentHealth.MetricsEntry
}
var file_gkg_proto_depIdxs = []int32{
	5,  // 0: gkg.v1.ExecuteQueryMessage.request:type_name -> gkg.v1.ExecuteQueryRequest
	18, // 1: gkg.v1.ExecuteQueryMessage.redaction:type_name -> gkg.v1.RedactionExchange
	6,  // 2: gkg.v1.ExecuteQueryMessage.result:type_name -> gkg.v1.ExecuteQueryResult
	8,  // 3: gkg.v1.ExecuteQueryMessage.error:type_name -> gkg.v1.ExecuteQueryError
	0,  // 4: gkg.v1.ExecuteQueryRequest.format:type_name -> gkg.v1.ResponseFormat
	2,  // 5: gkg.v1.ExecuteQueryRequest.query_type:type_name -> gkg.v1.QueryType
	7,  // 6: gkg.v1.ExecuteQueryResult.metadata:type_name -> gkg.v1.QueryMetadata
	1,  // 7: gkg.v1.QueryMetadata.format_name:type_name -> gkg.v1.FormatName
	0,  // 8: gkg.v1.GetGraphSchemaRequest.format:type_name -> gkg.v1.ResponseFormat
	11, // 9: gkg.v1.GetGraphSchemaResponse.structured:type_name -> gkg.v1.StructuredSchema
	12, // 10: gkg.v1.StructuredSchema.domains:type_name -> gkg.v1.SchemaDomain
	13, // 11: gkg.v1.StructuredSchema.nodes:type_name -> gkg.v1.SchemaNode
	15, // 12: gkg.v1.StructuredSchema.edges:type_name -> gkg.v1.SchemaEdge
	14, // 13: gkg.v1.SchemaNode.properties:type_name -> gkg.v1.SchemaProperty
	17, // 14: gkg.v1.SchemaNode.style:type_name -> gkg.v1.SchemaNodeStyle
	16, // 15: gkg.v1.SchemaEdge.variants:type_name -> gkg.v1.SchemaEdgeVariant
	19, // 16: gkg.v1.RedactionExchange.required:type_name -> gkg.v1.RedactionRequired
	21, // 17: gkg.v1.RedactionExchange.response:type_name -> gkg.v1.RedactionResponse
	20, // 18: gkg.v1.RedactionRequired.resources:type_name -> gkg.v1.ResourceToAuthorize
	22, // 19: gkg.v1.RedactionResponse.authorizations:type_name -> gkg.v1.ResourceAuthorization
	35, // 20: gkg.v1.ResourceAuthorization.authorized:type_name -> gkg.v1.ResourceAuthorization.AuthorizedEntry
	25, // 21: gkg.v1.ListToolsResponse.tools:type_name -> gkg.v1.ToolDefinition
	0,  // 22: gkg.v1.GetClusterHealthRequest.format:type_name -> gkg.v1.ResponseFormat
	28, // 23: gkg.v1.GetClusterHealthResponse.structured:type_name -> gkg.v1.StructuredClusterHealth
	3,  // 24: gkg.v1.StructuredClusterHealth.status:type_name -> gkg.v1.ClusterStatus
	29, // 25: gkg.v1.StructuredClusterHealth.components:type_name -> gkg.v1.ComponentHealth
	3,  // 26: gkg.v1.ComponentHealth.status:type_name -> gkg.v1.ClusterStatus
	30, // 27: gkg.v1.ComponentHealth.replicas:type_name -> gkg.v1.ReplicaStatus
	36, // 28: gkg.v1.ComponentHealth.metrics:type_name -> gkg.v1.ComponentHealth.MetricsEntry
	33, // 29: gkg.v1.GetGraphStatsResponse.domains:type_name -> gkg.v1.GraphStatsDomain
	34, // 30: gkg.v1.GraphStatsDomain.items:type_name -> gkg.v1.GraphStatsItem
	23, // 31: gkg.v1.KnowledgeGraphService.ListTools:input_type -> gkg.v1.ListToolsRequest
	4,  // 32: gkg.v1.KnowledgeGraphService.ExecuteQuery:input_type -> gkg.v1.ExecuteQueryMessage
	9,  // 33: gkg.v1.KnowledgeGraphService.GetGraphSchema:input_type -> gkg.v1.GetGraphSchemaRequest
	26, // 34: gkg.v1.KnowledgeGraphService.GetClusterHealth:input_type -> gkg.v1.GetClusterHealthRequest
	31, // 35: gkg.v1.KnowledgeGraphService.GetGraphStats:input_type -> gkg.v1.GetGraphStatsRequest
	24, // 36: gkg.v1.KnowledgeGraphService.ListTools:output_type -> gkg.v1.ListToolsResponse
	4,  // 37: gkg.v1.KnowledgeGraphService.ExecuteQuery:output_type -> gkg.v1.ExecuteQueryMessage
	10, // 38: gkg.v1.KnowledgeGraphService.GetGraphSchema:output_type -> gkg.v1.GetGraphSchemaResponse
	27, // 39: gkg.v1.KnowledgeGraphService.GetClusterHealth:output_type -> gkg.v1.GetClusterHealthResponse
	32, // 40: gkg.v1.KnowledgeGraphService.GetGraphStats:output_type -> gkg.v1.GetGraphStatsResponse
	36, // [36:41] is the sub-list for method output_type
	31, // [31:36] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_gkg_proto_init() }
func file_gkg_proto_init() {
	if File_gkg_proto != nil {
		return
	}
	file_gkg_proto_msgTypes[0].OneofWrappers = []any{
		(*ExecuteQueryMessage_Request)(nil),
		(*ExecuteQueryMessage_Redaction)(nil),
		(*ExecuteQueryMessage_Result)(nil),
		(*ExecuteQueryMessage_Error)(nil),
	}
	file_gkg_proto_msgTypes[2].OneofWrappers = []any{
		(*ExecuteQueryResult_ResultJson)(nil),
		(*ExecuteQueryResult_FormattedText)(nil),
	}
	file_gkg_proto_msgTypes[6].OneofWrappers = []any{
		(*GetGraphSchemaResponse_Structured)(nil),
		(*GetGraphSchemaResponse_FormattedText)(nil),
	}
	file_gkg_proto_msgTypes[14].OneofWrappers = []any{
		(*RedactionExchange_Required)(nil),
		(*RedactionExchange_Response)(nil),
	}
	file_gkg_proto_msgTypes[23].OneofWrappers = []any{
		(*GetClusterHealthResponse_Structured)(nil),
		(*GetClusterHealthResponse_FormattedText)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gkg_proto_rawDesc), len(file_gkg_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gkg_proto_goTypes,
		DependencyIndexes: file_gkg_proto_depIdxs,
		EnumInfos:         file_gkg_proto_enumTypes,
		MessageInfos:      file_gkg_proto_msgTypes,
	}.Build()
	File_gkg_proto = out.File
	file_gkg_proto_goTypes = nil
	file_gkg_proto_depIdxs = nil
}
