#[global_allocator]
static GLOBAL: mimalloc::MiMalloc = mimalloc::MiMalloc;

mod sql;
mod sql_format;
mod workspace;

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use gitalisk_core::repository::gitalisk_repository::IterFileOptions;
use ontology::Ontology;
use serde::Serialize;
use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;
use tracing::{Level, info};
use tracing_subscriber::fmt::format::FmtSpan;

/// Generate the full DuckDB DDL (graph tables + manifest) from the ontology.
fn generate_local_ddl(ontology: &Ontology) -> String {
    let schema_version = include_str!("../../../config/SCHEMA_VERSION").trim();
    let tables = query_engine::compiler::generate_local_tables(ontology);
    let mut ddl = format!(
        "-- SCHEMA_VERSION={schema_version} [AUTOGENERATED — DO NOT EDIT MANUALLY]\n\
         -- Regenerate with: mise schema:generate:ddl:local\n\n"
    );
    for t in &tables {
        ddl.push_str(&format!(
            "{};\n\n",
            query_engine::compiler::emit_duckdb_create_table(t)
        ));
    }
    ddl.push_str(duckdb_client::MANIFEST_DDL);
    ddl
}

#[derive(Serialize)]
struct IndexOutput {
    repository: String,
    path: String,
    time_seconds: f64,
    graph: GraphStats,
    processing: ProcessingStats,
    #[serde(skip_serializing_if = "Option::is_none")]
    database_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    detailed: Option<DetailedStats>,
}

#[derive(Serialize)]
struct GraphStats {
    directories: usize,
    files: usize,
    definitions: usize,
    imported_symbols: usize,
    relationships: usize,
}

#[derive(Serialize)]
struct ProcessingStats {
    skipped_files: usize,
    errored_files: usize,
}

#[derive(Debug, Clone, Default)]
struct IndexGraphStats {
    directories: usize,
    files: usize,
    definitions: usize,
    imported_symbols: usize,
    relationships: usize,
    relationship_types: HashMap<String, usize>,
    definition_types: HashMap<String, usize>,
}

struct IndexRunResult {
    total_processing_time: Duration,
    skipped_files: Vec<code_graph::v2::SkippedFile>,
    faulted_files: Vec<code_graph::v2::FaultedFile>,
    graph_stats: IndexGraphStats,
    database_path: Option<String>,
}

#[derive(Serialize)]
struct DetailedStats {
    #[serde(skip_serializing_if = "Vec::is_empty")]
    skipped_files: Vec<SkippedFile>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    errored_files: Vec<ErroredFile>,
    relationship_types: HashMap<String, usize>,
    definition_types: HashMap<String, usize>,
}

#[derive(Serialize)]
struct SkippedFile {
    path: String,
    reason: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    detail: String,
}

#[derive(Serialize)]
struct ErroredFile {
    path: String,
    kind: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    detail: String,
}

#[derive(Parser)]
#[command(name = "orbit")]
#[command(about = "Orbit - local code indexing and query CLI")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Index a code repository and output graph statistics as JSON
    Index {
        /// Path to the repository to index
        #[arg(value_name = "PATH")]
        path: PathBuf,

        /// Number of worker threads (0 = auto-detect based on CPU cores)
        #[arg(short, long, default_value = "0")]
        threads: usize,

        /// Include detailed statistics in output
        #[arg(short, long)]
        stats: bool,

        /// Verbose logging to stderr
        #[arg(short, long)]
        verbose: bool,
    },
    /// Run a raw read-only SQL query against the local DuckDB graph.
    Sql {
        /// SQL query, or `-` to read from stdin.
        #[arg(value_name = "QUERY", conflicts_with = "file")]
        query: Option<String>,

        /// Read SQL from a file.
        #[arg(long, short, value_name = "PATH")]
        file: Option<PathBuf>,

        /// Output format.
        #[arg(long, short = 'F', default_value = "table")]
        format: sql::Format,

        /// Override the DuckDB path (default: ~/.orbit/graph.duckdb).
        #[arg(long, value_name = "PATH")]
        db: Option<PathBuf>,
    },
    /// Describe the schema of the local DuckDB graph.
    Schema {
        /// Override the DuckDB path (default: ~/.orbit/graph.duckdb).
        #[arg(long, value_name = "PATH")]
        db: Option<PathBuf>,

        /// Emit JSON instead of the default table view.
        #[arg(long)]
        raw: bool,
    },
    /// Maintainer-only tools (DDL generation, etc.)
    Debug {
        #[command(subcommand)]
        command: DebugCommands,
    },
}

#[derive(Subcommand)]
enum DebugCommands {
    /// Generate ClickHouse DDL from the ontology
    Ddl {
        /// Path to ontology directory (default: embedded)
        #[arg(long, short)]
        ontology: Option<PathBuf>,

        /// Table prefix (e.g., "v1_" for schema version 1)
        #[arg(long, short, default_value = "")]
        prefix: String,

        /// Diff generated DDL against an existing .sql file
        #[arg(long, short)]
        diff: Option<PathBuf>,
    },
    /// Generate DuckDB DDL from the ontology (local graph tables + manifest)
    DdlLocal {
        /// Path to ontology directory (default: embedded)
        #[arg(long, short)]
        ontology: Option<PathBuf>,
    },
}

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Index {
            path,
            threads,
            stats,
            verbose,
        } => {
            let level = if verbose { Level::DEBUG } else { Level::WARN };
            let subscriber = tracing_subscriber::fmt()
                .with_max_level(level)
                .with_target(verbose)
                .with_level(verbose)
                .with_ansi(true)
                .without_time()
                .with_span_events(if verbose {
                    FmtSpan::CLOSE
                } else {
                    FmtSpan::NONE
                })
                .with_writer(std::io::stderr)
                .finish();
            tracing::subscriber::set_global_default(subscriber)
                .expect("setting default subscriber failed");

            run_index(path, threads, stats).await
        }
        Commands::Sql {
            query,
            file,
            format,
            db,
        } => sql::run(query, file, format, db),
        Commands::Schema { db, raw } => run_schema(db, raw),
        Commands::Debug { command } => match command {
            DebugCommands::Ddl {
                ontology,
                prefix,
                diff,
            } => run_ddl(ontology, prefix, diff),
            DebugCommands::DdlLocal { ontology } => {
                let ont = match ontology {
                    Some(path) => {
                        Ontology::load_from_dir(&path).context("failed to load ontology")?
                    }
                    None => {
                        Ontology::load_embedded().context("failed to load embedded ontology")?
                    }
                };
                print!("{}", generate_local_ddl(&ont));
                Ok(())
            }
        },
    }
}

/// Describe the local DuckDB schema by reading `information_schema` from the
/// graph database. Skips DuckDB's own `*_schema` namespaces.
fn run_schema(db: Option<PathBuf>, raw: bool) -> Result<()> {
    let db_path = match db {
        Some(p) => p,
        None => workspace::Workspace::open_default()?.db_path(),
    };
    if !db_path.exists() {
        anyhow::bail!(
            "no local graph found at {}. Run `orbit index` first.",
            db_path.display()
        );
    }

    let client = duckdb_client::DuckDbClient::open_read_only(&db_path)
        .with_context(|| format!("failed to open {}", db_path.display()))?;
    let sql = "SELECT table_name, column_name, data_type \
               FROM information_schema.columns \
               WHERE table_schema = 'main' \
               ORDER BY table_name, ordinal_position";
    let batches = client
        .query_arrow(sql)
        .context("failed to read information_schema.columns")?;

    let stdout = std::io::stdout().lock();
    if raw {
        sql_format::write_json(stdout, &batches)
    } else {
        sql_format::write_table(stdout, &batches)
    }
}

fn run_ddl(ontology_path: Option<PathBuf>, prefix: String, diff: Option<PathBuf>) -> Result<()> {
    let ont = match ontology_path {
        Some(path) => Ontology::load_from_dir(&path).context("failed to load ontology")?,
        None => Ontology::load_embedded().context("failed to load embedded ontology")?,
    };

    let tables = query_engine::compiler::generate_graph_tables(&ont);
    let generated: Vec<String> = tables
        .iter()
        .map(|t| {
            let t = if prefix.is_empty() {
                t.clone()
            } else {
                t.clone().with_prefix(&prefix)
            };
            format!("{};\n", query_engine::compiler::emit_create_table(&t))
        })
        .collect();

    let schema_version = include_str!("../../../config/SCHEMA_VERSION").trim();

    match diff {
        Some(path) => run_schema_diff(&generated, &path),
        None => {
            println!("-- SCHEMA_VERSION={schema_version} [AUTOGENERATED — DO NOT EDIT MANUALLY]");
            println!("-- Regenerate with: mise schema:generate:ddl");
            println!();
            for stmt in &generated {
                println!("{stmt}");
            }
            Ok(())
        }
    }
}

/// Extracts `CREATE TABLE IF NOT EXISTS` statements from SQL, keyed by table name.
/// Splits on top-level semicolons and extracts the table name from each statement.
fn extract_tables_from_sql(sql: &str) -> std::collections::BTreeMap<String, String> {
    let mut tables = std::collections::BTreeMap::new();
    let mut depth = 0i32;
    let mut in_string = false;
    let mut start = 0;

    for (i, c) in sql.char_indices() {
        match c {
            '\'' if !in_string || (i > 0 && sql.as_bytes()[i - 1] != b'\\') => {
                in_string = !in_string;
            }
            '(' if !in_string => depth += 1,
            ')' if !in_string => depth -= 1,
            ';' if !in_string && depth == 0 => {
                let stmt = sql[start..=i].trim();
                if let Some(name) = extract_create_table_name(stmt) {
                    tables.insert(name, strip_leading_comments(stmt).to_string());
                }
                start = i + 1;
            }
            _ => {}
        }
    }

    tables
}

/// Strips leading SQL comments and blank lines from a statement.
fn strip_leading_comments(stmt: &str) -> &str {
    let mut start = 0;
    for line in stmt.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with("--") {
            start += line.len() + 1; // +1 for newline
        } else {
            break;
        }
    }
    if start >= stmt.len() {
        stmt
    } else {
        &stmt[start..]
    }
}

/// Extracts the table name from a `CREATE TABLE IF NOT EXISTS <name>` statement.
fn extract_create_table_name(stmt: &str) -> Option<String> {
    let upper = stmt.to_uppercase();
    let marker = "CREATE TABLE IF NOT EXISTS ";
    let pos = upper.find(marker)?;
    let after = &stmt[pos + marker.len()..];
    let name = after
        .split(|c: char| c.is_whitespace() || c == '(')
        .next()?;
    if name.is_empty() {
        None
    } else {
        Some(name.to_string())
    }
}

fn run_schema_diff(generated_stmts: &[String], sql_path: &PathBuf) -> Result<()> {
    let existing_sql = std::fs::read_to_string(sql_path)
        .with_context(|| format!("failed to read {}", sql_path.display()))?;

    let existing = extract_tables_from_sql(&existing_sql);
    let generated_sql = generated_stmts.join("\n");
    let generated = extract_tables_from_sql(&generated_sql);

    let all_names: std::collections::BTreeSet<&str> = existing
        .keys()
        .chain(generated.keys())
        .map(|s| s.as_str())
        .collect();

    let mut ok = 0u32;
    let mut diffs = 0u32;
    let mut missing = 0u32;
    let mut extra = 0u32;

    for name in &all_names {
        // Skip control tables that aren't generated from ontology
        if *name == "gkg_schema_version" {
            continue;
        }

        match (existing.get(*name), generated.get(*name)) {
            (Some(_), None) => {
                eprintln!("MISSING from generated: {name}");
                missing += 1;
            }
            (None, Some(_)) => {
                eprintln!("EXTRA in generated: {name}");
                extra += 1;
            }
            (Some(exp), Some(got)) => {
                if exp.trim() == got.trim() {
                    ok += 1;
                } else {
                    diffs += 1;
                    eprintln!("DIFF: {name}");
                    let exp_lines: Vec<&str> = exp.lines().collect();
                    let got_lines: Vec<&str> = got.lines().collect();
                    let max = exp_lines.len().max(got_lines.len());
                    for i in 0..max {
                        let e = exp_lines.get(i).map(|s| s.trim()).unwrap_or("<missing>");
                        let g = got_lines.get(i).map(|s| s.trim()).unwrap_or("<missing>");
                        if e != g {
                            eprintln!("  L{i}: exp: {e}");
                            eprintln!("  L{i}: got: {g}");
                        }
                    }
                }
            }
            (None, None) => unreachable!(),
        }
    }

    eprintln!();
    eprintln!("{ok} OK, {diffs} DIFF, {missing} MISSING, {extra} EXTRA");

    if diffs > 0 || missing > 0 || extra > 0 {
        anyhow::bail!("DDL mismatch: {diffs} tables differ, {missing} missing, {extra} extra");
    }

    eprintln!("All tables match.");
    Ok(())
}

async fn run_index(path: PathBuf, threads: usize, show_stats: bool) -> Result<()> {
    let store = workspace::Workspace::open_default()?;
    let repos = store.resolve_repos(&path)?;

    if repos.is_empty() {
        info!("No git repositories found in {}", path.display());
        return Ok(());
    }

    let ontology = Ontology::load_embedded().context("failed to load embedded ontology")?;

    // Ensure schema exists, then drop the connection so we don't hold
    // the write lock during parsing.
    {
        let db_path = store.db_path();
        let client =
            duckdb_client::DuckDbClient::open(&db_path).context("failed to open DuckDB")?;
        let ddl = generate_local_ddl(&ontology);
        client
            .initialize_schema(&ddl)
            .context("failed to create schema")?;
    }

    let pipeline_config = code_graph::v2::PipelineConfig {
        max_file_size: 5_000_000,
        worker_threads: threads,
        per_file_timeout: Some(std::time::Duration::from_secs(2)),
        cross_file_resolve_timeout: Some(std::time::Duration::from_secs(180)),
        ..Default::default()
    };

    let mut failed = 0usize;

    for repo_path in &repos {
        let git = match workspace::git_info(repo_path) {
            Ok(g) => g,
            Err(e) => {
                tracing::error!("skipping {}: {e:#}", repo_path.display());
                failed += 1;
                continue;
            }
        };
        let key = git.repo_path.to_string_lossy().to_string();
        let db_path = store.db_path();

        info!(
            "Indexing repository at: {} (branch: {}, commit: {})",
            key,
            git.branch,
            git.commit_sha.get(..8).unwrap_or(&git.commit_sha)
        );

        // Mark as indexing before we start parsing.
        {
            let client =
                duckdb_client::DuckDbClient::open(&db_path).context("failed to open DuckDB")?;
            workspace::set_status(
                &client,
                &key,
                git.project_id,
                workspace::RepoStatus::Indexing,
                None,
                Some(&git),
            )?;
        }

        let result = index_repo(&git, &store, &ontology, pipeline_config.clone()).await;
        match result {
            Ok(result) => {
                let repo_name = git
                    .repo_path
                    .file_name()
                    .map(|n| n.to_string_lossy().to_string())
                    .unwrap_or_else(|| "repository".to_string());
                let mut output = build_index_output(&repo_name, &key, &result, show_stats);
                output.database_path = Some(db_path.display().to_string());
                println!("{}", serde_json::to_string_pretty(&output)?);
            }
            Err(e) => {
                tracing::error!("failed to index {key}: {e:#}");
                failed += 1;
                if let Ok(client) = duckdb_client::DuckDbClient::open(&db_path)
                    && let Err(manifest_err) = workspace::set_status(
                        &client,
                        &key,
                        git.project_id,
                        workspace::RepoStatus::Error,
                        Some(&e.to_string()),
                        None,
                    )
                {
                    tracing::warn!("failed to record error status in manifest: {manifest_err}");
                }
            }
        }
    }

    if failed > 0 {
        anyhow::bail!("{failed} of {} repositories failed to index", repos.len());
    }
    Ok(())
}

async fn index_repo(
    git: &workspace::GitInfo,
    store: &workspace::Workspace,
    ontology: &Ontology,
    pipeline_config: code_graph::v2::PipelineConfig,
) -> Result<IndexRunResult> {
    let key = git.repo_path.to_string_lossy().to_string();
    let root_path = key.clone();
    let start_time = std::time::Instant::now();

    let tracer = code_graph::v2::trace::Tracer::new(false);
    let file_inventory = gitalisk_file_inventory(git)?;

    let db_path = store.db_path();
    let client =
        duckdb_client::DuckDbClient::open(&db_path).context("failed to open DuckDB for writing")?;

    let node_tables: Vec<String> = ontology
        .local_entity_names()
        .iter()
        .map(|name| {
            ontology
                .get_node(name)
                .expect("local entity must exist")
                .destination_table
                .clone()
        })
        .collect();
    let edge_table = ontology
        .local_edge_table_name()
        .context("local_db.edge_table.name must be configured")?;

    client
        .delete_project(git.project_id, &node_tables, edge_table)
        .context("failed to clear existing project data")?;

    let converter: std::sync::Arc<dyn code_graph::v2::GraphConverter> =
        std::sync::Arc::new(duckdb_client::DuckDbConverter {
            project_id: git.project_id,
            branch: git.branch.clone(),
            commit_sha: git.commit_sha.clone(),
            ontology: std::sync::Arc::new(ontology.clone()),
        });
    let sink: std::sync::Arc<dyn code_graph::v2::BatchSink> =
        std::sync::Arc::new(duckdb_client::DuckDbSink::new(client));

    let v2_result = code_graph::v2::Pipeline::run_with_tracer(
        std::path::Path::new(&root_path),
        file_inventory,
        pipeline_config.clone(),
        tracer,
        converter,
        sink,
    );

    if !v2_result.errors.is_empty() {
        for err in &v2_result.errors {
            tracing::warn!("pipeline error: {} ({})", err.error, err.file_path);
        }
    }
    // Re-open for workspace status (client was moved into sink)
    let client =
        duckdb_client::DuckDbClient::open(&db_path).context("failed to open DuckDB for status")?;
    workspace::set_status(
        &client,
        &key,
        git.project_id,
        workspace::RepoStatus::Indexed,
        None,
        Some(git),
    )?;

    for err in &v2_result.errors {
        tracing::warn!(stage = err.stage, error = %err.error, "task-level pipeline error");
    }

    Ok(IndexRunResult {
        total_processing_time: start_time.elapsed(),
        skipped_files: v2_result.skipped,
        faulted_files: v2_result.faults,
        graph_stats: IndexGraphStats {
            directories: v2_result.stats.directories_indexed,
            files: v2_result.stats.files_indexed,
            definitions: v2_result.stats.definitions_count,
            imported_symbols: v2_result.stats.imports_count,
            relationships: v2_result.stats.edges_count,
            relationship_types: HashMap::new(),
            definition_types: HashMap::new(),
        },
        database_path: Some(db_path.display().to_string()),
    })
}

fn gitalisk_file_inventory(
    git: &workspace::GitInfo,
) -> Result<Arc<[code_graph::v2::FileInventoryEntry]>> {
    let files = git
        .repository()
        .get_repo_files(IterFileOptions {
            include_ignored: false,
            include_hidden: true,
            exclude_patterns: Vec::new(),
        })
        .with_context(|| {
            format!(
                "failed to list repository files with Gitalisk in {}",
                git.repo_path.display()
            )
        })?;

    let entries: Vec<_> = files
        .into_iter()
        .map(|file| {
            let path = file.path();
            let relative_path = path
                .strip_prefix(&git.repo_path)
                .unwrap_or(path)
                .to_string_lossy()
                .to_string();
            let size = std::fs::symlink_metadata(path)
                .with_context(|| format!("failed to read metadata for {}", path.display()))?
                .len();
            Ok(code_graph::v2::FileInventoryEntry {
                path: relative_path,
                size,
            })
        })
        .collect::<Result<_>>()?;
    Ok(Arc::from(entries))
}

fn build_index_output(
    repo_name: &str,
    path: &str,
    result: &IndexRunResult,
    show_stats: bool,
) -> IndexOutput {
    let stats = &result.graph_stats;
    let graph = GraphStats {
        directories: stats.directories,
        files: stats.files,
        definitions: stats.definitions,
        imported_symbols: stats.imported_symbols,
        relationships: stats.relationships,
    };

    let detailed = show_stats.then(|| DetailedStats {
        skipped_files: result
            .skipped_files
            .iter()
            .map(|s| SkippedFile {
                path: s.path.clone(),
                reason: s.kind.as_metric_label().to_string(),
                detail: s.detail.clone(),
            })
            .collect(),
        errored_files: result
            .faulted_files
            .iter()
            .map(|f| ErroredFile {
                path: f.path.clone(),
                kind: f.kind.as_metric_label().to_string(),
                detail: f.detail.clone(),
            })
            .collect(),
        relationship_types: stats.relationship_types.clone(),
        definition_types: stats.definition_types.clone(),
    });

    IndexOutput {
        repository: repo_name.to_string(),
        path: path.to_string(),
        time_seconds: result.total_processing_time.as_secs_f64(),
        graph,
        processing: ProcessingStats {
            skipped_files: result.skipped_files.len(),
            errored_files: result.faulted_files.len(),
        },
        database_path: result.database_path.clone(),
        detailed,
    }
}
