{{- if and .Values.dispatcher.enabled .Values.metrics.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "gkg.fullname" . }}-dispatcher
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gkg.componentLabels" (dict "root" . "component" "dispatcher") | nindent 4 }}
spec:
  {{- with .Values.metrics.prometheus.podTargetLabels }}
  podTargetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gkg.componentSelectorLabels" (dict "root" . "component" "dispatcher") | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
{{- end }}
